module.exports = `    { name: \`The Lighthouse\`, owner: \`Barnacle Bessie\`, ownerImg: \`BarnacleBessie.png\`, mapImg: \`TheLighthouseMapLocation.png\`, shopImg: \`TheLighthouse.png\`, tasks: [{ name: \`Oh, Barnacles!\`, type: \`Mainline Task\`, wikiUrl: \`https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Oh,_Barnacles!\`, steps: [{ text: \`Visit Flippy at Toon Hall in Toontown Central (178 XP, 7 JBS)\` }, { text: \`Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (178 XP, 7 JBS)\` }, { text: \`Visit River at Toon HQ (178 XP, 7 JBS)\` }, { text: \`Visit Wade at Toon HQ (178 XP, 7 JBS)\` }], reward: \`178 XP - 7 JBS per step\` }, TASK_IMPORTANT, TASK_UNITE_1, TASK_CHARTING, TASK_I_CAN_SEE, TASK_CAPTAIN, { name: \`The Office\`, type: \`Mainline Task\`, wikiUrl: \`https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#The_Office\`, steps: [{ text: \`Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (107 XP, 4 JBS)\`, sub: \`Defeat the Land Acquisition Architect on Anchor Avenue\` }, { text: \`Return to Barnacle Bessie at The Lighthouse on Lighthouse Lane (1605 XP, 54 JBS, Ye Olde Toontowne Profile Background)\` }], reward: \`1605 XP - 54 JBS - Ye Olde Toontowne Profile Background\` }] },
    { name: \`This Transom Man Custom-Tailored Suits\`, owner: \`Porter Hole\`, ownerImg: \`PorterHole.png\`, mapImg: \`ThisTransomManMapLocation.png\`, shopImg: \`ThisTransomMan.png\`, tasks: [] },
    { name: \`Docker's Diner\`, owner: \`Dinah Docker\`, ownerImg: \`DinahDocker.png\`, mapImg: \`Docker'sDinerMapLocation.png\`, shopImg: \`Docker'sDiner.png\`, tasks: [] },
    { name: \`Seven Seas Cafe\`, owner: \`Ted Calm\`, ownerImg: \`TedCalm.png\`, mapImg: \`SevenSeasCafeMapLocation.png\`, shopImg: \`SevenSeasCafe.png\`, tasks: [] },
    { name: \`Hook, Line, and Sinker Prank Shop\`, owner: \`Whoopie Cushion\`, ownerImg: \`WhoopieCushion.png\`, mapImg: \`HookLineAndSinkerPrankShopMapLocation.png\`, shopImg: \`HookLineAndSinkerPrankShop.png\`, tasks: [] },
    { name: \`King Neptoon's Cannery\`, owner: \`Stinky Ned\`, ownerImg: \`StinkyNed.png\`, mapImg: \`KingNeptoon'sCanneryMapLocation.png\`, shopImg: \`KingNeptoon'sCannery.png\`, tasks: [] },
    { name: \`Dog Paddles\`, owner: \`Ned Setter\`, ownerImg: \`NedSetter.png\`, mapImg: \`DogPaddlesMapLocation.png\`, shopImg: \`DogPaddles.png\`, tasks: [] },
    { name: \`The Clam Bake Diner\`, owner: \`Pearl Diver\`, ownerImg: \`PearlDiver.png\`, mapImg: \`TheClamBakeDinerMapLocation.png\`, shopImg: \`TheClamBakeDiner.png\`, tasks: [] },
    { name: \`Wholly Mackerel! Fish Market\`, owner: \`Felicia Chips\`, ownerImg: \`FeliciaChips.png\`, mapImg: \`WhollyMackerelMapLocation.png\`, shopImg: \`WhollyMackerel.png\`, tasks: [] },
    { name: \`Claggart's Clever Clovis Closet\`, owner: \`Claggart\`, ownerImg: \`Claggart.png\`, mapImg: \`Claggart'sCleverClovisClosetMapLocation.png\`, shopImg: \`Claggart'sCleverClovisCloset.png\`, tasks: [] },
    { name: \`Rudderly Ridiculous!\`, owner: \`Rudy Rudder\`, ownerImg: \`RudyRudder.png\`, mapImg: \`RudderlyRidiculousMapLocation.png\`, shopImg: \`RudderlyRidiculous.png\`, tasks: [] },
    { name: \`Alice's Ballast Palace\`, owner: \`Alice\`, ownerImg: \`Alice.png\`, mapImg: \`Alice'sBallastPalaceMapLocation.png\`, shopImg: \`Alice'sBallastPalace.png\`, tasks: [] },
  ],
};
STREET_SHOPS[\`BB|Lighthouse Lane\`] = BB_LIGHTHOUSE;
`;
