export interface CollectionItem { name: string; type: string; how: string; }
export interface CollectionSection { name: string; icon: string; color: string; accent: string; items: CollectionItem[]; }
const I = (name: string, type: string, how: string): CollectionItem => ({ name, type, how });

export const COLLECTIONS: CollectionSection[] = [
  {
    name: 'Start of Game', icon: '🎮', color: '#1a1a2a', accent: '#8888ff',
    items: [
      I('Default','Background','Available at start of game'),
      I('Default Dark Blue','Background','Available at start of game'),
      I('Default Blue','Background','Available at start of game'),
      I('Default Blue','Nameplate','Available at start of game'),
      I('Default Green','Nameplate','Available at start of game'),
      I('Default Orange','Nameplate','Available at start of game'),
      I('Default Purple','Nameplate','Available at start of game'),
      I('Default Red','Nameplate','Available at start of game'),
      I('Default Yellow','Nameplate','Available at start of game'),
      I('Default Dark Green','Nameplate','Available at start of game'),
      I('Basic','Nametag','Available at start of game'),
      I('Plain','Nametag','Available at start of game'),
      I('Neutral','Profile Pose','Available at start of game'),
      I('Wave','Profile Pose','Available at start of game'),
      I('Sit','Profile Pose','Available at start of game'),
      I('Applause','Profile Pose','Available at start of game'),
    ],
  },
  {
    name: 'Toontown Central', icon: '🍦', color: '#5a2004', accent: '#d86b10',
    items: [
      I('Toontown Central','Background','Awarded for progressing to Toontown Central in the Taskline'),
      I('Toontown Central','Nameplate','Awarded for visiting Toontown Central'),
      I('Toontown Central Sky','Background','Awarded after completing the Give and Cake Kudos Rank-Up Task'),
      I('Congratulations','Nameplate','Awarded after completing the Give and Cake Kudos Rank-Up Task'),
      I('Duck Shuffler','Background','Awarded after defeating the Duck Shuffler'),
      I("Slippin'",'Nametag','Awarded for clicking the Banana in Toon Hall in Toontown Central'),
      I('You Did It','Nameplate','Awarded after completing the Give and Cake Kudos Rank-Up Task'),
      I('Green Duck Shuffler','Nameplate','Awarded after defeating the Duck Shuffler'),
      I('Red Duck Shuffler','Nameplate','Awarded after defeating the Duck Shuffler'),
      I('Zany','Cheesy Effect','Rewarded from the Monkey See Monkey Do sidetask'),
      I('Ice Cream','Nametag','Rank 8 on the Toontown Central Kudos Board'),
      I('Selfie','Profile Pose','Awarded after completing the task New Toony Tourist'),
      I('Become Duck','Profile Pose','Rank 5 on the Toontown Central Kudos Board'),
      I('Upset','Profile Pose','Awarded after defeating the Derrick Man'),
      I('Invisible','Cheesy Effect','Awarded after completing the task Cream-Be-Gone'),
    ],
  },
  {
    name: 'Barnacle Boatyard', icon: '⚓', color: '#5a1a05', accent: '#dc4a14',
    items: [
      I('Barnacle Boatyard','Background','Awarded for progressing to Barnacle Boatyard in the Taskline'),
      I('Barnacle Boatyard','Nameplate','Awarded for visiting Barnacle Boatyard'),
      I('Barnacle Boatyard Sky','Background','Awarded after completing the Silverware Sting Kudos Rank-Up Task'),
      I('On The Dock','Background','Awarded after completing the Silverware Sting Kudos Rank-Up Task'),
      I('Sandcastles','Nameplate','Awarded for riding the Boat in Barnacle Boatyard for 20 Laps'),
      I('Nautical','Nametag','Rewarded from the The Salty Spit-toon sidetask'),
      I('Boardwalk','Nametag','Rewarded from the Straight to Boardwalk sidetask'),
      I('Wonky','Nametag','Rewarded from the First Mate Makeover sidetask'),
      I('Pirate','Nametag','Rank 8 on the Barnacle Boatyard Kudos Board'),
      I('Diving','Profile Pose','Awarded after completing the task Swimming Kiwi'),
      I('Treasure','Profile Pose','Rank 5 on the Barnacle Boatyard Kudos Board'),
      I("I'm Outta Here!",'Profile Pose','Awarded after defeating the Land Acquisition Architect'),
      I('Big Legs','Cheesy Effect','Awarded after completing the task The Salty Spit-toon'),
    ],
  },
  {
    name: 'Ye Olde Toontowne', icon: '👑', color: '#33205e', accent: '#9b70cc',
    items: [
      I('Ye Olde Toontowne','Background','Awarded for progressing to Ye Olde Toontowne in the Taskline'),
      I('Ye Olde Toontowne','Nameplate','Awarded for visiting Ye Olde Toontowne'),
      I('Ye Olde Toontowne Sky','Background','Awarded after completing the Doodragon Festival Kudos Rank-Up Task'),
      I('Hearty Feast','Background','Awarded after completing the Doodragon Festival Kudos Rank-Up Task'),
      I('Ye Olde Toontowne Sky','Nameplate','Awarded for touching the Well in Ye Olde Toontowne'),
      I('Hearty Feast','Nameplate','Awarded after completing the Doodragon Festival Kudos Rank-Up Task'),
      I('Poetic','Nametag','Rewarded from the Midlife Crisis sidetask'),
      I('Medieval','Nametag','Rank 8 on the Ye Olde Toontowne Kudos Board'),
      I('Casting','Profile Pose','Awarded after completing the task The Golden Penny'),
      I('At The Gate','Profile Pose','Rank 5 on the Ye Olde Toontowne Kudos Board'),
      I('To Be Or Not To Be?','Profile Pose','Awarded after defeating the Public Relations Representative'),
      I('Transparent','Cheesy Effect','Awarded after completing the task Midlife Crisis'),
      I('Small Head','Cheesy Effect','Awarded after completing the task Not-So-Tall Tales'),
    ],
  },
  {
    name: 'Daffodil Gardens', icon: '🌸', color: '#1f3200', accent: '#9bd31a',
    items: [
      I('Daffodil Gardens','Background','Awarded for progressing to Daffodil Gardens in the Taskline'),
      I('Daffodil Gardens','Nameplate','Awarded for visiting Daffodil Gardens'),
      I('Daffodil Gardens Sky','Background','Awarded after completing the Groovy Paintings Kudos Rank-Up Task'),
      I('Tranquil Fountain','Background','Awarded for raising the Flower of Doom with 5 Toons in Daffodil Gardens'),
      I('Gardening','Nameplate','Awarded after completing the Groovy Paintings Kudos Rank-Up Task'),
      I('Silly','Nametag','Rewarded from the Not-So-Instant Film sidetask'),
      I('Calligraphy','Nametag','Rank 8 on the Daffodil Gardens Kudos Board'),
      I('Running','Profile Pose','Awarded after completing the task Wedding Planner'),
      I('Elegance','Profile Pose','Rank 5 on the Daffodil Gardens Kudos Board'),
      I('Flat Portrait','Cheesy Effect','Awarded after completing the task Not-So-Instant Film'),
      I('Green Toon','Cheesy Effect','Awarded after completing the task Greener Thumbs'),
    ],
  },
  {
    name: 'Mezzo Melodyland', icon: '🎵', color: '#3a1545', accent: '#bf62cb',
    items: [
      I('Mezzo Melodyland','Background','Awarded for progressing to Mezzo Melodyland in the Taskline'),
      I('Mezzo Melodyland','Nameplate','Awarded for visiting Mezzo Melodyland'),
      I('Mezzo Melodyland Sky','Background','Awarded after completing the Rocked Out Kudos Rank-Up Task'),
      I('Rock Concert','Background','Awarded for jumping on a drum in Mezzo Melodyland ten times in a row'),
      I("Fires n' Flames",'Nameplate','Awarded after completing the Rocked Out Kudos Rank-Up Task'),
      I('Whimsical','Nametag','Rewarded from the Flat Notes & Profiles sidetask'),
      I('Fancy','Nametag','Rewarded from the Got You Covered! sidetask'),
      I('Playful','Nametag','Rank 8 on the Mezzo Melodyland Kudos Board'),
      I('Presenting...','Profile Pose','Awarded after completing the task Piano Player'),
      I('Pick Up The Phone','Profile Pose','Rank 5 on the Mezzo Melodyland Kudos Board'),
      I('Flat Profile','Cheesy Effect','Awarded after completing the task Flat Notes & Profiles'),
      I('Big Head','Cheesy Effect',"Awarded after completing the task What's That Sound?"),
    ],
  },
  {
    name: 'The Brrrgh', icon: '❄️', color: '#00263a', accent: '#29b2dc',
    items: [
      I('The Brrrgh','Background','Awarded for progressing to The Brrrgh in the Taskline'),
      I('The Brrrgh','Nameplate','Awarded for visiting The Brrrgh'),
      I('The Brrrgh Sky','Background',"Awarded after completing the Paula's Parent Present Party Kudos Rank-Up Task"),
      I('Doodlesledding','Background','Awarded for touching all 5 Ice Blocks in The Brrrgh Playground'),
      I('Snowball Fight','Background','Awarded for making Steve the Snowman grow to his largest size'),
      I('Scarf','Nameplate',"Awarded after completing the Paula's Parent Present Party Kudos Rank-Up Task"),
      I('Shivering','Nametag','Rewarded from the Stevey The Snowman! sidetask'),
      I('Comical','Nametag','Rank 8 on the The Brrrgh Kudos Board'),
      I('Surprised','Profile Pose','Awarded after completing the task Gathering Warmth'),
      I('Fire Hands','Profile Pose','Rank 5 on the The Brrrgh Kudos Board'),
      I('No Color','Cheesy Effect','Awarded after completing the task Snow Pale'),
      I('Wireframe','Cheesy Effect','Awarded after completing the task Stevey The Snowman!'),
      I('Big White Toon','Cheesy Effect','Awarded after completing the task Hybernation Invitation'),
    ],
  },
  {
    name: 'Acorn Acres', icon: '🌰', color: '#003a18', accent: '#20cf69',
    items: [
      I('Acorn Acres','Background','Awarded for progressing to Acorn Acres in the Taskline'),
      I('Acorn Acres','Nameplate','Awarded for visiting Acorn Acres'),
      I('Acorn Acres Sky','Background','Awarded from completing the Perilous Party Preparations Kudos Rank-Up Task'),
      I('Light Show','Background','Awarded from completing the Perilous Party Preparations Kudos Rank-Up Task'),
      I('Light Show','Nameplate','Awarded from completing the Perilous Party Preparations Kudos Rank-Up Task'),
      I('Snowball Fight','Background','Awarded for swimming from downriver to the waterfall in Acorn Acres'),
      I('Practical','Nametag','Rewarded from the When Nature Calls sidetask'),
      I('Arrogant','Nametag','Rank 8 on the Acorn Acres Kudos Board'),
      I('Greened','Profile Pose','Awarded after completing the task Survival Kit Builder'),
      I('Rolled','Profile Pose','Rank 5 on the Acorn Acres Kudos Board'),
      I('Small Legs','Cheesy Effect','Awarded after completing the task Down We Go'),
      I('Big Toon','Cheesy Effect','Awarded after completing the task Training Season'),
    ],
  },
  {
    name: 'Drowsy Dreamland', icon: '💤', color: '#1a1060', accent: '#7b68ee',
    items: [
      I('Drowsy Dreamland','Background','Awarded for progressing to Drowsy Dreamland in the Taskline'),
      I('Drowsy Dreamland','Nameplate','Awarded for visiting Drowsy Dreamland'),
      I('Drowsy Dreamland Sky','Background','Awarded from completing the Candy Conundrum Kudos Rank-Up Task'),
      I('Sweet','Background','Awarded from completing the Candy Conundrum Kudos Rank-Up Task'),
      I('Sweet','Nameplate',"Awarded for saying \"I'm Sleepy\" in Drowsy Dreamland 20 times"),
      I('Action','Nametag','Rewarded from the Short Story sidetask'),
      I('Western','Nametag',"Rewarded from the The Ol' West sidetask"),
      I('Cinema','Nametag','Rank 8 on the Drowsy Dreamland Kudos Board'),
      I('Yawning','Profile Pose','Awarded after completing the task Camera Repair'),
      I('Naptime','Profile Pose','Rank 5 on the Drowsy Dreamland Kudos Board'),
      I('Small Toon','Cheesy Effect','Awarded after completing the task Short Story'),
    ],
  },
  {
    name: 'Minigames', icon: '🎡', color: '#1a2a1a', accent: '#60d060',
    items: [
      I('The Trolley','Background','Awarded for completing the Trolley for the first time'),
      I('Under the Sea','Background','Awarded rarely when Fishing'),
      I('Golfing','Background','Awarded for completing a round of Golf for the first time'),
      I('Racing','Background','Awarded for completing a Race for the first time'),
      I('Chequered Flag','Nameplate','Randomly dropped at a low chance after completing a Trolley Game'),
      I('Aquarium','Nameplate','Awarded by securing 3 Treasure Chests in Treasure Dive on the Trolley'),
      I('Golfing','Nameplate','Randomly dropped at a low chance after completing a course of Golf'),
      I('Racing','Nameplate','Randomly dropped at a low chance after a Race at Roaster Raceway'),
    ],
  },
  {
    name: 'G.U.M.B.A.L.L. Machine', icon: '🔮', color: '#1a0a2a', accent: '#c060ff',
    items: [
      I('Outback','Background','Purchasable at the G.U.M.B.A.L.L. Machine for 600 Gumballs'),
      I('Outback','Nameplate','Purchasable at the G.U.M.B.A.L.L. Machine for 700 Gumballs'),
      I('Stars','Background','Purchasable at the G.U.M.B.A.L.L. Machine for 800 Gumballs'),
    ],
  },
  {
    name: 'Promotions & Directives', icon: '⚙️', color: '#1a1a0a', accent: '#c0c040',
    items: [
      I('R.I.D.D.L.E','Background','Awarded after completing the Crossword Crisis Directive (Pettifogger to Level 7)'),
      I('Paint Mixer','Background','Overclocked Find the Foreman (April Toons 2022 / MAYpril Toons 2023)'),
      I('Sellbot HQ','Background','Awarded for reaching the Tier 8 Sellbot Suit'),
      I('Bossbot HQ','Background','Awarded for reaching the Tier 8 Bossbot Suit'),
      I('Lawbot HQ','Background','Awarded for reaching the Tier 8 Lawbot Suit'),
      I('Cashbot HQ','Background','Awarded for reaching the Tier 8 Cashbot Suit'),
      I('Turning It Up To 11','Nameplate','Awarded for maxing out the Sound Bar during a C.L.O. Battle'),
    ],
  },
  {
    name: 'Codes & Events', icon: '🎟️', color: '#2a1a0a', accent: '#f0a030',
    items: [
      I('Pacesetter & Firestarter','Background','Awarded after using the code "FIRESETTER"'),
      I('Cybertoon','Background','Awarded after using the code "CYBERTOONEXPLORER"'),
      I('Game Show','Background','Defeating the High Roller 11 times'),
      I('Pacesetter & Firestarter','Nameplate','Awarded after using the code "FIRESETTER"'),
      I('Cybertoon','Nameplate','Awarded after using the code "CYBERTOONEXPLORER"'),
      I('Game Show','Nameplate','Defeating the High Roller 13 times'),
      I('Birthday Bash','Background',"Rewarded during Corporate Clash's 6th Anniversary event"),
    ],
  },
  {
    name: 'Halloween', icon: '🎃', color: '#2a1000', accent: '#ff6820',
    items: [
      I('Halloween Night','Background','Available from Reid Stock during Halloween/April Toons for 100 Bones'),
      I('Halloween Town','Background','Available during Halloween/April Toons for 35 of each Shkrafting Material'),
      I('The Golden Corridor','Background','Available during Halloween/April Toons for 35 of each Shkrafting Material'),
      I('Lazy Bones','Nameplate','Available from Reid Stock during Halloween/April Toons for 100 Bones'),
      I('Spooky Bat','Nameplate','Available during Halloween/April Toons for 35 of each Shkrafting Material'),
      I('Halloween Candy (Blue)','Nameplate','Available from Reid Stock for 100 Bones (Halloween/April Toons)'),
      I('Halloween Candy (Green)','Nameplate','Available during Halloween/April Toons for 20 of each Shkrafting Material'),
      I('Halloween Candy (Purple)','Nameplate','Available during Halloween/April Toons for 20 of each Shkrafting Material'),
      I('Halloween Candy (Red)','Nameplate','Available during Halloween/April Toons for 20 of each Shkrafting Material'),
      I('Spooky','Nametag',"Available in Elphabat's shop for 40 of every Shkrafting material"),
      I('Zombie','Nametag','N/A'),
      I('Spooky','Profile Pose','Available during Halloween/April Toons for 35 of each Shkrafting Material'),
      I('Sinking','Cheesy Effect','Trick-or-Treating (2023-2025)'),
      I('Yarr & Harr','Cheesy Effect','Shkrafting Shop (Lynn Decisive)'),
      I('Scapegourd','Cheesy Effect','Shkrafting Shop (Lynn Decisive)'),
      I('Spirit','Cheesy Effect','Shkrafting Shop (Lynn Decisive)'),
      I('Stomped','Cheesy Effect','Shkrafting Shop (Lynn Decisive)'),
      I('No Arms','Cheesy Effect','Available during Halloween/April Toons for 35 of each Shkrafting Material'),
    ],
  },
  {
    name: 'Christmas / Toonsmas', icon: '🎄', color: '#0a2010', accent: '#40d070',
    items: [
      I('Winter Cabin','Background','Earned as a drop from Toonseltown Present Thief Game (Toonsmas Update)'),
      I('Fireplace','Background','Awarded after completing the Stocking Stuffers Toontask (Toonmas Update)'),
      I('Night Lights','Background','Earned as a drop from Toonseltown Present Thief Game (Toonsmas Event)'),
      I('Wrapping','Nameplate','Awarded after completing the Presidential Appreciation Toontask (Toonmas Event)'),
      I('Tinsel','Nameplate','Earned as a drop from Toonseltown Present Thief Game (Toonsmas Event)'),
      I('Snowman Head','Cheesy Effect','Caroling (Toonsmas)'),
    ],
  },
  {
    name: 'Unobtainable', icon: '🔒', color: '#1a1a1a', accent: '#888888',
    items: [
      I('Sky Clan','Background','Awarded for completing a Sky Clan task during the Mayday event'),
      I('Break the Law!','Background','Awarded for getting 4 Pink Slip Pieces during Break The Law'),
      I('New Years 2019 Fireworks','Background','Awarded during the 2019 New Years Event'),
      I('New Years 2020 Fireworks','Background','Awarded during the 2020 New Years Event'),
      I('Easter 2020','Background','Awarded after using the Easter 2020 code "eggcellent"'),
      I("Valentine's 2020",'Background',"Awarded after using the Valentoon's 2020 code \"lovestruck\""),
      I('Artificial Progeny','Background','Awarded for defeating the Witness Stand-In during Break The Law'),
      I('Fireworks Show','Background','Awarded after using the 2020 Summer code "fireworks"'),
      I('Dreams Come True','Background','Awarded for completing the Sky Clan ARG during the Mayday event'),
      I("Atticus' Desk",'Background','Awarded for defeating the Witness Stand-In during Break The Law'),
      I('Pink Slip','Background','Awarded for finding 5 Pink Slip Pieces during Break The Law'),
      I('Thanksgiving 2019','Nameplate','Awarded for attending the 2019 Thanksgiving Event'),
      I('New Years Fireworks 2019','Nameplate','Awarded for attending the 2019 New Years Event'),
      I('New Years Fireworks 2020','Nameplate','Awarded for attending the 2020 New Years Event'),
      I('Easter 2020','Nameplate','Awarded for using the 2020 Easter Event code "eggcellent"'),
      I('Candy','Nameplate','Awarded after using the 2020 Summer code "fireworks"'),
      I('Prepare for Launch','Nameplate','Awarded after using the 2020 Summer code "fireworks"'),
      I('Pink Slip','Nameplate','Awarded for completing a Sky Clan task during the Mayday event'),
      I('6 Pink Slip Collectibles','Cheesy Effect','Awarded for getting 6 Pink Slip Pieces during Break The Law'),
    ],
  },
];
export const COLLECTION_TYPES = ['Background','Nameplate','Nametag','Profile Pose','Cheesy Effect'] as const;
export type CollectionType = typeof COLLECTION_TYPES[number];
