import type { QuestPlayground } from './data-quests-types';
import { H, Q, S, KL, KH } from './data-quests-types';
export const BB: QuestPlayground = {
  name: 'Barnacle Boatyard', icon: '⭐', color: '#5a1a05', accent: '#dc4a14',
  mainColor: '#ff6050', kudosHighColor: '#40d8ff',
  rows: [
    H('Main Storyline'),
    Q('Oh, Barnacles!'), Q('Butter Flippers'), Q("Someone's Been Drinking Saltwater …"),
    Q('Red Rover, Red Rover'), Q('First Day of School!'), Q('Big Binnacle Bash'),
    Q('Meet Misty'), Q('Contacting Live Support'), Q("Baby's First Steps"),
    Q('The Important Stuff'), Q('Unite the Buccaneers!'), Q('Charting Smart Charts'),
    Q('I Can See Clearly Now …'), Q('A Captain For Hire'), Q('The Weakest Link'),
    Q('The Office',"⭐ I'm Outta Here! – Pose | ⭐ Ye Olde Toontowne – Background"),
    H('Sidetasks'),
    S('Pilfering Propellers','⭐ Teleport Access','Anchor Avenue (Island, You Land! Airplanes)'),
    S('Dressing Sea-Lads and Lasses','Sailor Outfit','Buccaneer Blvd (Salmon Chanted Evening Formal Wear)'),
    S('The Salty Spit-toon','⭐ Nautical – Nametag | ⭐ Big Legs – Cheesy Effect','Anchor Avenue (The Salty Spit-toon)'),
    S('Straight to Boardwalk','⭐ Boardwalk – Nametag',"Lighthouse Lane (What's Up, Dock?)"),
    S('First Mate Makeover','⭐ Wonky – Nametag',"Buccaneer Blvd (Blackbeard's Beauty Parlor)"),
    S('Swimming Kiwi','⭐ Diving – Profile Pose','Tumbies (Playground)'),
    H('Kudos Rank-Up Quests'),
    KL('1→2  Are You Squidding Me?','+1 BB Gag Exp. Multiplier'),
    KL('2→3  Sandcastle Savings','15% Cheaper BB Gags | +1 BB G.U.M.B.A.L.L. Booster'),
    KL('3→4  Silverware Sting','⭐ On The Dock – Background | ⭐ Sandcastles – Nameplate'),
    KL('4→5  Salt, Pepper, Paprika','⭐ Treasure – Profile Pose'),
    KL('5→6  Stopping the Scuttlebutt','30% Cheaper Gags in BB | +1 BB G.U.M.B.A.L.L. Booster'),
    KH('6→7  Huge Oppor-tuna-ty','+2 BB Gag XP Multiplier'),
    KH('7→8  7th Layer Wrapping Paper','⭐ Pirate – Nametag Font'),
    KH('8→9  Barbarian Barbara','50% Cheaper Gags in BB | +1 BB GUMBALL Booster'),
    KH('9→10  A Misty Mystery','+1 Max Laff'),
    KH('10+  +25 Gumballs'),
  ],
};
