import type { QuestPlayground } from './data-quests-types';
import { H, Q, S, KL, KH } from './data-quests-types';
export const DG: QuestPlayground = {
  name: 'Daffodil Gardens', icon: '🌸', color: '#1f3200', accent: '#9bd31a',
  mainColor: '#7ec820', kudosHighColor: '#e06090',
  rows: [
    H('Main Storyline'),
    Q('Trained and Ready'), Q('The Zucchini'), Q('The Rose'), Q('Wilted Sunflowers'),
    Q('Where the Grass Grows …'), Q('Ketchum?'), Q('Bert.'), Q('Never Out Of Style'),
    Q("Petunia's Place"), Q('A Boxing Lesson To Forget'), Q('Not So Vine …'),
    Q('Hard to Reed'), Q("Reed's Needs"), Q("Rose's Words"), Q('Stretch and Squash'),
    Q('Lima … Seen?'), Q('Enter The Big Scary Place'), Q('Secret Agent Toon'),
    Q('The Great Factory Haul'), Q('Whats Behind Door #1?'), Q('The Lost Training'),
    Q('The Great Market Crash','⭐ Mezzo Melodyland – Profile Background'),
    H('Sidetasks'),
    S('The Secret Weapon','⭐ Teleport Access','Daisy Drive (Trellis the Truth! Private Investigators)'),
    S('Garden Tending','Gardening Outfit',"Daisy Drive (Tracy's Trowels & Tools)"),
    S('The Magical Fruit','Samba Hat','Daisy Drive (The Musical Fruit Diner)'),
    S('Not-So-Instant Film','⭐ Silly – Nametag | ⭐ Flat Portrait – Cheesy Effect',"Daisy Drive (Photo Cynthia's Camera Store)"),
    S('Greener Thumbs','⭐ Green Toon – Cheesy Effect','Tulip Terrace (Green Bean Jeans)'),
    S('Wedding Planner','⭐ Running – Profile Pose','Tumbies (Playground)'),
    H('Kudos Rank-Up Quests'),
    KL('1→2  Forecast Fallacy','+1 DC Gag XP Multiplier'),
    KL('2→3  Ant Stop Me Now','15% Cheaper Gags in DC | +1 DC CUMBALL Booster'),
    KL('3→4  Groovy Paintings','⭐ Tranquil Fountain – Background | ⭐ Gardening – Nameplate'),
    KL('4→5  Ringing the Right Bell','⭐ Elegance – Profile Pose'),
    KL('5→6  Floral Fisticuffs','30% Cheaper Gags in DG | +1 DG CUMBALL Booster'),
    KH('6→7  Top-Notch Tuft Toons','+2 DG Gag XP Multiplier'),
    KH('7→8  Quaking and Breaking','⭐ Calligraphy – Nametag Font'),
    KH('8→9  Miss-ting Mail','50% Cheaper Gags in DG | +1 DG CUMBALL Booster'),
    KH('9→10  The Couch Slouch','+1 Max Laff'),
    KH('10+  +35 Gumballs'),
  ],
};
