import type { QuestPlayground } from './data-quests-types';
import { H, Q, S, KL, KH } from './data-quests-types';
export const AA: QuestPlayground = {
  name: 'Acorn Acres', icon: '🌰', color: '#00451e', accent: '#20cf69',
  rows: [
    H('Main Storyline'),
    Q("Flippy's Message"), Q('First Draft Pick'), Q('Enlisting In The Army'),
    Q('Its a Hard Knock Life'), Q('First Impressions'), Q('Or Your Money Back'),
    Q('Stir Crazy'), Q('Crazy Construction Time'), Q('Help The Needy'),
    Q('Silence Is Golden'), Q('The Best Investments Is …'), Q('All Rise'),
    Q('Surprise Supplies Check!'), Q('A Real Banquet Breaker'), Q('Suit Up.'),
    Q("It's Time.",'⭐ Drowsy Dreamland – Profile Background'),
    H('Sidetasks'),
    S('FORE!!','⭐ Teleport Access','Walnut Way (Golf Balls Fore Sale)'),
    S('Suit Up, Ranger','Ranger Outfit','Almond Avenue (Hiking, Biking, and Sightseeing)'),
    S('Down We Go','⭐ Small Legs – Cheesy Effect','Almond Avenue (I\'m Stumped! Problem Solvers)'),
    S('Training Season','⭐ Big Toon – Cheesy Effect','Almond Avenue (Hut Hut Hike)'),
    S('When Nature Calls','⭐ Practical – Nametag','Legume Lane (Nature Calls! Toilet-trees)'),
    S('Survival Kit Builder','⭐ Greened – Profile Pose','Tumbies (Playground)'),
    H('Kudos Rank-Up Quests'),
    KL('1→2  Beanevolent Mr. Bean','+1 AA Gag XP Multiplier'),
    KL('2→3  Easy Elementary Earnings','15% Cheaper Gags in AA | +1 AA G.U.M.B.A.L.L. Machine Booster'),
    KL('3→4  Perilous Party Preparations','⭐ Light Show – Profile Background | ⭐ Light Show – Nameplate'),
    KL('4→5  The Side of Caution','⭐ Rolled – Profile Pose'),
    KL('5→6  Dendrochrojewelry','30% Cheaper Gags in AA | +1 AA G.U.M.B.A.L.L. Machine Booster'),
    KH("6→7  Pet A'tree'ciation",'+2 AA Gag XP Multiplier'),
    KH("7→8  Nathan's Nutrition",'⭐ Arrogant – Nametag Font'),
    KH('8→9  Nuthing to Sneeze At','50% Cheaper Gags in AA | +1 AA G.U.M.B.A.L.L. Machine Booster'),
    KH('9→10  I Saw What I Chain-Saw','+1 Max Laff'),
    KH('10+  +60 Gumballs'),
  ],
};
export const DDL: QuestPlayground = {
  name: 'Drowsy Dreamland', icon: '💤', color: '#1a1060', accent: '#7b68ee',
  rows: [
    H('Main Storyline'),
    Q('The Star of The Show'), Q('But Wait, There\'s More?'), Q('The DiMML Doctor'),
    Q('The Rumbling in Drowsy Dreamland'), Q('Fitting Into The Crowd'), Q('Wakey, Wakey!'),
    Q('Eggs and Bakey!'), Q('Just a Hunch …'), Q('Look What I Found!'), Q('Back To It!'),
    Q('Zee Exterminatah'), Q('Bahama Pajama Drama'), Q("Dozin'"), Q('Another Hunch …'),
    Q('Is it the Golden Ticket?'), Q("I've Been Working In The Dreamland …"),
    Q('The Not-So-Tucked-Inn'), Q('Bring Us A Dream'), Q("Snoozin'"),
    Q("It's Time To Pay Up"), Q('Lawfully Strange'), Q('Three Pieces'),
    Q('All-Seeing Eye Doctors'), Q('Yes. Hand Development Affairs.'),
    Q('Not-So-Secret Secret Agent'), Q('Gathering Intel'), Q('Delivering Intel'),
    Q('LORD LOWDEN CLEAR, HELP !!!'), Q('Put Me In, Coach.'),
    Q('The Final Battle. For Now.'),
    Q('The Day Is Saved!','⭐ Resistance Salute – Profile Pose | Gold Medal Shirt'),
    H('Sidetasks'),
    S('Alternative Transportation','⭐ Teleport Access','Pajama Place (Fly By Night Travel Agency)'),
    S('MerchandiZzzing','ZZZ Outfit','Pajama Place (House of Zzzzzs)'),
    S('Short Story','⭐ Action – Nametag | ⭐ Small Toon – Cheesy Effect','Lullaby Lane (Bed Time Stories)'),
    S("The Ol' West",'⭐ Western – Nametag','Pajama Place (Sleepless in the Saddle All Night Pony Rides)'),
    S('Camera Repair','⭐ Yawning – Profile Pose','Tumbies (Playground)'),
    H('Kudos Rank-Up Quests'),
    KL("1→2  Professor Problem's Peril",'+1 DDL Gag XP Multiplier'),
    KL('2→3  Quiet Hours','15% Cheaper Gags in DDL | +1 DDL G.U.M.B.A.L.L. Machine Booster'),
    KL('3→4  Candy Conundrum','⭐ Sweet – Profile Background | ⭐ Sweet – Nameplate'),
    KL('4→5  Make Your Bed And Lie In It','⭐ Naptime – Profile Pose'),
    KL("5→6  What Night is It?",'30% Cheaper Gags in DDL | +1 DDL G.U.M.B.A.L.L. Machine Booster'),
    KH('6→7  No Time for Beauty Sleep','+2 DDL Gag XP Multiplier'),
    KH('7→8  Doze Were Mine!','⭐ Cinema – Nametag Font'),
    KH('8→9  So Easy, You Could Do It In Your Sleep!','50% Cheaper Gags in DDL | +1 DDL G.U.M.B.A.L.L. Machine Booster'),
    KH('9→10  Give it a Rest!','+1 Max Laff'),
    KH('10+  +70 Gumballs'),
  ],
};
