import type { QuestPlayground } from './data-quests-types';
import { H, Q, S, KL, KH } from './data-quests-types';
export const TB: QuestPlayground = {
  name: 'The Brrrgh', icon: '❄️', color: '#003a46', accent: '#29b2dc',
  rows: [
    H('Main Storyline'),
    Q('Rocky Joins The Battle'), Q('Ye Olde Wizard'), Q("Home's Where the Wizard's At?"),
    Q("Let's Retrace His Steps …"), Q('Oldman On Vacation?'), Q("Lil' Oldman! Lil' Oldman?"),
    Q("The Ol' Pub"), Q('The New Heater'), Q('The Magic Cap'), Q('That Smelly Smell'),
    Q('Prepping For The Winter?'), Q('FIND THE OLDMAN!'), Q('Mingle The Mingler'),
    Q('Destroy The Mingler'), Q('Really Destroy The Mingler'), Q('Please the Oldman'),
    Q('Look Good, Feel Good'), Q("Lil' Old Eyes"), Q('Sweet Buck Tooth'),
    Q('Blast From The Past!'), Q('Blast From The Past Pt. 2!'), Q('Helping Rocky'),
    Q('Nevermind, Helping Oldman'), Q('Is This Malpractice?'), Q('Cog Suit Architect'),
    Q('Just Another Day At The Office'), Q('Actually Help Rocky'), Q('Bumpy Plans'),
    Q('Topple The Law','⭐ Acorn Acres – Profile Background'),
    H('Sidetasks'),
    S('Ice Cold Warmth','⭐ Teleport Access','Sleet Street (Solar Powered Blankets)'),
    S('Bundle Up!','Snowflake Outfit','Polar Place (The Sweater Lodge)'),
    S('Snow Pale','⭐ No Color – Cheesy Effect',"Polar Place (Snowman's Land)"),
    S('Stevey The Snowman!','⭐ Shivering – Nametag | ⭐ Wireframe – Cheesy Effect','Steve (Playground)'),
    S('Hibernation Invitation','⭐ Big White Toon – Cheesy Effect','Polar Place (Hibernation Vacations)'),
    S('Gathering Warmth','⭐ Surprised – Profile Pose','Tumbies (Playground)'),
    H('Directives'),
    Q('Crossword Crisis (Pettifogger – Lvl 7)','Needlenose Promotion | ⭐ R.I.D.D.L.E. – Background'),
    Q('Needle Nonsense (Needlenose – Lvl 10)','Lawbot Overclocked Mode Laff Points (1/3)'),
    Q('Temperature Troubles (Conveyancer – Lvl 8)','Advocate Promotion | ⭐ Megaphone – Profile Pose'),
    Q('Docket Dilemma (Advocate – Lvl 15)','Lawbot Overclocked Mode Laff Point (2/3)'),
    Q('Memo Mishap (Styster – Lvl 12)','Barrister Promotion | ⭐ Crocheting – Nameplate'),
    Q('Fashion Fiasco (Barrister – Lvl 14)','Lawbot Overclocked Mode Laff Point (3/3) | Lawbot Suit Switching'),
    H('Kudos Rank-Up Quests'),
    KL('1→2  Tour De Brrrgh','+1 TB Gag XP Multiplier'),
    KL('2→3  Slippery Circuit!','15% Cheaper Gags in TB | +1 TB G.U.M.B.A.L.L. Booster'),
    KL("3→4  Paula's Parent Present Party",'⭐ Doodlesidding – Background | ⭐ Scarf – Nameplate'),
    KL("4→5  I'm Melting, I'm Melting!",'⭐ Fire Hands – Profile Pose'),
    KL('5→6  Snowglobal Emergency!','30% Cheaper Gags in TB | +1 TB G.U.M.B.A.L.L. Booster'),
    KH('6→7  Art for Auntie','+2 TB Gag XP Multiplier'),
    KH('7→8  Soup Served Sad','⭐ Comical – Nametag Font'),
    KH('8→9  Keeping Cool','50% Cheaper Gags in TB | +1 TB G.U.M.B.A.L.L. Booster'),
    KH('9→10  Joining The System','+1 Max Laff'),
    KH('10+  +50 Gumballs'),
  ],
};
