export interface CollectionItem { name: string; type: string; how: string; img?: string; }
export interface CollectionSection { name: string; icon: string; color: string; accent: string; items: CollectionItem[]; }
const I = (name: string, type: string, how: string, img?: string): CollectionItem => ({ name, type, how, img });
const BG = (f: string) => `/icons/collections/profile-backgrounds/${f}`;
const NP = (f: string) => `/icons/collections/profile-nameplates/${f}`;
const NT = (f: string) => `/icons/collections/profile-nametags/${f}`;
const PP = (f: string) => `/icons/collections/profile-poses/${f}`;
const CE = (f: string) => `/icons/collections/profile-cheesy-effects/${f}`;
const EM = (f: string) => `/icons/collections/emotions/${f}`;

export const COLLECTIONS: CollectionSection[] = [
  { name:"Start of Game", icon:"🎮", color:"#1a1a2a", accent:"#8888ff", items:[
    I("Default","Background","Available at start of game",BG('DefaultBackground.webp')),
    I("Default Blue","Nameplate","Available at start of game",NP('DefaultBlue.webp')),
    I("Default Dark Blue","Nameplate","Available at start of game",NP('DefaultDarkBlue.webp')),
    I("Default Dark Green","Nameplate","Available at start of game",NP('DefaultDarkGreen.webp')),
    I("Default Green","Nameplate","Available at start of game",NP('DefaultGreen.webp')),
    I("Default Light Blue","Nameplate","Available at start of game",NP('DefaultLightBlue.webp')),
    I("Default Orange","Nameplate","Available at start of game",NP('DefaultOrange.webp')),
    I("Default Purple","Nameplate","Available at start of game",NP('DefaultPurple.webp')),
    I("Default Red","Nameplate","Available at start of game",NP('DefaultRed.webp')),
    I("Default Yellow","Nameplate","Available at start of game",NP('DefaultYellow.webp')),
    I("Agree","Emotion","Available at start of game",EM('neutral/Agree.webp')),
    I("Angry","Emotion","Available at start of game",EM('negative/Angry.webp')),
    I("Applause","Profile Pose","Available at start of game",PP('Pose-applause.webp')),
    I("Basic","Nametag","Available at start of game",NT('Basic_Nametag.webp')),
    I("Disagree","Emotion","Available at start of game",EM('neutral/Disagree.webp')),
    I("Happy","Emotion","Available at start of game",EM('positive/Happy.webp')),
    I("Neutral","Profile Pose","Available at start of game",PP('Pose-neutral.webp')),
    I("Plain","Nametag","Available at start of game",NT('Plain_Nametag.webp')),
    I("Sit","Profile Pose","Available at start of game",PP('Pose-sit.webp')),
    I("Sleepy","Emotion","Available at start of game",EM('neutral/Sleepy.webp')),
    I("Wave","Profile Pose","Available at start of game",PP('Pose-wave.webp')),
    I("Wave","Emotion","Available at start of game",EM('neutral/Wave.webp')),
  ]},
  { name:"Activities", icon:"🎣", color:"#0a2a1a", accent:"#3dd68c", items:[
    I("Jellybeans","Background","Awarded for completing the Trolley for the first time",BG('JellybeansBackground.webp')),
    I("Aquarium","Background","Awarded rarely when Fishing",BG('AquariumBackground.webp')),
    I("Golfing","Background","Awarded for completing a round of Golf for the first time",BG('GolfingBackground.webp')),
    I("Chequered Flag","Background","Awarded for completing a Race for the first time",BG('FlagBackground.webp')),
    I("The Trolley","Nameplate","Randomly dropped at a low chance after completing a Trolley Game",NP('Trolley.webp')),
    I("Under the Sea","Nameplate","Awarded by securing 3 Treasure Chests in the Treasure Dive minigame on the Trolley",NP('UnderTheSea.webp')),
    I("Golfing","Nameplate","Randomly dropped at a low chance after completing a course of Golf",NP('GolfingNameplate.webp')),
    I("Racing","Nameplate","Randomly dropped at a low chance after completing a Race at Roaster Raceway",NP('RacingNameplate.webp')),
  ]},
  { name:"Misc.", icon:"🌟", color:"#2a1a00", accent:"#ffaa00", items:[
    I("Pacesetter & Firestarter","Background","Awarded after using the code \"FIRESETTER\"",BG('Pacesetter&FirestarterBackground.webp')),
    I("Game Show","Background","Defeating the High Roller 11 times",BG('GameShowBackground.webp')),
    I("Duck Shuffler","Background","Awarded after defeating the Duck Shuffler",BG('DuckShufflerBackground.webp')),

    I("Cybertoon","Background","Awarded after using the code \"CYBERTOONEXPLORER\"",BG('CybertoonBackground.webp')),
    I("Pacesetter & Firestarter","Nameplate","Awarded after using the code \"FIRESETTER\"",NP('Pacesetter&FirestarterNameplate.webp')),
    I("Game Show","Nameplate","Defeating the High Roller 13 times",NP('GameShowNameplate.webp')),
    I("Green Duck Shuffler","Nameplate","Awarded after defeating the Duck Shuffler",NP('GreenDuckShufflerNameplate.webp')),
    I("Red Duck Shuffler","Nameplate","Awarded after defeating the Duck Shuffler",NP('RedDuckShufflerNameplate.webp')),
    I("Cybertoon","Nameplate","Awarded after using the code \"CYBERTOONEXPLORER\"",NP('CybertoonNameplate.webp')),

    I("Birthday Bash","Nametag","Rewarded during Corporate Clash's 6th Anniversary event",NT('Birthday_Bash_Nametag.webp')),
    I("Sad","Emotion","Available at start of game",EM('negative/Sad.webp')),
  ]},
  { name:"Cattlelog Purchases", icon:"📦", color:"#1a1020", accent:"#aa88ff", items:[
    I("Applause","Emotion","Purchasable from the Cattlelog (Series 1, #5 / Series 3, #12)",EM('positive/Applause.webp')),
    I("Banana Peel","Emotion","Purchasable from the Cattlelog (Series 7, #10)",EM('negative/BananaPeel.webp')),
    I("Belly Flop","Emotion","Purchasable from the Cattlelog (Series 7, #5)",EM('negative/BellyFlop.webp')),
    I("Bored","Emotion","Purchasable from the Cattlelog (Series 2, #9)",EM('negative/Bored.webp')),
    I("Bow","Emotion","Purchasable from the Cattlelog (Series 1, #9 / Series 3, #8)",EM('positive/Bow.webp')),
    I("Confused","Emotion","Purchasable from the Cattlelog (Series 2, #1)",EM('negative/Confused.webp')),
    I("Cringe","Emotion","Purchasable from the Cattlelog (Series 4, #12)",EM('negative/Cringe.webp')),
    I("Cry","Emotion","Purchasable from the Cattlelog (Series 1, #1)\n\nNever goes to backorder",EM('negative/Cry.webp')),
    I("Dance","Emotion","Purchasable from the Cattlelog (Series 2, #5)",EM('positive/Dance.webp')),
    I("Delighted","Emotion","Purchasable from the Cattlelog (Series 1, #1)\n\nNever goes to backorder",EM('positive/Delighted.webp')),
    I("Furious","Emotion","Purchasable from the Cattlelog (Series 1, #1)\n\nNever goes to backorder",EM('negative/Furious.webp')),
    I("Laugh","Emotion","Purchasable from the Cattlelog (Series 1, #1)\n\nNever goes to backorder",EM('positive/Laugh.webp')),
    I("Shrug","Emotion","Purchasable from the Cattlelog (Series 1, #1 / Series 3, #1)",EM('neutral/Shrug.webp')),
    I("Surprise","Emotion","Purchasable from the Cattlelog (Series 1, #1)\n\nNever goes to backorder",EM('positive/Surprise.webp')),
    I("Taunt","Emotion","Purchasable from the Cattlelog (Series 1, #1)\n\nNever goes to backorder",EM('negative/Taunt.webp')),
    I("Think","Emotion","Purchasable from the Cattlelog (Series 4, #6)",EM('neutral/Think.webp')),
    I("Yawn","Emotion","Purchasable from the Cattlelog (Series 1, #1)\n\nNever goes to backorder",EM('neutral/Yawn.webp')),
  ]},
   { name:"G.U.M.B.A.L.L. Machine", icon:"🔮", color:"#2a102a", accent:"#cc44cc", items:[
    I("Outback","Background","Awarded for Participating in the Outback Event OR purchasable at the G.U.M.B.A.L.L. Machine for 600 Gumballs",BG('OutbackBackground.webp')),
    I("Outback","Nameplate","Awarded for completing the Outback Event OR purchasable at the G.U.M.B.A.L.L. Machine for 700 Gumballs",NP('OutbackNameplate.webp')),
    I("Stars","Nameplate","Awarded for earning the Silver Star after completing 50 Floors of Cog Buildings OR purchasable at the G.U.M.B.A.L.L. Machine for 800 Gumballs",NP('Stars.webp')),

    I("Banana","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 500 Gumballs",PP('Pose-Banana.webp')),
    I("Gag Button","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 500 Gumballs",PP('Pose-Gag_Button.webp')),
    I("Megaphone","Profile Pose","Awarded after completing the Temperature Troubles Directive",PP('Pose-megaphone.webp')),
    I("Pie Toss","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 500 Gumballs",PP('Pose-Pie_Toss.webp')),
    I("Seltzer Bottle","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 500 Gumballs",PP('Pose-Seltzer_Bottle.webp')),
    I("Silent Treatment","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 450 Gumballs",PP('Pose-Silent_Treatment.webp')),
  ]},
  { name:"Promotions & Directives", icon:"⚙️", color:"#1a1a1a", accent:"#aaaaaa", items:[
    I("R.I.D.D.L.E","Background","Awarded after completing the Crossword Crisis Directive",BG('Riddle.webp')),
    I("Paint Mixer","Background","Awarded after completing Overclocked Find the Foreman during the April Toons 2022 Event OR after defeating 5 Unstable Cogs in Overclocked Face the Family during the MAYpril Toons 2023 event",BG('PaintMixerBackground.webp')),
    I("Sellbot HQ","Background","Awarded for reaching the Tier 8 Sellbot Suit",BG('SellbotHQBackground.webp')),
    I("Sellbot Paint","Nameplate","Awarded after defeating 10 Unstable Cogs in Overclocked Face the Family during the MAYpril Toons 2023 event",NP('SellbotPaintNameplate.webp')),
    I("Cashbot HQ","Background","Awarded for reaching the Tier 8 Cashbot Suit",BG('CashbotHQBackground.webp')),
    I("Lawbot HQ","Background","Awarded for reaching the Tier 8 Lawbot Suit",BG('LawbotHQBackground.webp')),
    I("Bossbot HQ","Background","Awarded for reaching the Tier 8 Bossbot Suit",BG('BossbotHQBackground.webp')),
    I("Turning It Up To 11","Nameplate","Awarded for maxing out the Sound Bar during a Chief Legal Officer (C.L.O.) Battle",NP('Turningitupto11.webp')),
    I("Crocheting Lessons","Nameplate","Awarded for completing the Memo Mishap Directive",NP('Crochet.webp')),
    I("Resistance Salute","Profile Pose","Awarded after defeating The Directors",PP('Pose-Resistance_Salute.webp')),
  ]},
  { name:"Halloween", icon:"🎃", color:"#2a0e00", accent:"#ff6600", items:[
    I("The Golden Corridor","Background","Available for purchase from Reid Stock during Halloween and April Toons for 100 Bones",BG('TheGoldenCorridorBackground.webp')),
    I("Halloween Town","Background","Available for purchase from Reid Stock during Halloween and April Toons for 35 of each Shkrafting Material",BG('HalloweenTown.webp')),
    I("Halloween Night","Background","Available for purchase from Reid Stock during Halloween and April Toons for 35 of each Shkrafting Material",BG('HalloweenNightBackground.webp')),
    I("Lazy Bones","Nameplate","Available for purchase from Reid Stock during Halloween and April Toons for 100 Bones",NP('LazyBonesNameplate.webp')),
    I("Spooky Bat","Nameplate","Available for purchase from Reid Stock during Halloween and April Toons for 35 of each Shkrafting Material",NP('Spookybat.webp')),
    I("Halloween Night","Nameplate","Available for purchase from Reid Stock during Halloween and April Toons for 35 of each Shkrafting Material",NP('HalloweenNightNameplate.webp')),

    I("Halloween Candy (Blue)","Nameplate","Available for purchase from Reid Stock during Halloween and April Toons for 20 of each Shkrafting Material",NP('HalloweenCandyBlue.webp')),
    I("Halloween Candy (Green)","Nameplate","Available for purchase from Reid Stock during Halloween and April Toons for 20 of each Shkrafting Material",NP('HalloweenCandyGreen.webp')),
    I("Halloween Candy (Magenta)","Nameplate","Available for purchase from Reid Stock during Halloween and April Toons for 20 of each Shkrafting Material",NP('HalloweenCandyMagenta.webp')),
    I("Halloween Candy (Purple)","Nameplate","Available for purchase from Reid Stock during Halloween and April Toons for 20 of each Shkrafting Material",NP('HalloweenCandyPurple.webp')),
    I("Halloween Candy (Red)","Nameplate","Available for purchase from Reid Stock during Halloween and April Toons for 20 of each Shkrafting Material",NP('HalloweenCandyRed.webp')),

    I("No Arms","Cheesy Effect","Available during Halloween for 35 of each Shkrafting Material",CE('CE_noarms.webp')),
    I("Scapegourd","Cheesy Effect","Shkrafting Shop (Lynn Decisive)",CE('ScapegourdDouble.webp')),
    I("Sinking","Profile Pose","Available from Reid Stock during Halloween/April Toons for 35 of each Shkrafting Material",PP('Pose-sinking.webp')),
    I("Spirit","Cheesy Effect","Shkrafting Shop (Lynn Decisive)",CE('CE_spirit.webp')),
    I("Spooky","Nametag","Available in Elphabat's shop during Halloween events for 40 of every Shkrafting material",NT('Spooky_Nametag.webp')),
    I("Spooky","Profile Pose","Awarded after completing Halloween Organizer (Unobtainable)",PP('Pose-spooky.webp')),
    I("Stomped","Cheesy Effect","Shkrafting Shop (Lynn Decisive)",CE('CE_Stomped.webp')),

    I("Zombie","Profile Pose","Awarded after completing Spooky Storyteller (Unobtainable)",PP('Pose-zombie.webp')),
  ]},
  { name:"Toonsmas", icon:"🎄", color:"#0a2010", accent:"#40d070", items:[
    I("Winter Cabin","Background","Earned as a drop from the Toonseltown Present Thief Game during the Toonsmas Update",BG('WinterCabinBackground.webp')),
    I("Fireplace","Background","Awarded after completing the Stocking Stuffers Toontask during the Toonmas Update",BG('Fireplace.webp')),
    I("Night Lights","Nameplate","Earned as a drop from the Toonseltown Present Thief Game during the Toonsmas Event",NP('NightLights.webp')),
    I("Wrapping","Nameplate","Awarded after completing the Presidential Appreciation Toontask during the Toonmas Event",NP('Wrappingpaper.webp')),
    I("Tinsel","Nameplate","Earned as a drop from the Toonseltown Present Thief Game during the Toonsmas Event",NP('TinselNameplate.webp')),
    I("Snowman Head","Cheesy Effect","Caroling during Toonsmas",CE('SnowmanHeadDouble.webp')),

  ]},
  { name:"Toontown Central", icon:"🍦", color:"#5a2004", accent:"#d86b10", items:[
    I("Toontown Central","Background","Awarded for progressing to Toontown Central in the Taskline",BG('ToontownCentralBackground.webp')),
    I("Toontown Central Sky","Background","Awarded for visiting Toontown Central",BG('ToontownCentralSkyBackground.webp')),
    I("Congratulations","Background","Awarded after completing the Give and Cake Kudos Rank-Up Task",BG('CongratulationsBackground.webp')),
    I("Toontown Central","Nameplate","Awarded for saying \"Yeehaw!\" located in the \"Happy\" section of SpeedChat in front of the Horse statue in Toontown Central (placed next to the Library)",NP('Ttcnameplate.webp')),
    I("Slippin'","Nameplate","Awarded for clicking the Banana in Toon Hall in Toontown Central",NP('SlippinNameplate.webp')),
    I("You Did It","Nameplate","Awarded after completing the Give and Cake Kudos Rank-Up Task",NP('YouDidItNameplate.webp')),
    I("Become Duck","Profile Pose","Awarded after reaching Toontown Central Kudos Rank 5",PP('Pose-Become_Duck.webp')),
    I("Become Duck (Ducks Only)","Profile Pose","Awarded after reaching Toontown Central Kudos Rank 5",PP('BecomeDuckDuck.webp')),
    I("Ice Cream","Nametag","Rewarded for completing the Double Coil and Trouble Rank-Up Task (Kudos Rank 8, Toontown Central)",NT('Ice_Cream_Nametag.webp')),
    I("Invisible","Cheesy Effect","Awarded from the Cream-Be-Gone sidetask in Toontown Central",CE('CE_invisible.webp')),
    I("Selfie","Profile Pose","Awarded after completing the task New Toony Tourist",PP('Pose-selfie.webp')),
    I("Upset","Profile Pose","Awarded after defeating the Derrick Man",PP('Pose-upset.webp')),
    I("Zany","Nametag","Rewarded from the Monkey See Monkey Do sidetask",NT('Nametag-Zany.webp')),
  ]},
  { name:"Barnacle Boatyard", icon:"⚓", color:"#5a1a05", accent:"#dc4a14", items:[
    I("Barnacle Boatyard","Background","Awarded for progressing to Barnacle Boatyard in the Taskline",BG('BarnacleBoatyard.webp')),
    I("Barnacle Boatyard Sky","Background","Awarded for visiting Barnacle Boatyard",BG('BarnacleBoatyardSkyBackground.webp')),
    I("On The Dock","Background","Awarded after completing the Silverware Sting Kudos Rank-Up Task",BG('OnTheDockBackground.webp')),
    I("Barnacle Boatyard","Nameplate","Awarded for riding the Boat in Barnacle Boatyard for 20 Laps",NP('BarnacleBoatyardNameplate.webp')),
    I("Sandcastles","Nameplate","Awarded after completing the Silverware Sting Kudos Rank-Up Task",NP('SandcastlesNameplate.webp')),
    I("Big Legs","Cheesy Effect","Awarded after completing The Salty Spit-toon sidetask",CE('CE_biglegs.webp')),
    I("Boardwalk","Nametag","Rewarded from the Straight to Boardwalk sidetask",NT('Boardwalk.webp')),
    I("Diving","Profile Pose","Awarded after completing the task Swimming Kiwi",PP('Pose-diving.webp')),
    I("I'm Outta Here!","Profile Pose","Awarded after defeating the Land Acquisition Architect",PP("Pose-I'm_outta_here.webp")),
    I("Nautical","Nametag","Rewarded from The Salty Spit-toon sidetask",NT('Nautical_Nametag.webp')),
    I("Pirate","Nametag","Rewarded for completing the 7th Layer Wrapping Paper Rank-Up Task (Kudos Rank 8, Barnacle Boatyard)",NT('Pirate_Nametag.webp')),
    I("Treasure","Profile Pose","Awarded after reaching Barnacle Boatyard Kudos Rank 5",PP('Pose-Treasure.webp')),
    I("Wonky","Nametag","Rewarded from the First Mate Makeover sidetask",NT('Wonky.webp')),
  ]},
  { name:"Ye Olde Toontowne", icon:"👑", color:"#33205e", accent:"#9b70cc", items:[
    I("Ye Olde Toontowne","Background","Awarded for progressing to Ye Olde Toontowne in the Taskline",BG('YeOleToontowneBackground.webp')),
    I("Ye Olde Toontowne Sky","Background","Awarded for visiting Ye Olde Toontowne",BG('YOTTskyBackground.webp')),
    I("Hearty Feast","Background","Awarded after completing the Doodragon Festival Kudos Rank-Up Task",BG('HeartyFeastBackground.webp')),
    I("Ye Olde Toontowne","Nameplate","Awarded for touching the Well in Ye Olde Toontowne",NP('YOTT.webp')),
    I("The Doodragon","Nameplate","Awarded after completing the Doodragon Festival Kudos Rank-Up Task",NP('TheDoodragonNameplate.webp')),
    I("At The Gate","Profile Pose","Awarded after reaching Ye Olde Toontowne Kudos Rank 5",PP('Pose-At_The_Gate.webp')),
    I("Casting","Profile Pose","Awarded after completing the task The Golden Penny",PP('Pose-casting.webp')),
    I("Medieval","Nametag","Rewarded for completing the Fishing Fiasco Rank-Up Task (Kudos Rank 8, Ye Olde Toontowne)",NT('Medieval_Nametag.webp')),
    I("Poetic","Nametag","Rewarded from the Midlife Crisis sidetask",NT('Poetic.webp')),
    I("Small Head","Cheesy Effect","Purchasable or event reward",CE('CE_smallhead.webp')),
    I("To Be or Not To Be?","Profile Pose","Awarded after defeating the Public Relations Representative",PP('Pose-To_be_or_not_to_be.webp')),
    I("Transparent","Cheesy Effect","Purchasable or event reward",CE('CE_transparent.webp')),
  ]},
  { name:"Daffodil Gardens", icon:"🌸", color:"#314600", accent:"#9bd31a", items:[
    I("Daffodil Gardens","Background","Awarded for progressing to Daffodil Gardens in the Taskline",BG('DaffodilGardensBackground.webp')),
    I("Daffodil Gardens Sky","Background","Awarded for visiting Daffodil Gardens",BG('DaffodilSkysBackground.webp')),
    I("Tranquil Fountain","Background","Awarded after completing the Groovy Paintings Kudos Rank-Up Task",BG('TranquilFountainBackground.webp')),
    I("Daffodil Gardens","Nameplate","Awarded for raising the Flower of Doom with 5 Toons in Daffodil Gardens",NP('DaffodilNameplate.webp')),
    I("Gardening","Nameplate","Awarded after completing the Groovy Paintings Kudos Rank-Up Task",NP('GardeningNameplate.webp')),
    I("Calligraphy","Nametag","Rewarded for completing the Quaking and Breaking Rank-Up Task (Kudos Rank 8, Daffodil Gardens)",NT('Calligraphy_Nametag.webp')),
    I("Elegance","Profile Pose","Awarded after reaching Daffodil Gardens Kudos Rank 5",PP('Pose-Elegance.webp')),
    I("Flat Portrait","Cheesy Effect","Purchasable or event reward",CE('CE_flatportrait.webp')),
    I("Green Toon","Cheesy Effect","Awarded from the Monkey See Monkey Do sidetask",CE('CE_greentoon.webp')),
    I("Running","Profile Pose","Awarded after completing the task Wedding Planner",PP('Pose-running.webp')),
    I("Silly","Nametag","Rewarded from the Not-So-Instant Film sidetask",NT('Silly_Nametag.webp')),
  ]},
  { name:"Mezzo Melodyland", icon:"🎵", color:"#482052", accent:"#bf62cb", items:[
    I("Mezzo Melodyland","Background","Awarded for progressing to Mezzo Melodyland in the Taskline",BG('MezzoBackground.webp')),
    I("Mezzo Melodyland Sky","Background","Awarded for visiting Mezzo Melodyland",BG('MezzoMelodylandBackground.webp')),

    I("Rock Concert","Background","Awarded after completing the Rocked Out Kudos Rank-Up Task",BG('RockConcertBackground.webp')),
    I("Mezzo Melodyland","Nameplate","Awarded for jumping on a drum in Mezzo Melodyland ten times in a row",NP('MezzoMelodylandNameplate.webp')),
    I("Fire n' Flames","Nameplate","Awarded after completing the Rocked Out Kudos Rank-Up Task",NP("FiresN'FlamesNameplate.webp")),
    I("Big Head","Cheesy Effect","Purchasable or event reward",CE('CE_bighead.webp')),
    I("Fancy","Nametag","Rewarded from the Got You Covered! sidetask",NT('Fancy_Nametag.webp')),
    I("Flat Profile","Cheesy Effect","Purchasable or event reward",CE('CE_flatprofile.webp')),
    I("Pick Up The Phone","Profile Pose","Awarded after reaching Mezzo Melodyland Kudos Rank 5",PP('Pose-Pick_Up_The_Phone.webp')),
    I("Playful","Nametag","Rewarded for completing the Phonic Phraudulence Rank-Up Task (Kudos Rank 8, Mezzo Melodyland)",NT('Playful_Nametag.webp')),
    I("Presenting...","Profile Pose","Awarded after completing the task Piano Player",PP('Pose-presenting.webp')),
    I("Whimsical","Nametag","Rewarded from the Flat Notes & Profiles sidetask",NT('Whimsical_Nametag.webp')),
  ]},
  { name:"The Brrrgh", icon:"❄️", color:"#003a46", accent:"#29b2dc", items:[
    I("The Brrrgh","Background","Awarded for progressing to The Brrrgh in the Taskline",BG('TheBrrrghBackground.webp')),
    I("The Brrrgh Sky","Background","Awarded for visiting The Brrrgh",BG('BrrrghSkyBackground.webp')),
    I("Doodlesledding","Background","Awarded after completing the Paula's Parent Present Party Kudos Rank-Up Task",BG('DoodlesleddingBackground.webp')),
    I("The Brrrgh","Nameplate","Awarded for touching all 5 Ice Blocks in The Brrrgh Playground",NP('BrrrghNameplate.webp')),
    I("Snowball Fight","Nameplate","Awarded for making Steve the Snowman grow to his largest possible size by throwing snowballs at him",NP('SnowballFightNameplate.webp')),
    I("Scarf","Nameplate","Awarded after completing the Paula's Parent Present Party Kudos Rank-Up Task",NP('ScarfNameplate.webp')),
    I("Big White Toon","Cheesy Effect","Purchasable or event reward",CE('CE_bigwhitetoon.webp')),
    I("Comical","Nametag","Rewarded from the Soup Served Sad sidetask",NT('Comical_Nametag.webp')),
    I("Fire Hands","Profile Pose","Awarded after reaching The Brrrgh Kudos Rank 5",PP('Pose-fire-hands.webp')),
    I("No Color","Cheesy Effect","Purchasable or event reward",CE('CE_nocolor.webp')),
    I("Shivering","Nametag","Rewarded from the Stevey The Snowman! sidetask",NT('Shivering_Nametag.webp')),
    I("Surprised","Profile Pose","Awarded after completing the task Gathering Warmth",PP('Pose-surprised.webp')),
    I("Wireframe","Cheesy Effect","Purchasable or event reward",CE('CE_wireframe.webp')),
  ]},
  { name:"Acorn Acres", icon:"🌰", color:"#00451e", accent:"#20cf69", items:[
    I("Acorn Acres","Background","Awarded for progressing to Acorn Acres in the Taskline",BG('AABackground.webp')),
    I("Acorn Acres Sky","Background","Awarded for visiting Acorn Acres",BG('AASkyBackground.webp')),
    I("Light Show","Background","Awarded from completing the Perilous Party Preparations Kudos Rank-Up Task",BG('LightShowBackground.webp')),
    I("Acorn Acres","Nameplate","Awarded for swimming from downriver to the waterfall in Acorn Acres",NP('AANameplate.webp')),
    I("Light Show","Nameplate","Awarded after completing the Perilous Party Preparations Kudos Rank-Up Task",NP('LightsShowNameplate.webp')),
    I("Arrogant","Nametag","Rewarded from the Nathan's Nutrition sidetask",NT('Arrogant_Nametag.webp')),
    I("Big Toon","Cheesy Effect","Purchasable or event reward",CE('CE_bigtoon.webp')),
    I("Greened","Profile Pose","Awarded after completing the task Survival Kit Builder",PP('Pose-greened.webp')),
    I("Practical","Nametag","Rewarded from the When Nature Calls sidetask",NT('PracticalNametag.webp')),
    I("Rolled","Profile Pose","Awarded after reaching Acorn Acres Kudos Rank 5",PP('Pose-Rolled.webp')),
    I("Small Legs","Cheesy Effect","Purchasable or event reward",CE('CE_smalllegs.webp')),
  ]},
  { name:"Drowsy Dreamland", icon:"💤", color:"#1a1060", accent:"#7b68ee", items:[
    I("Drowsy Dreamland","Background","Awarded for progressing to Drowsy Dreamland in the Taskline",BG('DrowsyDreamlandPGBackground.webp')),
    I("Drowsy Dreamland Sky","Background","Awarded for visiting Drowsy Dreamland",BG('DrowsyDreamlandBackground.webp')),
    I("Sweet","Background","Awarded from completing the Candy Conundrum Kudos Rank-Up Task",BG('SweetBackground.webp')),
    I("Drowsy Dreamland","Nameplate","Awarded for saying \"I'm Sleepy\" located in the \"Friendly\" section of SpeedChat in Drowsy Dreamland 20 times",NP('DrowsyDreamlandNameplate.webp')),
    I("Sweet","Nameplate","Awarded after completing the Candy Conundrum Kudos Rank-Up Task",NP('SweetNameplate.webp')),
    I("Action","Nametag","Rewarded from the Short Story sidetask",NT('ActionNametag.webp')),
    I("Cinema","Nametag","Rewarded for completing the Doze Were Mine! Rank-Up Task (Kudos Rank 8, Drowsy Dreamland)",NT('CinemaNametag.webp')),
    I("Naptime","Profile Pose","Awarded after reaching Drowsy Dreamland Kudos Rank 5",PP('Pose-Naptime.webp')),
    I("Resistance Salute","Emotion","Say SpeedChat \"Would you like some help?\" under Friendly to Whispering Willow in Talking In Your Sleep Voice Training on Pajama Place, Drowsy Dreamland",EM('neutral/Resistance_Salute.webp')),
    I("Small Toon","Cheesy Effect","Purchasable or event reward",CE('CE_smalltoon.webp')),
    I("Western","Nametag","Rewarded from the Ol' West sidetask",NT('WesternNametag.webp')),
    I("Yawn","Profile Pose","Awarded after completing the task Camera Repair",PP('Pose-yawning.webp')),
  ]},
  { name:"Unobtainable", icon:"🔒", color:"#1a1a1a", accent:"#888888", items:[
    I("Sky Clan","Background","Awarded for completing a Sky Clan task during the Mayday event (Unobtainable)",BG('SkyclanBackground.webp')),
    I("Break The Law!","Background","Awarded for getting 4 Pink Slip Pieces during Break The Law (Unobtainable)",BG('BTLbackground.webp')),
    I("New Years 2019 Fireworks","Background","Awarded during the 2019 New Years Event (Unobtainable)",BG('NewYear2019Background.webp')),
    I("New Years 2020 Fireworks","Background","Awarded during the 2020 New Years Event (Unobtainable)",BG('NewYears2020Background.webp')),
    I("Easter 2020","Background","Awarded after using the Easter 2020 code \"eggcellent\" (Unobtainable)",BG('Easter2020Background.webp')),
    I("Valentine's 2020","Background","Awarded after using the Valentoon's 2020 code \"lovestruck\" (Unobtainable)",BG('Valentines2020Background.webp')),
    I("Artificial Progeny","Background","Awarded for defeating the Witness Stand-In during Break The Law (Unobtainable)",BG('ArtificalProgenyBackground.webp')),
    I("Fireworks Show","Background","Awarded after using the 2020 Summer code \"fireworks\" (Unobtainable)",BG('FireworksShowBackground.webp')),
    I("Dreams Come True","Nameplate","Awarded for completing the Sky Clan ARG during the Mayday event (Unobtainable)",NP('DreamsComeTrue.webp')),
    I("Atticus' Desk","Nameplate","Awarded for defeating the Witness Stand-In during Break The Law (Unobtainable)",NP('AtticusDeskNameplate.webp')),
    I("Pink Slip","Nameplate","Awarded for finding 5 Pink Slip Pieces during Break The Law (Unobtainable)",NP('PinkSlipNameplate.webp')),
    I("Thanksgiving 2019","Nameplate","Awarded for attending the 2019 Thanksgiving Event (Unobtainable)",NP('Thanksgiving2019Namepalte.webp')),
    I("New Years Fireworks 2019","Nameplate","Awarded for attending the 2019 New Years Event (Unobtainable)",NP('2019Nameplate.webp')),
    I("New Years Fireworks 2020","Nameplate","Awarded for attending the 2020 New Years Event (Unobtainable)",NP('2020Nameplate.webp')),
    I("Easter 2020","Nameplate","Awarded for using the 2020 Easter Event code \"eggcellent\" (Unobtainable)",NP('Easter2020Nameplate.webp')),
    I("Candy","Nameplate","Awarded for solving the 2018 Christmas ARG (Unobtainable)",NP('Candy.webp')),

    I("Prepare for Launch","Nameplate","Awarded after using the 2020 Summer code \"fireworks\" (Unobtainable)",NP('PrepareForLaunchNameplate.webp')),
    I("Pumpkin Head","Cheesy Effect","Awarded by Trick-or-Treating (Halloween 2018)",CE('H2018PumpkinDouble.webp')),
    I("Pumpkin Head","Cheesy Effect","Awarded by Trick-or-Treating (Halloween 2019)",CE('H2019PumpkinDouble.webp')),
    I("Pumpkin Behind the Carving","Cheesy Effect","Awarded by Trick-or-Treating (Halloween 2020)",CE('WilliamPumpkinDouble.webp')),
    I("Flared Up Hallows","Cheesy Effect","Awarded by Trick-or-Treating (Halloween 2021)",CE('FlaredUpHallowsDouble.webp')),
    I("Yarr & Harr","Cheesy Effect","Awarded by Trick-or-Treating (Halloween 2023-2025)",CE('Yarr&HarrDouble.webp')),
    I("Pink Slip","Cheesy Effect","Awarded for getting 6 Pink Slip Pieces during Break The Law",CE('CE_Pinkslip.webp')),
  ]},
];
export const COLLECTION_TYPES = ['Background','Nameplate','Nametag','Profile Pose','Cheesy Effect','Emotion'] as const;
export type CollectionType = typeof COLLECTION_TYPES[number];
