﻿export interface TaskStep { text: string; sub?: string; }
export interface ShopTask { name: string; type: string; wikiUrl: string; steps: TaskStep[]; reward: string; }
export interface Fisherman { name: string; img: string; }
export interface Shop { name: string; owner: string | null; ownerImg: string | null; mapImg: string | null; shopImg: string | null; role?: string; trivia?: string; tasks: ShopTask[]; }
export interface StreetShopData { streetName: string; neighborhood?: string; mainMap: string; shopsBase: string; fisherman?: Fisherman; shops: Shop[]; }

export const STREET_SHOPS: Record<string, StreetShopData> = {};

const TTC_LOOPY: StreetShopData = {
  streetName: `Loopy Lane`,
  mainMap: `/icons/streets/Toontown-Central/Loopy-Lane/main-map.webp`,
  shopsBase: `/icons/streets/Toontown-Central/Loopy-Lane`,
  fisherman: { name: `Fisherman Droopy`, img: `Droopy.webp` },
  shops: [
    { name: `Seltzer Bottles and Cans`, owner: `Sid Seltzer`, ownerImg: `SidSeltzer.webp`, mapImg: `SeltzerBottlesAndCansMapLocation.webp`, shopImg: `SeltzerBottlesandCans.webp`, tasks: [{ name: `Gathering Gags`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Gathering_Gags`, steps: [{ text: `Visit Rancid Robert at Slip and Slide on Wacky Way (36 XP, 2 JBS)` }, { text: `Return to Rancid Robert at Slip and Slide on Wacky Way (36 XP, 2 JBS)`, sub: `Defeat 3 Cogs on Wacky Way` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }, { text: `Visit Ma Putrid at House of Bad Pies on Silly Street (36 XP, 2 JBS)` }, { text: `Return to Ma Putrid at House of Bad Pies on Silly Street (36 XP, 2 JBS)`, sub: `Recover 3 Pencil Shavings from Pencil Pushers in Toontown Central` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }, { text: `Visit Sid Seltzer at Seltzer Bottles and Cans on Loopy Lane (36 XP, 2 JBS)` }, { text: `Return to Sid Seltzer at Seltzer Bottles and Cans on Loopy Lane (36 XP, 2 JBS)`, sub: `Recover 3 Springs from The Cogs in Toontown Central` }, { text: `Visit Lord Lowden Clear at Toon HQ (356 XP, 22 JBS)` }], reward: `356 XP - 22 JBS (final step)` }] },
    { name: `Vanishing Cream`, owner: `Nona Seeya`, ownerImg: `NonaSeeya.webp`, mapImg: `VanishingCreamMapLocation.webp`, shopImg: `VanishingCream.webp`, tasks: [{ name: `Cream-Be-Gone`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Cream-Be-Gone`, steps: [{ text: `Visit Nona Seeya at Vanishing Cream on Loopy Lane` }, { text: `Return to Nona Seeya at Vanishing Cream on Loopy Lane`, sub: `Recover 5 Samples of Ink from The Lawbots Anywhere` }, { text: `Return to Nona Seeya at Vanishing Cream on Loopy Lane`, sub: `Go Fishing for 4 Bags of Salt Anywhere` }, { text: `Return to Nona Seeya at Vanishing Cream on Loopy Lane`, sub: `Recover 3 Plastic Containers from The Cogs Anywhere` }, { text: `Return to Nona Seeya at Vanishing Cream on Loopy Lane`, sub: `Defeat 10 Cogs Anywhere` }], reward: `516 XP - Invisible Toon Cheesy Effect` }] },
    { name: `Used Firecrackers`, owner: `Smokey Joe`, ownerImg: `SmokeyJoe.webp`, mapImg: `UsedFirecrackersMapLocation.webp`, shopImg: `UsedFirecrackers.webp`, tasks: [] },
    { name: `The Meatball Shoppe`, owner: `Papa Stahl`, ownerImg: `PapaStahl.webp`, mapImg: `TheMeatballShoppeMapLocation.webp`, shopImg: `TheMeatballShoppe.webp`, trivia: `Originally named Loopy’s Balls after YouTuber LoopyGoopyG, then Loopy’s Meatballs, and finally renamed to The Meatball Shoppe in v1.0.13.`, tasks: [] },
    { name: `Unnamed Shop`, owner: `Sam Stain`, ownerImg: `SamStain.webp`, mapImg: `SamStainShopMapLocation.webp`, shopImg: `SamStain'sShop.webp`, trivia: `This is the only unnamed shop in the game to possess an NPC.`, tasks: [] },
    { name: `Visible Ink`, owner: `Inky Ivon`, ownerImg: `InkyIvon.webp`, mapImg: `VisibleInkMaplocation.webp`, shopImg: `VisibleInk.webp`, tasks: [] },
    { name: `The Kaboomery`, owner: `Shorty Fuse`, ownerImg: `ShortyFuse.webp`, mapImg: `TheKaboomeryMapLocation.webp`, shopImg: `TheKaboomery.webp`, tasks: [{ name: `Fire Safety`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Fire_Safety`, steps: [{ text: `Visit Shorty Fuse at The Kaboomery on Loopy Lane` }, { text: `Return to Shorty Fuse at The Kaboomery on Loopy Lane`, sub: `Recover 5 Igniters from The Cogs Anywhere` }, { text: `Return to Shorty Fuse at The Kaboomery on Loopy Lane`, sub: `Recover 5 Metal Casings from The Cogs Anywhere` }, { text: `Return to Shorty Fuse at The Kaboomery on Loopy Lane`, sub: `Recover 5 Metal Plates from The Cogs Anywhere` }], reward: `230 XP - Firefighter Outfit` }] },
    { name: `Sidesplitter's Mending`, owner: `Sasha Sidesplitter`, ownerImg: `SashaSidesplitter.webp`, mapImg: `Sidesplitter'sMendingMapLocation.webp`, shopImg: `Sidesplitter'sMending.webp`, tasks: [] },
    { name: `Crack Up Auto Repair`, owner: `Lucy Tires`, ownerImg: `LucyTires.webp`, mapImg: `CrackUpAutoRepairMapLocation.webp`, shopImg: `CrackUpAutoRepair.webp`, tasks: [] },
    { name: `Suction Cups and Saucers`, owner: `Clovinia Cling`, ownerImg: `CloviniaCling.webp`, mapImg: `SuctionCupsAndSaucersMapLocation.webp`, shopImg: `SuctionCupsAndSaucers.webp`, tasks: [] },
    { name: `Jest for Laughs`, owner: `Jester Chester`, ownerImg: `JesterChester.webp`, mapImg: `JestForLaughsMapLocation.webp`, shopImg: `JestForLaughs.webp`, tasks: [] },
    { name: `Soup and Crack Ups`, owner: `Sally Spittake`, ownerImg: `SallySpittake.webp`, mapImg: `SoupAndCrackUpsMapLocation.webp`, shopImg: `SoupAndCrackUps.webp`, tasks: [] },
    { name: `Bottled Cans`, owner: `Weird Warren`, ownerImg: `WeirdWarren.webp`, mapImg: `BottledCansMapLocation.webp`, shopImg: `BottledCans.webp`, tasks: [] },
    { name: `Cast-Iron Kites`, owner: `Rick Rockhead`, ownerImg: `RickRockhead.webp`, mapImg: `CastIronKitesMapLocation.webp`, shopImg: `Cast-IronKites.webp`, tasks: [] },
    { name: `Kooky Cineplex`, owner: null, ownerImg: null, mapImg: `KookyCineplexMapLocation.webp`, shopImg: `KookyCineplex.webp`, tasks: [] },
    { name: `Laughter Hours Cafe`, owner: `Tee Hee`, ownerImg: `TeeHee.webp`, mapImg: `LaughterHoursCafeMapLocation.webp`, shopImg: `LaughterHoursCafe.webp`, tasks: [] },
    { name: `Chortle Cafe`, owner: `Charlie Chortle`, ownerImg: `CharlieChortle.webp`, mapImg: `ChortleCafeMapLocation.webp`, shopImg: `ChortleCafe.webp`, tasks: [] },
    { name: `Toontown Post Office`, owner: `Postmaster Pete`, ownerImg: `PostmasterPete.webp`, mapImg: `ToontownPostOfficeMapLocation.webp`, shopImg: `ToontownPostOffice.webp`, tasks: [] },
    { name: `Blue Glue Direct 2 You`, owner: `Sticky Lou`, ownerImg: `StickyLou.webp`, mapImg: `BlueGlueMapLocation.webp`, shopImg: `BlueGlue.webp`, tasks: [{ name: `Sticky Situation`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Sticky_Situation`, steps: [{ text: `Visit Sticky Lou at Blue Glue on Loopy Lane (31 XP, 2 JBS)` }, { text: `Obtain A Reservation Ticket from Silent Simone at The Merry Mimes on Silly Street (31 XP, 2 JBS)` }, { text: `Deliver A Reservation Ticket to Sticky Lou at Blue Glue on Loopy Lane (31 XP, 2 JBS)` }, { text: `Return to Sticky Lou at Blue Glue on Loopy Lane (31 XP, 2 JBS)`, sub: `Recover An Unsticking Object from The Cogs in Toontown Central` }, { text: `Deliver Some Decorative Glue to Bumpy Bumblebehr at Toon HQ (219 XP, 14 JBS)` }], reward: `219 XP - 14 JBS (final step)` }] },
    { name: `Spaghetti and Goofballs`, owner: `Chef Knucklehead`, ownerImg: `ChefKnucklehead.webp`, mapImg: `SpaghettiAndGoofballsMapLocation.webp`, shopImg: `SpaghettiandGoofballs.webp`, tasks: [{ name: `A Taste Of Toontown`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#A_Taste_Of_Toontown`, steps: [{ text: `Visit Chef Knucklehead at Spaghetti and Goofballs on Loopy Lane (36 XP, 2 JBS)` }, { text: `Visit Chef E.Z. Bake at Toontown Mess Hall on Punchline Place (36 XP, 2 JBS)` }, { text: `Visit Chewy Morsel at Rubber Chicken Sandwiches on Punchline Place (36 XP, 2 JBS)` }, { text: `Visit Cindy Sprinkles at Sundae Funnies Ice Cream on Punchline Place (36 XP, 2 JBS)` }, { text: `Return to Chef Knucklehead at Spaghetti and Goofballs on Loopy Lane (36 XP, 2 JBS)`, sub: `Recover 3 Noodles from The Cogs Anywhere` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }], reward: `36 XP per step - continuing mainline chain` }] },
    { name: `Wiseacre's Noisemakers`, owner: `Will Wiseacre`, ownerImg: `WillWiseacre.webp`, mapImg: `Wiseacre'sNoisemakersMapLocation.webp`, shopImg: `Wiseacre'sNoisemakers.webp`, tasks: [] },
    { name: `Movie Multiplex`, owner: null, ownerImg: null, mapImg: `MovieMultiplexMapLocation.webp`, shopImg: `MovieMultiplex.webp`, tasks: [] },
    { name: `14 Karat Goldfish`, owner: `Sharky Jones`, ownerImg: `SharkyJones.webp`, mapImg: `14KaratGoldfishMapLocation.webp`, shopImg: `14KaratGoldfish.webp`, tasks: [] },
    { name: `News for the Amused`, owner: `Paige Arthur`, ownerImg: `PaigeArthur.webp`, mapImg: `NewsForTheAmusedMapLocation.webp`, shopImg: `NewsForTheAmused.webp`, tasks: [] },
  ],
};
STREET_SHOPS[`TTC|Loopy Lane`] = TTC_LOOPY;

const TTC_PUNCHLINE: StreetShopData = {
  streetName: `Punchline Place`,
  mainMap: `/icons/streets/Toontown-Central/Punchline-Place/main-map.webp`,
  shopsBase: `/icons/streets/Toontown-Central/Punchline-Place`,
  fisherman: { name: `Fisherman Punchy`, img: `Punchy.webp` },
  shops: [
    { name: `Sofa Whoopee Cushions`, owner: `Nancy Gas`, ownerImg: `NancyGas.webp`, mapImg: `SofaWhoopeeCushionsMapLocation.webp`, shopImg: `SofaWhoopeeCushions.webp`, tasks: [] },
    { name: `Inflatable Wrecking Balls`, owner: `Big Bruce`, ownerImg: `BigBruce.webp`, mapImg: `InflatableWreckingBallsMapLocation.webp`, shopImg: `InflatableWreckingBalls.webp`, tasks: [] },
    { name: `The Karnival Kid`, owner: null, ownerImg: null, mapImg: `TheKarnivalKidMapLocation.webp`, shopImg: `TheKarnivalKid.webp`, tasks: [] },
    { name: `Dr. Pulyurleg, Chiropractor`, owner: `Dr. Pulyurleg`, ownerImg: `Dr.Pulyurleg.webp`, mapImg: `Dr.PulyurlegChiropractorMapLocation.webp`, shopImg: `Dr.PulyurlegChiropractor.webp`, tasks: [{ name: `Smart Minds Think Unalike`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Smart_Minds_Think_Unalike`, steps: [{ text: `Visit Flippy at Toon Hall (40 XP, 2 JBS)` }, { text: `Visit Dr. Pulyurleg at Dr. Pulyurleg, Chiropractor on Punchline Place (40 XP, 2 JBS)` }, { text: `Visit Dr. Sensitive at Hardy Harr Seminars on Punchline Place (40 XP, 2 JBS)` }, { text: `Obtain A Love Letter from Dr. Pulyurleg at Dr. Pulyurleg, Chiropractor on Punchline Place (40 XP, 2 JBS)` }, { text: `Return to Dr. Pulyurleg at Dr. Pulyurleg, Chiropractor on Punchline Place (40 XP, 2 JBS)`, sub: `Recover A Love Letter from Double Talkers Anywhere` }, { text: `Return to Dr. Pulyurleg at Dr. Pulyurleg, Chiropractor on Punchline Place (40 XP, 2 JBS)`, sub: `Fish up A Supply of Ink in Toontown Central` }, { text: `Deliver A Love Letter to Dr. Sensitive at Hardy Harr Seminars on Punchline Place (40 XP, 2 JBS)` }, { text: `Visit Flippy at Toon Hall (362 XP, 22 JBS)` }], reward: `362 XP - 22 JBS (final step)` }] },
    { name: `Toontown Mess Hall`, owner: `Chef E.Z. Bake`, ownerImg: `ChefE.Z.Bake.webp`, mapImg: `ToontownMessHallMapLocation.webp`, shopImg: `ToontownMessHall.webp`, tasks: [{ name: `A Taste Of Toontown`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#A_Taste_Of_Toontown`, steps: [{ text: `Visit Chef Knucklehead at Spaghetti and Goofballs on Loopy Lane (36 XP, 2 JBS)` }, { text: `Visit Chef E.Z. Bake at Toontown Mess Hall on Punchline Place (36 XP, 2 JBS)` }, { text: `Visit Chewy Morsel at Rubber Chicken Sandwiches on Punchline Place (36 XP, 2 JBS)` }, { text: `Visit Cindy Sprinkles at Sundae Funnies Ice Cream on Punchline Place (36 XP, 2 JBS)` }, { text: `Return to Chef Knucklehead at Spaghetti and Goofballs on Loopy Lane (36 XP, 2 JBS)`, sub: `Recover 3 Noodles from The Cogs Anywhere` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }], reward: `36 XP per step - continuing mainline chain` }] },
    { name: `Barely Palatable Pasta`, owner: `Crunchy Alfredo`, ownerImg: `CrunchyAlfredo.webp`, mapImg: `BarelyPalatablePastaMapLocation.webp`, shopImg: `BarelyPalatablePasta.webp`, tasks: [] },
    { name: `Hardy Harr Seminars`, owner: `Dr. Sensitive`, ownerImg: `Dr.Sensitive.webp`, mapImg: `HardyHarrSeminarsMapLocation.webp`, shopImg: `HardyHarrSeminars.webp`, tasks: [{ name: `Smart Minds Think Unalike`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Smart_Minds_Think_Unalike`, steps: [{ text: `Visit Flippy at Toon Hall (40 XP, 2 JBS)` }, { text: `Visit Dr. Pulyurleg at Dr. Pulyurleg, Chiropractor on Punchline Place (40 XP, 2 JBS)` }, { text: `Visit Dr. Sensitive at Hardy Harr Seminars on Punchline Place (40 XP, 2 JBS)` }, { text: `Obtain A Love Letter from Dr. Pulyurleg at Dr. Pulyurleg, Chiropractor on Punchline Place (40 XP, 2 JBS)` }, { text: `Return to Dr. Pulyurleg at Dr. Pulyurleg, Chiropractor on Punchline Place (40 XP, 2 JBS)`, sub: `Recover A Love Letter from Double Talkers Anywhere` }, { text: `Return to Dr. Pulyurleg at Dr. Pulyurleg, Chiropractor on Punchline Place (40 XP, 2 JBS)`, sub: `Fish up A Supply of Ink in Toontown Central` }, { text: `Deliver A Love Letter to Dr. Sensitive at Hardy Harr Seminars on Punchline Place (40 XP, 2 JBS)` }, { text: `Visit Flippy at Toon Hall (362 XP, 22 JBS)` }], reward: `362 XP - 22 JBS (final step)` }] },
    { name: `The Punch Line Gym`, owner: `Franz Neckvein`, ownerImg: `FranzNeckvein.webp`, mapImg: `ThePunchLineGymMapLocation.webp`, shopImg: `ThePunchLineGym.webp`, tasks: [{ name: `A Hairy Introduction`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#A_Hairy_Introduction`, steps: [{ text: `Visit Franz Neckvein at The Punch Line Gym on Punchline Place (58 XP, 2 JBS)` }, { text: `Return to Franz Neckvein at The Punch Line Gym on Punchline Place (58 XP, 2 JBS)`, sub: `Recover Some Exercise Supplies from The Cogs in Toontown Central` }, { text: `Return to Franz Neckvein at The Punch Line Gym on Punchline Place (58 XP, 2 JBS)`, sub: `Defeat 3 Cogs in Toontown Central` }, { text: `Visit Mata Hairy at Toon HQ (292 XP, 12 JBS)` }], reward: `292 XP - 12 JBS (final step)` }] },
    { name: `Toontown Theatre`, owner: null, ownerImg: null, mapImg: `ToontownTheatreMapLocation.webp`, shopImg: `ToontownTheatre.webp`, tasks: [] },
    { name: `Funny Bone Emergency Room`, owner: `Nurse Nancy`, ownerImg: `NurseNancy.webp`, mapImg: `FunnyBoneEmergencyRoomMapLocation.webp`, shopImg: `FunnyBoneEmergencyRoom.webp`, tasks: [] },
    { name: `Phony Baloney`, owner: `Tony Maroni`, ownerImg: `TonyMaroni.webp`, mapImg: `PhonyBaloneyMapLocation.webp`, shopImg: `PhonyBaloney.webp`, tasks: [{ name: `Monkey See Monkey Do`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Monkey_See_Monkey_Do`, steps: [{ text: `Visit Pants On Fire at The Building Beside Me is Lying to you on Wacky Way` }, { text: `Visit Liar Liar at No, the Building Beside Me is Telling the Truth on Wacky Way` }, { text: `Return to Pants On Fire at The Building Beside Me is Lying to you on Wacky Way`, sub: `Defeat 6 Cogs on Wacky Way` }, { text: `Return to Pants On Fire at The Building Beside Me is Lying to you on Wacky Way` }, { text: `Visit Tony Maroni at Phony Baloney on Punchline Place`, sub: `Recover Some Baloney from Flunkies in Toontown Central` }, { text: `Return to Tony Maroni at Phony Baloney on Punchline Place` }, { text: `Visit Pants On Fire at The Building Beside Me is Lying to you on Wacky Way` }, { text: `Visit Liar Liar at No, the Building Beside Me is Telling the Truth on Wacky Way` }], reward: `558 XP - Zany Nametag Font - 30 JBS` }] },
    { name: `Zippy's Zingers`, owner: `Zippy`, ownerImg: `Zippy.webp`, mapImg: `Zippy'sZingersMapLocation.webp`, shopImg: `Zippy'sZingers.webp`, tasks: [] },
    { name: `The Flying Pie`, owner: `Ned Slinger`, ownerImg: `NedSlinger.webp`, mapImg: `TheFlyingPieMapLocation.webp`, shopImg: `TheFlyingPie.webp`, tasks: [{ name: `Jokey Jam (Continuation)`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Jokey_Jam`, steps: [{ text: `Visit Ned Slinger at The Flying Pie on Punchline Place (43 XP, 2 JBS)` }, { text: `Defeat 5 Cogs in Toontown Central` }, { text: `Return to Ned Slinger at The Flying Pie on Punchline Place (43 XP, 2 JBS)` }, { text: `Defeat 10 Cogs in Toontown Central` }, { text: `Return to Ned Slinger at The Flying Pie on Punchline Place (486 XP)` }], reward: `486 XP - TTC Rank 6 - 30% Cheaper Gags in TTC - +1 TTC G.U.M.B.A.L.L. Booster` }] },
    { name: `Professor Wiggle's House of Giggles`, owner: `Professor Wiggle`, ownerImg: `ProfessorWiggle.webp`, mapImg: `ProfessorWiggle'sHouseOfGigglesMapLocation.webp`, shopImg: `ProfessorWiggle'sHouseOfGiggles.webp`, tasks: [] },
    { name: `Rubber Chicken Sandwiches`, owner: `Chewy Morsel`, ownerImg: `ChewyMorsel.webp`, mapImg: `RubberChickenSandwichesMapLocation.webp`, shopImg: `RubberChickenSandwiches.webp`, tasks: [{ name: `A Taste Of Toontown`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#A_Taste_Of_Toontown`, steps: [{ text: `Visit Chef Knucklehead at Spaghetti and Goofballs on Loopy Lane (36 XP, 2 JBS)` }, { text: `Visit Chef E.Z. Bake at Toontown Mess Hall on Punchline Place (36 XP, 2 JBS)` }, { text: `Visit Chewy Morsel at Rubber Chicken Sandwiches on Punchline Place (36 XP, 2 JBS)` }, { text: `Visit Cindy Sprinkles at Sundae Funnies Ice Cream on Punchline Place (36 XP, 2 JBS)` }, { text: `Return to Chef Knucklehead at Spaghetti and Goofballs on Loopy Lane (36 XP, 2 JBS)`, sub: `Recover 3 Noodles from The Cogs Anywhere` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }], reward: `36 XP per step - continuing mainline chain` }] },
    { name: `Punchline Movie Palace`, owner: null, ownerImg: null, mapImg: `PunchlineMoviePalaceMapLocation.webp`, shopImg: `PunchlineMoviePalace.webp`, tasks: [] },
    { name: `Sundae Funnies Ice Cream`, owner: `Cindy Sprinkles`, ownerImg: `CindySprinkles.webp`, mapImg: `SundaeFunniesMapLocation.webp`, shopImg: `SundaeFunniesIceCream.webp`, tasks: [{ name: `A Taste Of Toontown`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#A_Taste_Of_Toontown`, steps: [{ text: `Visit Chef Knucklehead at Spaghetti and Goofballs on Loopy Lane (36 XP, 2 JBS)` }, { text: `Visit Chef E.Z. Bake at Toontown Mess Hall on Punchline Place (36 XP, 2 JBS)` }, { text: `Visit Chewy Morsel at Rubber Chicken Sandwiches on Punchline Place (36 XP, 2 JBS)` }, { text: `Visit Cindy Sprinkles at Sundae Funnies Ice Cream on Punchline Place (36 XP, 2 JBS)` }, { text: `Return to Chef Knucklehead at Spaghetti and Goofballs on Loopy Lane (36 XP, 2 JBS)`, sub: `Recover 3 Noodles from The Cogs Anywhere` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }], reward: `36 XP per step - continuing mainline chain` }] },
  ],
};
STREET_SHOPS[`TTC|Punchline Place`] = TTC_PUNCHLINE;

const TTC_SILLY: StreetShopData = {
  streetName: `Silly Street`,
  mainMap: `/icons/streets/Toontown-Central/Silly-Street/main-map.webp`,
  shopsBase: `/icons/streets/Toontown-Central/Silly-Street`,
  fisherman: { name: `Fisherman Billy`, img: `Billy.webp` },
  shops: [
    { name: `Impractical Jokes`, owner: `T.P. Rolle`, ownerImg: `T.P.Rolle.webp`, mapImg: `ImpracticalJokesMapLocation.webp`, shopImg: `ImpracticalJokes.webp`, tasks: [] },
    { name: `All Smiles Tooth Repair`, owner: `Dentist Daniel`, ownerImg: `DentistDaniel.webp`, mapImg: `AllSmilesToothRepairMapLocation.webp`, shopImg: `AllSmilesToothRepair.webp`, tasks: [] },
    { name: `Hogwash & Dry`, owner: `Sir Babbles A Lot`, ownerImg: `SirBabblesALot.webp`, mapImg: `HogwashAndDryMapLocation.webp`, shopImg: `Hogwash&Dry.webp`, tasks: [] },
    { name: `One-Liner Miners`, owner: `Canary Coalmine`, ownerImg: `CanaryCoalmine.webp`, mapImg: `OneLinerMinersMapLocation.webp`, shopImg: `One-LinerMiners.webp`, tasks: [] },
    { name: `Toontown Sign Factory`, owner: `Bill Board`, ownerImg: `BillBoard.webp`, mapImg: `ToontownSignFactoryMapLocation.webp`, shopImg: `ToontownSignFactory.webp`, tasks: [] },
    { name: `Jumping Beans`, owner: `Dancing Diego`, ownerImg: `DancingDiego.webp`, mapImg: `JumpingBeansMapLocation.webp`, shopImg: `JumpingBeans.webp`, tasks: [] },
    { name: `All Fun and Games Shop`, owner: `Lazy Hal`, ownerImg: `LazyHal.webp`, mapImg: `AllFunAndGamesShopMapLocation.webp`, shopImg: `AllFunAndGamesShop.webp`, tasks: [] },
    { name: `Tickle Machines`, owner: `Feather Duster`, ownerImg: `FeatherDuster.webp`, mapImg: `TickleMachinesMapLocation.webp`, shopImg: `TickleMachines.webp`, tasks: [] },
    { name: `Dr. Tom Foolery`, owner: `Dr. Foolery`, ownerImg: `Dr.Foolery.webp`, mapImg: `DrTomFooleryMapLocation.webp`, shopImg: `Dr.TomFoolery.webp`, tasks: [] },
    { name: `Toontown Cinerama`, owner: null, ownerImg: null, mapImg: `ToontownCineramaMapLocation.webp`, shopImg: `ToontownCinerama.webp`, tasks: [] },
    { name: `Dr. I.M. Euphoric`, owner: `Dr. Euphoric`, ownerImg: `Dr.Euphoric.webp`, mapImg: `DrIMEuphoricMapLocation.webp`, shopImg: `Dr.I.M.Euphoric.webp`, tasks: [] },
    { name: `The Merry Mimes`, owner: `Silent Simone`, ownerImg: `SilentSimone.webp`, mapImg: `TheMerryMimesMapLocation.webp`, shopImg: `TheMerryMimes.webp`, tasks: [{ name: `Sticky Situation`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Sticky_Situation`, steps: [{ text: `Visit Sticky Lou at Blue Glue on Loopy Lane (31 XP, 2 JBS)` }, { text: `Obtain A Reservation Ticket from Silent Simone at The Merry Mimes on Silly Street (31 XP, 2 JBS)` }, { text: `Deliver A Reservation Ticket to Sticky Lou at Blue Glue on Loopy Lane (31 XP, 2 JBS)` }, { text: `Return to Sticky Lou at Blue Glue on Loopy Lane (31 XP, 2 JBS)`, sub: `Recover An Unsticking Object from The Cogs in Toontown Central` }, { text: `Deliver Some Decorative Glue to Bumpy Bumblebehr at Toon HQ (219 XP, 14 JBS)` }], reward: `219 XP - 14 JBS (final step)` }] },
    { name: `Weird Beard's Disguise Shop`, owner: `Sneezy Kitty`, ownerImg: `SneezyKitty.webp`, mapImg: `WeirdBeard'sDisguiseShopMapLocation.webp`, shopImg: `WeirdBeard'sDisguiseShop.webp`, tasks: [{ name: `Trashcat Troubles`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Trashcat_Troubles`, steps: [{ text: `Visit Travis in the Toontown Central Playground`, sub: `Fish up a PBJ Fish Anywhere` }, { text: `Return to Travis in the Toontown Central Playground` }, { text: `Visit Sneezy Kitty at Weird Beard's Disguise Shop on Silly Street`, sub: `Recover A Beard Supply from Insiders Anywhere` }, { text: `Return to Sneezy Kitty at Weird Beard's Disguise Shop on Silly Street` }, { text: `Visit Travis in the Toontown Central Playground`, sub: `Deliver 5 Level 2 Gags to Travis` }, { text: `Visit Flippy at Toon Hall` }, { text: `Return to Travis in the Toontown Central Playground` }], reward: `528 XP - Trashcat Outfit - 30 JBS` }] },
    { name: `Silly Stunts`, owner: `Rollo The Amazing`, ownerImg: `RolloTheAmazing.webp`, mapImg: `SillyStuntsMapLocation.webp`, shopImg: `SillyStunts.webp`, tasks: [] },
    { name: `All That Razz`, owner: `Roz Berry`, ownerImg: `RozBerry.webp`, mapImg: `AllThatRazzMapLocation.webp`, shopImg: `AllThatRazz.webp`, tasks: [] },
    { name: `Soup Forks`, owner: `Dan Dribbles`, ownerImg: `DanDribbles.webp`, mapImg: `SoupForksMapLocation.webp`, shopImg: `SoupForks.webp`, tasks: [] },
    { name: `Paper Airplanes`, owner: `Patty Papercut`, ownerImg: `PattyPapercut.webp`, mapImg: `PaperAirplanesMapLocation.webp`, shopImg: `PaperAirplanes.webp`, tasks: [] },
    { name: `Laughing Gas Station`, owner: `Sal Snicker`, ownerImg: `SalSnicker.webp`, mapImg: `LaughingGasStationMapLocation.webp`, shopImg: `LaughingGasStation.webp`, tasks: [] },
    { name: `Mary's Go Around Travel Company`, owner: `Mary`, ownerImg: `Mary.webp`, mapImg: `Mary'sGoAroundTravelCompanyMapLocation.webp`, shopImg: `Mary'sGoAroundTravelCompany.webp`, tasks: [] },
    { name: `Happy Hooligans Pub`, owner: `Bruiser McDougal`, ownerImg: `BruiserMcDougal.webp`, mapImg: `HappyHooligansMapLocation.webp`, shopImg: `HappyHooligansPub.webp`, tasks: [] },
    { name: `House of Bad Pies`, owner: `Ma Putrid`, ownerImg: `MaPutrid.webp`, mapImg: `HouseOfBadPiesMapLocation.webp`, shopImg: `HouseOfBadPies.webp`, tasks: [{ name: `Gathering Gags`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Gathering_Gags`, steps: [{ text: `Visit Rancid Robert at Slip and Slide on Wacky Way (36 XP, 2 JBS)` }, { text: `Return to Rancid Robert at Slip and Slide on Wacky Way (36 XP, 2 JBS)`, sub: `Defeat 3 Cogs on Wacky Way` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }, { text: `Visit Ma Putrid at House of Bad Pies on Silly Street (36 XP, 2 JBS)` }, { text: `Return to Ma Putrid at House of Bad Pies on Silly Street (36 XP, 2 JBS)`, sub: `Recover 3 Pencil Shavings from Pencil Pushers in Toontown Central` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }, { text: `Visit Sid Seltzer at Seltzer Bottles and Cans on Loopy Lane (36 XP, 2 JBS)` }, { text: `Return to Sid Seltzer at Seltzer Bottles and Cans on Loopy Lane (36 XP, 2 JBS)`, sub: `Recover 3 Springs from The Cogs in Toontown Central` }, { text: `Visit Lord Lowden Clear at Toon HQ (356 XP, 22 JBS)` }], reward: `356 XP - 22 JBS (final step)` }] },
    { name: `Jesse's Joke Repair`, owner: `Jesse Jester`, ownerImg: `JesseJester.webp`, mapImg: `Jessie'sJokeRepairMapLocation.webp`, shopImg: `Jesse'sJokeRepair.webp`, tasks: [{ name: `Jokey Jam`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Jokey_Jam`, steps: [{ text: `Visit Professor Guffaw at Laughing Lessons on Silly Street (43 XP, 2 JBS)` }, { text: `Return to Professor Guffaw at Laughing Lessons on Silly Street (43 XP, 2 JBS)`, sub: `Recover Some Laughing Gas from The Cogs in Toontown Central` }, { text: `Visit Jesse Jester at Jesse's Joke Repair on Silly Street (43 XP, 2 JBS)` }, { text: `Return to Jesse Jester at Jesse's Joke Repair on Silly Street (43 XP, 2 JBS)`, sub: `Recover Joke Repair Tools from The Cogs in Toontown Central` }, { text: `Deliver Joke Repair Tools to Professor Guffaw at Laughing Lessons on Silly Street (43 XP, 2 JBS)` }, { text: `Visit Mata Hairy at Toon HQ (303 XP, 17 JBS)` }], reward: `303 XP - 17 JBS (final step)` }] },
    { name: `Daffy Taffy`, owner: `Daffy Don`, ownerImg: `DaffyDon.webp`, mapImg: `DaffyTaffyMapLocation.webp`, shopImg: `DaffyTaffy.webp`, tasks: [] },
    { name: `The Happy Times`, owner: `Happy Heikyung`, ownerImg: `HappyHeikyung.webp`, mapImg: `HappyTimesMapLocation.webp`, shopImg: `TheHappyTimes.webp`, tasks: [] },
    { name: `The Laughin' Place`, owner: `Honey Haha`, ownerImg: `HoneyHaha.webp`, mapImg: `TheLaughin'PlaceMapLocation.webp`, shopImg: `TheLaughin'Place.webp`, tasks: [] },
    { name: `Clown Class`, owner: `Professor Binky`, ownerImg: `ProfessorBinky.webp`, mapImg: `ClownClassMapLocation.webp`, shopImg: `ClownClass.webp`, tasks: [] },
    { name: `Laughing Lessons`, owner: `Professor Guffaw`, ownerImg: `ProfessorGuffaw.webp`, mapImg: `LaughingLessonsMapLocation.webp`, shopImg: `LaughingLessons.webp`, tasks: [{ name: `Jokey Jam`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Jokey_Jam`, steps: [{ text: `Visit Professor Guffaw at Laughing Lessons on Silly Street (43 XP, 2 JBS)` }, { text: `Return to Professor Guffaw at Laughing Lessons on Silly Street (43 XP, 2 JBS)`, sub: `Recover Some Laughing Gas from The Cogs in Toontown Central` }, { text: `Visit Jesse Jester at Jesse's Joke Repair on Silly Street (43 XP, 2 JBS)` }, { text: `Return to Jesse Jester at Jesse's Joke Repair on Silly Street (43 XP, 2 JBS)`, sub: `Recover Joke Repair Tools from The Cogs in Toontown Central` }, { text: `Deliver Joke Repair Tools to Professor Guffaw at Laughing Lessons on Silly Street (43 XP, 2 JBS)` }, { text: `Visit Mata Hairy at Toon HQ (303 XP, 17 JBS)` }], reward: `303 XP - 17 JBS (final step)` }] },
    { name: `Funny Money Savings and Loan`, owner: `Woody Nickel`, ownerImg: `WoodyNickel.webp`, mapImg: `FunnyMoneySavings&LoanMapLocation.webp`, shopImg: `FunnyMoneySavings&Loan.webp`, tasks: [] },
    { name: `Used Clown Cars`, owner: `Loony Louis`, ownerImg: `LoonyLouis.webp`, mapImg: `UsedClownCarsMapLocation.webp`, shopImg: null, tasks: [] },
    { name: `Tee-Hee Tea Shop`, owner: `Madam Chuckle`, ownerImg: `MadamChuckle.webp`, mapImg: `TeeHeeTeaShopMapLocation.webp`, shopImg: `Tee-HeeTeaShop.webp`, tasks: [] },
    { name: `Frank's Pranks`, owner: `Frank Furter`, ownerImg: `FrankFurter.webp`, mapImg: `Frank'sPranksMapLocation.webp`, shopImg: `Frank'sPranks.webp`, tasks: [] },
    { name: `Toontown Playhouse`, owner: null, ownerImg: null, mapImg: `ToontownPlayhouseMapLocation.webp`, shopImg: `ToontownPlayhouse.webp`, tasks: [] },
    { name: `Monkey Tricks`, owner: `Harry Ape`, ownerImg: `HarryApe.webp`, mapImg: `MonkeyTricksMapLocation.webp`, shopImg: `MonkeyTricks.webp`, tasks: [] },
    { name: `Joy Buzzers To The World`, owner: `Joy Buzzer`, ownerImg: `JoyBuzzerNPC.webp`, mapImg: `JoyBuzzersToTheWorldMapLocation.webp`, shopImg: `JoyBuzzersToTheWorld.webp`, tasks: [] },
    { name: `Muldoon's Maroon Balloons`, owner: `Muldoon`, ownerImg: `Muldoon.webp`, mapImg: `Muldoon'sMaroonBalloonsMapLocation.webp`, shopImg: `Muldoon'sMaroonBalloons.webp`, tasks: [] },
    { name: `Canned Bottles`, owner: `Spamonia Biggles`, ownerImg: `SpamoniaBiggles.webp`, mapImg: `CannedBottlesMapLocation.webp`, shopImg: `CannedBottles.webp`, tasks: [] },
  ],
};
STREET_SHOPS[`TTC|Silly Street`] = TTC_SILLY;

const TTC_WACKY: StreetShopData = {
  streetName: `Wacky Way`,
  mainMap: `/icons/streets/Toontown-Central/Wacky-Way/main-map.webp`,
  shopsBase: `/icons/streets/Toontown-Central/Wacky-Way`,
  fisherman: { name: `Fisherman Fruity`, img: `Fruity.webp` },
  shops: [
    { name: `Wacky Way Wonderworld`, owner: `Wacky Wally`, ownerImg: `WackyWally.webp`, mapImg: `WackyWayWonderlandMapLocation.webp`, shopImg: `WackyWayWonderland.webp`, tasks: [{ name: `Find the Rain`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Find_the_Rain`, steps: [{ text: `Visit Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)` }, { text: `Visit Louise Connection at Toon Mobile on Wacky Way (47 XP, 3 JBS)` }, { text: `Visit Wacky Wally at Wacky Way Wonderworld on Wacky Way (47 XP, 3 JBS)` }, { text: `Investigate Gagsoline Oil Refineries on Wacky Way (47 XP, 3 JBS)` }, { text: `Return to Wacky Wally at Wacky Way Wonderworld on Wacky Way (47 XP, 3 JBS)`, sub: `Recover A Key from The Bossbots in Toontown Central` }, { text: `Return to Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)` }, { text: `Investigate Gagsoline Oil Refineries on Wacky Way (47 XP, 3 JBS)` }, { text: `Return to Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)`, sub: `Defeat the Derrick Man on Wacky Way` }, { text: `Return to Lord Lowden Clear at Toon HQ (379 XP, 25 JBS)` }], reward: `379 XP - 25 JBS - Barnacle Boatyard Profile Background (final step)` }] },
    { name: `Gagsoline Oil Refineries`, owner: `Derrick Man`, ownerImg: `DerrickMan.webp`, mapImg: `GagsolineMapLocation.webp`, shopImg: `GagsolineOilRefineries.webp`, role: `Toontown Central Manager`, tasks: [{ name: `Find the Rain`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Find_the_Rain`, steps: [{ text: `Visit Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)` }, { text: `Visit Louise Connection at Toon Mobile on Wacky Way (47 XP, 3 JBS)` }, { text: `Visit Wacky Wally at Wacky Way Wonderworld on Wacky Way (47 XP, 3 JBS)` }, { text: `Investigate Gagsoline Oil Refineries on Wacky Way (47 XP, 3 JBS)` }, { text: `Return to Wacky Wally at Wacky Way Wonderworld on Wacky Way (47 XP, 3 JBS)`, sub: `Recover A Key from The Bossbots in Toontown Central` }, { text: `Return to Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)` }, { text: `Investigate Gagsoline Oil Refineries on Wacky Way (47 XP, 3 JBS)` }, { text: `Return to Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)`, sub: `Defeat the Derrick Man on Wacky Way` }, { text: `Return to Lord Lowden Clear at Toon HQ (379 XP, 25 JBS)` }], reward: `379 XP - 25 JBS - Barnacle Boatyard Profile Background (final step)` }] },
    { name: `Toon Mobile`, owner: `Louise Connection`, ownerImg: `LouiseConnection.webp`, mapImg: `ToonMobileMapLocation.webp`, shopImg: `ToonMobileWireless.webp`, tasks: [{ name: `Find the Rain`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Find_the_Rain`, steps: [{ text: `Visit Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)` }, { text: `Visit Louise Connection at Toon Mobile on Wacky Way (47 XP, 3 JBS)` }, { text: `Visit Wacky Wally at Wacky Way Wonderworld on Wacky Way (47 XP, 3 JBS)` }, { text: `Investigate Gagsoline Oil Refineries on Wacky Way (47 XP, 3 JBS)` }, { text: `Return to Wacky Wally at Wacky Way Wonderworld on Wacky Way (47 XP, 3 JBS)`, sub: `Recover A Key from The Bossbots in Toontown Central` }, { text: `Return to Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)` }, { text: `Investigate Gagsoline Oil Refineries on Wacky Way (47 XP, 3 JBS)` }, { text: `Return to Lord Lowden Clear at Toon HQ (47 XP, 3 JBS)`, sub: `Defeat the Derrick Man on Wacky Way` }, { text: `Return to Lord Lowden Clear at Toon HQ (379 XP, 25 JBS)` }], reward: `379 XP - 25 JBS - Barnacle Boatyard Profile Background (final step)` }] },
    { name: `Slip and Slide`, owner: `Rancid Robert`, ownerImg: `RancidRobert.webp`, mapImg: `SlipAndSlideMapLocation.webp`, shopImg: `SlipAndSlide.webp`, tasks: [{ name: `Gathering Gags`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Toontown_Central_Tasks#Gathering_Gags`, steps: [{ text: `Visit Rancid Robert at Slip and Slide on Wacky Way (36 XP, 2 JBS)` }, { text: `Return to Rancid Robert at Slip and Slide on Wacky Way (36 XP, 2 JBS)`, sub: `Defeat 3 Cogs on Wacky Way` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }, { text: `Visit Ma Putrid at House of Bad Pies on Silly Street (36 XP, 2 JBS)` }, { text: `Return to Ma Putrid at House of Bad Pies on Silly Street (36 XP, 2 JBS)`, sub: `Recover 3 Pencil Shavings from Pencil Pushers in Toontown Central` }, { text: `Visit Lord Lowden Clear at Toon HQ (36 XP, 2 JBS)` }, { text: `Visit Sid Seltzer at Seltzer Bottles and Cans on Loopy Lane (36 XP, 2 JBS)` }, { text: `Return to Sid Seltzer at Seltzer Bottles and Cans on Loopy Lane (36 XP, 2 JBS)`, sub: `Recover 3 Springs from The Cogs in Toontown Central` }, { text: `Visit Lord Lowden Clear at Toon HQ (356 XP, 22 JBS)` }], reward: `356 XP - 22 JBS (final step)` }] },
    { name: `Wacky Way-ving Inflatable Arm Flailing Tube Man`, owner: `Al Hare-ington`, ownerImg: `AlHare-ington.webp`, mapImg: `WWIAFTMapLocation.webp`, shopImg: `WackyWay-vingInflatableArmFlallingTubeMan.webp`, tasks: [] },
    { name: `A Gaggle of Gags`, owner: `Good Ol' Honkin' Sally`, ownerImg: `GoodOl'Honkin'Sally.webp`, mapImg: `AGaggleOfGagsMapLocation.webp`, shopImg: `AGaggleOfGags.webp`, tasks: [] },
    { name: `Pies Are Squared`, owner: `P.I. Multiply`, ownerImg: `P.I.Multiply.webp`, mapImg: `PiesAreSquaredMapLocation.webp`, shopImg: `PiesAreSquared.webp`, tasks: [] },
    { name: `Dogs of Wisdom Bookstore`, owner: `Bookworm Bork`, ownerImg: `BookwormBork.webp`, mapImg: `DogsOfWisdomMapLocation.webp`, shopImg: `DogsOfWisdomBookstore.webp`, tasks: [] },
    { name: `The Circuit Breaker`, owner: `Professor Proton`, ownerImg: `ProfessorProton.webp`, mapImg: `TheCircuitBreakerMapLocation.webp`, shopImg: `TheCircuitBreaker.webp`, tasks: [] },
    { name: `Recessed Is In Session`, owner: `B.R. Bea`, ownerImg: `B.R.Bea.webp`, mapImg: `RecessedIsInSessionMapLocation.webp`, shopImg: `RecessedIsInSession.webp`, tasks: [] },
    { name: `Lying Birthday Cakes`, owner: `Chef Foolery`, ownerImg: `ChefFoolery.webp`, mapImg: `LyingBirthdayCakesMapLocation.webp`, shopImg: `LyingBirthdayCakes.webp`, tasks: [] },
    { name: `Topsy Turvey Tailors`, owner: `R.E. Versed`, ownerImg: `R.E.Versed.webp`, mapImg: `TopsyTurveyTailorsMapLocation.webp`, shopImg: `TopsyTurveyTailors.webp`, tasks: [] },
    { name: `The Laughing Fit`, owner: `Louis Laffon`, ownerImg: `LouisLaffon.webp`, mapImg: `TheLaughingFitMapLocation.webp`, shopImg: `TheLaughingFit.webp`, tasks: [] },
    { name: `The Mehvie Theatre`, owner: null, ownerImg: null, mapImg: `TheMehvieTheatreMapLocation.webp`, shopImg: `TheMehvieTheatre.webp`, tasks: [] },
    { name: `Green Eggs and Spam`, owner: `Spam Iam`, ownerImg: `SpamIam.webp`, mapImg: `GreenEggsAndSpamMapLocation.webp`, shopImg: `GreenEggsAndSpam.webp`, tasks: [] },
    { name: `The Building Beside Me is Lying to You`, owner: `Pants On Fire`, ownerImg: `PantsOnFire.webp`, mapImg: `TBBMILTYMapLocation.webp`, shopImg: `TheBuildingBesideMeIsLyingToYou.webp`, tasks: [{ name: `Monkey See Monkey Do`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Monkey_See_Monkey_Do`, steps: [{ text: `Visit Pants On Fire at The Building Beside Me is Lying to you on Wacky Way` }, { text: `Visit Liar Liar at No, the Building Beside Me is Telling the Truth on Wacky Way` }, { text: `Return to Pants On Fire at The Building Beside Me is Lying to you on Wacky Way`, sub: `Defeat 6 Cogs on Wacky Way` }, { text: `Return to Pants On Fire at The Building Beside Me is Lying to you on Wacky Way` }, { text: `Visit Tony Maroni at Phony Baloney on Punchline Place`, sub: `Recover Some Baloney from Flunkies in Toontown Central` }, { text: `Return to Tony Maroni at Phony Baloney on Punchline Place` }, { text: `Visit Pants On Fire at The Building Beside Me is Lying to you on Wacky Way` }, { text: `Visit Liar Liar at No, the Building Beside Me is Telling the Truth on Wacky Way` }], reward: `558 XP - Zany Nametag Font - 30 JBS` }] },
    { name: `No, the Building Beside Me is Telling the Truth`, owner: `Liar Liar`, ownerImg: `LiarLiar.webp`, mapImg: `NTBBMITTTMapLocation.webp`, shopImg: `NoTheBuildingBesideMeIsTellingTheTruth.webp`, tasks: [] },
  ],
};
STREET_SHOPS[`TTC|Wacky Way`] = TTC_WACKY;
// ─────────────────────────────────────────────────────────────────────────────
// BARNACLE BOATYARD
// ─────────────────────────────────────────────────────────────────────────────
const TASK_BIG_BINNACLE_BASH = { name: `Big Binnacle Bash`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Big_Binnacle_Bash`, steps: [{ text: `Visit Billy Budd at Billy Budd's Big Bargain Binnacle Barn on Buccaneer Boulevard (364 XP, 12 JBS)`, sub: `Go Fishing for A Binnacle on Lighthouse Lane` }, { text: `Return to Billy Budd at Billy Budd's Big Bargain Binnacle Barn on Buccaneer Boulevard (364 XP, 12 JBS)` }, { text: `Visit Admiral Hook at Hook's Clock Repair on Buccaneer Boulevard (364 XP, 12 JBS)`, sub: `Defeat 3 Level 3+ Cogs in Barnacle Boatyard` }, { text: `Return to Admiral Hook at Hook's Clock Repair on Buccaneer Boulevard (1819 XP, 62 JBS)` }, { text: `Return to Billy Budd at Billy Budd's Big Bargain Binnacle Barn on Buccaneer Boulevard (163 XP, 6 JBS)` }, { text: `Visit Salty Stan at From Fore to Aft on Buccaneer Boulevard (163 XP, 6 JBS)`, sub: `Recover 4 Spare Parts from The Cogs in Barnacle Boatyard` }, { text: `Return to Salty Stan at From Fore to Aft on Buccaneer Boulevard (163 XP, 6 JBS)`, sub: `Defeat 3 Cogs in Barnacle Boatyard` }, { text: `Return to Salty Stan at From Fore to Aft on Buccaneer Boulevard (163 XP, 6 JBS)` }, { text: `Return to Billy Budd at Billy Budd's Big Bargain Binnacle Barn on Buccaneer Boulevard (163 XP, 6 JBS)` }, { text: `Visit Ree Pare at Flounder and Sink Ship Repair on Anchor Avenue (163 XP, 6 JBS)`, sub: `Recover 2 Spare Metals from The Cogs in Barnacle Boatyard` }, { text: `Return to Ree Pare at Flounder and Sink Ship Repair on Anchor Avenue (163 XP, 6 JBS)` }, { text: `Return to Billy Budd at Billy Budd's Big Bargain Binnacle Barn on Buccaneer Boulevard (2045 XP, 68 JBS)` }, { text: `Visit Wade at Toon HQ (364 XP, 12 JBS)` }], reward: `2045 XP - 68 JBS (Billy Budd final step)` };
const TASK_MEET_MISTY = { name: `Meet Misty`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Meet_Misty`, steps: [{ text: `Visit Misty at Toon HQ in the Barnacle Boatyard Playground (364 XP, 12 JBS)` }, { text: `Visit Helpful Harry at Be Pacific! Customer Support on Anchor Avenue (364 XP, 12 JBS)`, sub: `Recover 4 Support Tickets from The Cogs in Barnacle Boatyard` }, { text: `Return to Helpful Harry at Be Pacific! Customer Support on Anchor Avenue (364 XP, 12 JBS)`, sub: `Defeat 10 Cogs in Barnacle Boatyard` }, { text: `Return to Helpful Harry at Be Pacific! Customer Support on Anchor Avenue (2045 XP, 68 JBS)` }, { text: `Return to Misty at Toon HQ in the Barnacle Boatyard Playground (364 XP, 12 JBS)` }], reward: `2045 XP - 68 JBS (Return to Helpful Harry step)` };
const TASK_CONTACTING = { name: `Contacting Live Support`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Contacting_Live_Support`, steps: [{ text: `Visit Misty at Toon HQ in the Barnacle Boatyard Playground (243 XP, 8 JBS)` }, { text: `Visit Eileen Overboard at Piano Tuna Works for Scale on Buccaneer Boulevard (243 XP, 8 JBS)`, sub: `Defeat 5 Cashbots in Barnacle Boatyard` }, { text: `Return to Eileen Overboard at Piano Tuna Works for Scale on Buccaneer Boulevard (243 XP, 8 JBS)` }, { text: `Return to Misty at Toon HQ (243 XP, 8 JBS)` }, { text: `Visit Cal Estenicks at Poop Deck Gym on Buccaneer Boulevard (243 XP, 8 JBS)`, sub: `Defeat 15 Cogs Anywhere` }, { text: `Return to Cal Estenicks at Poop Deck Gym on Buccaneer Boulevard (243 XP, 8 JBS)` }, { text: `Return to Misty at Toon HQ in the Barnacle Boatyard Playground (1696 XP, 58 JBS)` }], reward: `1696 XP - 58 JBS (final Misty step)` };
const TASK_CAPTAIN = { name: `A Captain For Hire`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#A_Captain_For_Hire`, steps: [{ text: `Visit Melville at Melville's Massive Mizzenmast Mart on Lighthouse Lane (107 XP, 4 JBS)`, sub: `Collect 2 Treasure Chests from Treasure Dive on The Trolley` }, { text: `Return to Melville at Melville's Massive Mizzenmast Mart on Lighthouse Lane (107 XP, 4 JBS)` }, { text: `Visit Flappy Docksplinter at Soles Repaired While U Wait on Buccaneer Boulevard (107 XP, 4 JBS)`, sub: `Recover 3 Wooden Planks from The Cogs in Barnacle Boatyard` }, { text: `Return to Flappy Docksplinter at Soles Repaired While U Wait on Buccaneer Boulevard (107 XP, 4 JBS)` }, { text: `Visit Linda Landlubber at Disembark! Tree Surgeons on Buccaneer Boulevard (107 XP, 4 JBS)`, sub: `Recover 3 Woodcutting Tools from The Cogs in Barnacle Boatyard` }, { text: `Return to Linda Landlubber at Disembark! Tree Surgeons on Buccaneer Boulevard (107 XP, 4 JBS)` }, { text: `Deliver Some Hull Parts to Flappy Docksplinter at Soles Repaired While U Wait on Buccaneer Boulevard (107 XP, 4 JBS)` }, { text: `Visit Melville at Melville's Massive Mizzenmast Mart on Lighthouse Lane (107 XP, 4 JBS)`, sub: `Defeat 5 Cogs on Lighthouse Lane` }, { text: `Return to Melville at Melville's Massive Mizzenmast Mart on Lighthouse Lane (107 XP, 4 JBS)` }, { text: `Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (107 XP, 4 JBS)` }], reward: `Continues to The Weakest Link` };
const TASK_I_CAN_SEE = { name: `I Can See Clearly Now...`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#I_Can_See_Clearly_Now`, steps: [{ text: `Visit Greggory Goggles at Goggle Defoggers on Anchor Avenue (107 XP, 4 JBS)` }, { text: `Deliver A Telescope to Doctor Squall at Out to See Optics on Buccaneer Boulevard (107 XP, 4 JBS)` }, { text: `Obtain Some Shoes from Flappy Docksplinter at Soles Repaired While U Wait on Buccaneer Boulevard (107 XP, 4 JBS)` }, { text: `Deliver Some Shoes to Doctor Squall at Out to See Optics on Buccaneer Boulevard (107 XP, 4 JBS)` }, { text: `Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (1599 XP, 54 JBS)` }], reward: `1599 XP - 54 JBS (final step)` };
const TASK_UNITE_1 = { name: `Unite the Buccaneers!`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Unite_the_Buccaneers!`, steps: [{ text: `Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (107 XP, 4 JBS)` }, { text: `Visit Cal Estenicks at Poop Deck Gym on Buccaneer Boulevard (107 XP, 4 JBS)`, sub: `Recover 3 Gym Equipment Parts from The Cogs in Barnacle Boatyard` }, { text: `Return to Cal Estenicks at Poop Deck Gym on Buccaneer Boulevard (107 XP, 4 JBS)` }, { text: `Return to Barnacle Bessie at The Lighthouse on Lighthouse Lane (107 XP, 4 JBS)` }, { text: `Visit Greggory Goggles at Goggle Defoggers on Anchor Avenue (107 XP, 4 JBS)`, sub: `Defeat 8 Bossbots in Barnacle Boatyard` }, { text: `Return to Greggory Goggles at Goggle Defoggers on Anchor Avenue (107 XP, 4 JBS)` }, { text: `Return to Barnacle Bessie at The Lighthouse on Lighthouse Lane (1696 XP, 58 JBS)` }], reward: `1696 XP - 58 JBS (final Barnacle Bessie step)` };
const TASK_CHARTING = { name: `Charting Smart Charts`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Charting_Smart_Charts`, steps: [{ text: `Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (107 XP, 4 JBS)` }, { text: `Visit Art at Art's Smart Chart Mart on Seaweed Street (107 XP, 4 JBS)`, sub: `Recover Some Maps from The Cogs in Barnacle Boatyard` }, { text: `Return to Art at Art's Smart Chart Mart on Seaweed Street (107 XP, 4 JBS)` }, { text: `Return to Barnacle Bessie at The Lighthouse on Lighthouse Lane (1696 XP, 58 JBS)` }], reward: `1696 XP - 58 JBS (final Barnacle Bessie step)` };
const TASK_IMPORTANT = { name: `The Important Stuff`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#The_Important_Stuff`, steps: [{ text: `Visit Wade at Toon HQ (107 XP, 4 JBS)` }, { text: `Visit Dover at Toon HQ (107 XP, 4 JBS)` }, { text: `Visit River at Toon HQ in the Barnacle Boatyard Playground (107 XP, 4 JBS)` }, { text: `Visit Misty at Toon HQ in the Barnacle Boatyard Playground (107 XP, 4 JBS)` }, { text: `Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (1696 XP, 58 JBS)` }], reward: `1696 XP - 58 JBS (final Barnacle Bessie step)` };
const TASK_PROPELLERS = { name: `Pilfering Propellers`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Pilfering_Propellers`, steps: [{ text: `Visit N.D. Skye at Island, You Land! Airplanes on Anchor Avenue`, sub: `Recover 3 Propellers from Glad Handers in Barnacle Boatyard` }, { text: `Return to N.D. Skye at Island, You Land! Airplanes on Anchor Avenue`, sub: `Defeat 7 Level 4+ Cogs Anywhere` }, { text: `Return to N.D. Skye at Island, You Land! Airplanes on Anchor Avenue`, sub: `Recover Some Window Panes from a Cog Building in Barnacle Boatyard` }, { text: `Return to N.D. Skye at Island, You Land! Airplanes on Anchor Avenue` }], reward: `2388 XP - Teleport Access to Barnacle Boatyard` };
const TASK_SPIT_TOON = { name: `The Salty Spit-toon`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/The_Salty_Spit-toon`, steps: [{ text: `Visit Reg at The Salty Spit-toon on Anchor Avenue`, sub: `Defeat 12 Level 3+ Cogs Anywhere` }, { text: `Return to Reg at The Salty Spit-toon on Anchor Avenue`, sub: `Defeat 2 Cog Buildings Anywhere` }, { text: `Return to Reg at The Salty Spit-toon on Anchor Avenue`, sub: `Defeat 3 Yesmen Anywhere` }, { text: `Return to Reg at The Salty Spit-toon on Anchor Avenue`, sub: `Deliver 5 Level 3 Gags to Reg` }, { text: `Return to Reg at The Salty Spit-toon on Anchor Avenue` }], reward: `2580 XP - Big Legs Cheesy Effect - Nautical Nametag Font` };
const TASK_SEA_LADS = { name: `Dressing Sea-Lads and Lasses`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Dressing_Sea-Lads_and_Lasses`, steps: [{ text: `Visit Fishy Frank at Salmon Chanted Evening Formal Wear on Buccaneer Boulevard`, sub: `Collect 10 Treasures in the Barnacle Boatyard Playground` }, { text: `Return to Fishy Frank at Salmon Chanted Evening Formal Wear on Buccaneer Boulevard`, sub: `Recover Some Small Sewing Needles from Micromanagers Anywhere` }, { text: `Return to Fishy Frank at Salmon Chanted Evening Formal Wear on Buccaneer Boulevard`, sub: `Recover A Piece of Thread from The Cogs Anywhere` }, { text: `Return to Fishy Frank at Salmon Chanted Evening Formal Wear on Buccaneer Boulevard`, sub: `Defeat a Cog Building Anywhere` }, { text: `Return to Fishy Frank at Salmon Chanted Evening Formal Wear on Buccaneer Boulevard` }], reward: `2394 XP - Sailor Outfit` };
const TASK_BOARDWALK = { name: `Straight to Boardwalk`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Straight_to_Boardwalk`, steps: [{ text: `Visit Davey Drydock at What's Up, Dock? on Lighthouse Lane`, sub: `Defeat 15 Cogs in Barnacle Boatyard` }, { text: `Return to Davey Drydock at What's Up, Dock? on Lighthouse Lane` }, { text: `Visit Linda Landlubber at Disembark! Tree Surgeons on Buccaneer Boulevard`, sub: `Defeat 7 Cogs on Buccaneer Boulevard` }, { text: `Deliver 50 Jellybeans to Linda Landlubber at Disembark! Tree Surgeons on Buccaneer Boulevard` }, { text: `Deliver Some Lumber to Davey Drydock at What's Up, Dock? on Lighthouse Lane` }], reward: `2560 XP - Boardwalk Nametag Font` };
const TASK_MATE_MAKEOVER = { name: `First Mate Makeover`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/First_Mate_Makeover`, steps: [{ text: `Visit Choppy McDougal at Blackbeard's Beauty Parlor on Buccaneer Boulevard`, sub: `Defeat 15 Lawbots in Barnacle Boatyard` }, { text: `Return to Choppy McDougal at Blackbeard's Beauty Parlor on Buccaneer Boulevard`, sub: `Collect A Treasure Chest from Treasure Dive on the Trolley` }, { text: `Return to Choppy McDougal at Blackbeard's Beauty Parlor on Buccaneer Boulevard` }], reward: `2496 XP - Wonky Nametag Font` };
const TASK_SWIM_KIWI = { name: `Swimming Kiwi`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Swimming_Kiwi`, steps: [{ text: `Visit Tumbles in the Barnacle Boatyard Playground`, sub: `Recover a Pair of Goggles from Conveyancers Anywhere` }, { text: `Return to Tumbles in the Barnacle Boatyard Playground` }, { text: `Visit Blisters McKee at The Reel Deal on Seaweed Street`, sub: `Defeat a Cog Building Anywhere` }, { text: `Return to Blisters McKee at The Reel Deal on Seaweed Street` }, { text: `Deliver Some Sunscreen to Tumbles in the Barnacle Boatyard Playground`, sub: `Go for a Swim Anywhere` }, { text: `Return to Tumbles in the Barnacle Boatyard Playground` }], reward: `2608 XP - Diving Profile Pose` };

const BB_ANCHOR: StreetShopData = {
  streetName: `Anchor Avenue`, neighborhood: `Barnacle Boatyard`,
  mainMap: `/icons/streets/Barnacle-Boatyard/Anchor-Avenue/anchor-avenue-main-map.webp`,
  shopsBase: `/icons/streets/Barnacle-Boatyard/Anchor-Avenue`,
  fisherman: { name: `Fisherman Freshie`, img: `FreshieBoatyard.webp` },
  shops: [
    { name: `Gone Fishin'`, owner: null, ownerImg: null, mapImg: `GoneFishin'MapLocation.webp`, shopImg: `GoneFishin'.webp`, tasks: [] },
    { name: `Seaside Seasaws`, owner: `Sir C. Saw`, ownerImg: `Sir_C._Saw.webp`, mapImg: `SeasideSeasawsMapLocation.webp`, shopImg: `SeasideSeasaws.webp`, tasks: [] },
    { name: `Be Pacific! Customer Support`, owner: `Helpful Harry`, ownerImg: `HelpfulHarry.webp`, mapImg: `BePacificMapLocation.webp`, shopImg: `BePacific.webp`, tasks: [TASK_MEET_MISTY] },
    { name: `I Sea Seafood`, owner: `Chef Shea`, ownerImg: `ChefShea.webp`, mapImg: `ISeaSeafoodMapLocation.webp`, shopImg: `ISeaSeafood.webp`, tasks: [] },
    { name: `School of Fish Tutoring`, owner: `Professor Pearl`, ownerImg: `ProfessorPearl.webp`, mapImg: `SchoolofFishMapLocation.webp`, shopImg: `SchoolofFish.webp`, tasks: [{ name: `First Day of School!`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#First_Day_of_School!`, steps: [{ text: `Visit Professor Pearl at School of Fish Tutoring on Anchor Avenue (242 XP, 8 JBS)`, sub: `Recover 3 Pencils from Pencil Pushers Anywhere` }, { text: `Return to Professor Pearl at School of Fish Tutoring on Anchor Avenue (242 XP, 8 JBS)`, sub: `Recover 2 Books from The Lawbots Anywhere` }, { text: `Return to Professor Pearl at School of Fish Tutoring on Anchor Avenue (242 XP, 8 JBS)` }, { text: `Visit Dover at Toon HQ (1696 XP, 58 JBS)` }], reward: `1696 XP - 58 JBS (final step)` }] },
    { name: `Goggle Defoggers`, owner: `Greggory Goggles`, ownerImg: `GreggoryGoggles.webp`, mapImg: `GoggleDefoggersMapLocation.webp`, shopImg: `GoggleDefoggers.webp`, tasks: [TASK_UNITE_1, TASK_I_CAN_SEE] },
    { name: `Island, You Land! Airplanes`, owner: `N.D. Skye`, ownerImg: `N.D.Skye.webp`, mapImg: `Island,YouLand!MapLocation.webp`, shopImg: `Island,YouLand!.webp`, tasks: [TASK_PROPELLERS] },
    { name: `Seacastle Contractors`, owner: `Crafty Clyde`, ownerImg: `CraftyClyde.webp`, mapImg: `SeacastleContractorsMapLocation.webp`, shopImg: `SeacastleContractors.webp`, tasks: [] },
    { name: `Manatee Shirts`, owner: `T. Shirley`, ownerImg: `T.Shirley.webp`, mapImg: `ManateeShirtsMapLocation.webp`, shopImg: `ManateeShirts.webp`, tasks: [] },
    { name: `Burger King Crabs`, owner: `Prince Beef`, ownerImg: `PrinceBeef.webp`, mapImg: `BurgerKingCrabsMapLocation.webp`, shopImg: `BurgerKingCrabs.webp`, tasks: [] },
    { name: `Sailor Don't Sail!`, owner: `Captain Cheesy`, ownerImg: `CaptainCheesy.webp`, mapImg: `SailorDon'tSail!MapLocation.webp`, shopImg: `SailorDon'tSail!.webp`, tasks: [] },
    { name: `Salty Sandy's Seriously Salty Seafood Shop`, owner: `Sandy Seasalt`, ownerImg: `SandySeasalt.webp`, mapImg: `SaltySandy'sSeriouslySaltySeafoodShopMapLocation.webp`, shopImg: `SaltySandy'sSeriouslySaltySeafoodShop.webp`, tasks: [] },
    { name: `Fish and Chips on Ships`, owner: `Chef Chip`, ownerImg: `ChefChip.webp`, mapImg: `FishandChipsonShipsMapLocation.webp`, shopImg: `FishandChipsonShips.webp`, tasks: [] },
    { name: `Pelican Package Company`, owner: `Postmaster Paul`, ownerImg: `PostmasterPaulBoatyard.webp`, mapImg: `PelicanPackageCompanyMapLocation.webp`, shopImg: `PelicanPackageCompany.webp`, tasks: [] },
    { name: `Sad Vacant Building`, owner: null, ownerImg: null, mapImg: `SadVacantBuildingMapLocation.webp`, shopImg: `SadVacantBuilding.webp`, tasks: [] },
    { name: `Swordfish Armor and Weaponry`, owner: `A.R. Ming`, ownerImg: `A.R.Ming.webp`, mapImg: `SwordfishArmorandWeaponryMapLocation.webp`, shopImg: `SwordfishArmorandWeaponry.webp`, tasks: [] },
    { name: `Flounder and Sink Ship Repair`, owner: `Ree Pare`, ownerImg: `ReePare.webp`, mapImg: `FlounderandSinkShipRepairMapLocation.webp`, shopImg: `FlounderandSinkShipRepair.webp`, tasks: [TASK_BIG_BINNACLE_BASH] },
    { name: `The Salty Spit-toon`, owner: `Reg`, ownerImg: `Reg.webp`, mapImg: `TheSaltySpit-toonMapLocation.webp`, shopImg: `TheSaltySpit-toon.webp`, tasks: [TASK_SPIT_TOON] },
  ],
};
STREET_SHOPS[`BB|Anchor Avenue`] = BB_ANCHOR;

const BB_BUCCANEER: StreetShopData = {
  streetName: `Buccaneer Boulevard`, neighborhood: `Barnacle Boatyard`,
  mainMap: `/icons/streets/Barnacle-Boatyard/Buccaneer-Boulevard/buccaneer-boulevard-main-map.webp`,
  shopsBase: `/icons/streets/Barnacle-Boatyard/Buccaneer-Boulevard`,
  fisherman: { name: `Fisherman Barney`, img: `Barney.webp` },
  shops: [
    { name: `Used Life Preservers`, owner: `Gary Glubglub`, ownerImg: `GaryGlubglub.webp`, mapImg: `UsedLifePreserversMapLocation.webp`, shopImg: `UsedLifePreservers.webp`, tasks: [] },
    { name: `Salmon Chanted Evening Formal Wear`, owner: `Fishy Frank`, ownerImg: `FishyFrank.webp`, mapImg: `SalmonChantedEveningFormalWearMapLocation.webp`, shopImg: `SalmonChantedEveningFormalWear.webp`, tasks: [TASK_SEA_LADS] },
    { name: `Poop Deck Gym`, owner: `Cal Estenicks`, ownerImg: `CalEstenicks.webp`, mapImg: `PoopDeckGymMapLocation.webp`, shopImg: `PoopDeckGym.webp`, tasks: [TASK_CONTACTING, TASK_UNITE_1] },
    { name: `Wet Suit Dry Cleaners`, owner: `Mrs. Starch`, ownerImg: `Mrs.Starch.webp`, mapImg: `WetSuitDryCleanersMapLocation.webp`, shopImg: `WetSuitDryCleaners.webp`, tasks: [] },
    { name: `Bait and Switches Electrical Shop`, owner: `Electra Eel`, ownerImg: `ElectraEel.webp`, mapImg: `BaitAndSwitchElectricalShopMapLocation.webp`, shopImg: `BaitAndSwitchElectricalShop.webp`, tasks: [] },
    { name: `Hook's Clock Repair`, owner: `Admiral Hook`, ownerImg: `AdmiralHook.webp`, mapImg: `Hook'sClockRepairMapLocation.webp`, shopImg: `Hook'sClockRepair.webp`, tasks: [TASK_BIG_BINNACLE_BASH] },
    { name: `From Fore to Aft`, owner: `Salty Stan`, ownerImg: `SaltyStan.webp`, mapImg: `FromForeToAftMapLocation.webp`, shopImg: `FromForeToAft.webp`, tasks: [TASK_BIG_BINNACLE_BASH] },
    { name: `Luff 'N Stuff`, owner: `Lisa Luff`, ownerImg: `LisaLuff.webp`, mapImg: `Luff'NStuffMapLocation.webp`, shopImg: `Luff'NStuff.webp`, tasks: [] },
    { name: `Every Little Bait`, owner: `Charlie Chum`, ownerImg: `CharlieChum.webp`, mapImg: `EveryLittleBaitMapLocation.webp`, shopImg: `EveryLittleBait.webp`, tasks: [] },
    { name: `Piano Tuna Works for Scale`, owner: `Eileen Overboard`, ownerImg: `EileenOverboard.webp`, mapImg: `PianoTunaWorksForScaleMapLocation.webp`, shopImg: `PianoTunaWorksForScale.webp`, tasks: [TASK_CONTACTING] },
    { name: `Billy Budd's Big Bargain Binnacle Barn`, owner: `Billy Budd`, ownerImg: `BillyBudd.webp`, mapImg: `BillyBudd'sBigBargainBinnacleBarnMapLocation.webp`, shopImg: `BillyBudd'sBigBargainBinnacleBarn.webp`, tasks: [TASK_BIG_BINNACLE_BASH] },
    { name: `Dime & Quarterdeck Bank`, owner: `Captain Carl`, ownerImg: `CaptainCarl.webp`, mapImg: `Dime&QuarterdeckBankMapLocation.webp`, shopImg: `Dime&QuarterdeckBank.webp`, tasks: [] },
    { name: `Squid Pro Quo Attorneys at Law`, owner: `Sheila Squid, Atty`, ownerImg: `SheilaSquidAtty.webp`, mapImg: `SquidProQuoAttorneysAtLawMapLocation.webp`, shopImg: `SquidProQuoAttorneysAtLaw.webp`, tasks: [] },
    { name: `Trim the Nail Boutique`, owner: null, ownerImg: null, mapImg: `TrimTheNailBoutiqueMapLocation.webp`, shopImg: `TrimTheNailBoutique.webp`, tasks: [] },
    { name: `Yacht's All, Folks!`, owner: `Captain Yucks`, ownerImg: `CaptainYucks.webp`, mapImg: `Yacht'sAll,FolksMapLocation.webp`, shopImg: `Yacht'sAll,Folks.webp`, tasks: [] },
    { name: `Blackbeard's Beauty Parlor`, owner: `Choppy McDougal`, ownerImg: `ChoppyMcDougal.webp`, mapImg: `Blackbeard'sBeautyParlorMapLocation.webp`, shopImg: `Blackbeard'sBeautyParlor.webp`, tasks: [TASK_MATE_MAKEOVER] },
    { name: `Out to See Optics`, owner: `Doctor Squall`, ownerImg: `DoctorSquall.webp`, mapImg: `OutToSeeOpticsMapLocation.webp`, shopImg: `OutToSeeOptics.webp`, tasks: [TASK_I_CAN_SEE] },
    { name: `Soles Repaired While U Wait`, owner: `Flappy Docksplinter`, ownerImg: `FlappyDocksplinter.webp`, mapImg: `SolesRepairedWhileUWaitMapLocation.webp`, shopImg: `SolesRepairedWhileUWait.webp`, tasks: [TASK_I_CAN_SEE, TASK_CAPTAIN] },
    { name: `Disembark! Tree Surgeons`, owner: `Linda Landlubber`, ownerImg: `LindaLandlubber.webp`, mapImg: `Disembark!TreeSurgeonsMapLocation.webp`, shopImg: `Disembark!TreeSurgeons.webp`, tasks: [TASK_CAPTAIN, TASK_BOARDWALK] },
  ],
};
STREET_SHOPS[`BB|Buccaneer Boulevard`] = BB_BUCCANEER;

const BB_LIGHTHOUSE: StreetShopData = {
  streetName: `Lighthouse Lane`, neighborhood: `Barnacle Boatyard`,
  mainMap: `/icons/streets/Barnacle-Boatyard/Lighthouse-Lane/lighthouse-lane-main-map.webp`,
  shopsBase: `/icons/streets/Barnacle-Boatyard/Lighthouse-Lane`,
  fisherman: { name: `Fisherman Shane`, img: `Shane.webp` },
  shops: [
    { name: `Lost and Flounder`, owner: `Fred Flounder`, ownerImg: `FredFlounder.webp`, mapImg: `LostAndFlounderMapLocation.webp`, shopImg: `LostAndFlounder.webp`, tasks: [{ name: `Butter Flippers`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Butter_Flippers`, steps: [{ text: `Visit Fred Flounder at Lost and Flounder on Lighthouse Lane (178 XP, 7 JBS)`, sub: `Recover 3 Lost Items from The Cogs in Barnacle Boatyard` }, { text: `Return to Fred Flounder at Lost and Flounder on Lighthouse Lane (178 XP, 7 JBS)`, sub: `Recover A Lost and Found Box from The Cogs in Barnacle Boatyard` }, { text: `Return to Fred Flounder at Lost and Flounder on Lighthouse Lane (1425 XP, 57 JBS)` }, { text: `Visit Wade at Toon HQ (288 XP, 10 JBS)` }], reward: `1425 XP - 57 JBS (step 3)` }] },
    { name: `Seagull Statue Store`, owner: `Cindy Splat`, ownerImg: `CindySplat.webp`, mapImg: `SeagullStatueStoreMapLocation.webp`, shopImg: `SeagullStatueStore.webp`, tasks: [] },
    { name: `Kelp Around the House`, owner: `Shelly Seaweed`, ownerImg: `ShellySeaweed.webp`, mapImg: `KelpAroundTheHouseMapLocation.webp`, shopImg: `KelpAroundTheHouse.webp`, tasks: [] },
    { name: `Nautical But Nice`, owner: `Seafoam`, ownerImg: `Seafoam.webp`, mapImg: `NauticalButNiceMapLocation.webp`, shopImg: `NauticalButNice.webp`, tasks: [] },
    { name: `Melville's Massive Mizzenmast Mart`, owner: `Melville`, ownerImg: `Melville.webp`, mapImg: `Melville'sMassiveMizzenmastMartMapLocation.webp`, shopImg: `Melville'sMassiveMizzenmastMart.webp`, tasks: [TASK_CAPTAIN] },
    { name: `Tackle Box Lunches`, owner: `Ted Tackle`, ownerImg: `TedTackle.webp`, mapImg: `TackleBoxLunchesMapLocation.webp`, shopImg: `TackleBoxLunches.webp`, tasks: [] },
    { name: `Mussel Beach Gymnasium`, owner: `Svetlana`, ownerImg: `Svetlana.webp`, mapImg: `MusselBeachGymnasiumMapLocation.webp`, shopImg: `MusselBeachGymnasium.webp`, tasks: [] },
    { name: `Cap Size Hat Store`, owner: `Topsy Turvey`, ownerImg: `TopsyTurvey.webp`, mapImg: `CapSizeHatStoreMapLocation.webp`, shopImg: `CapSizeHatStore.webp`, tasks: [{ name: `Someone's Been Drinking Saltwater...`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Someone%27s_Been_Drinking_Saltwater...`, steps: [{ text: `Visit Ahab at Ahab's Prefab Sea Crab Center on Seaweed Street (288 XP, 10 JBS)`, sub: `Defeat 6 Cogs in Barnacle Boatyard` }, { text: `Return to Ahab at Ahab's Prefab Sea Crab Center on Seaweed Street (288 XP, 10 JBS)` }, { text: `Visit Topsy Turvey at the Cap Size Hat Store on Lighthouse Lane (288 XP, 10 JBS)`, sub: `Recover Some Suit Thread from Double Talkers Anywhere` }, { text: `Return to Topsy Turvey at the Cap Size Hat Store on Lighthouse Lane (1727 XP, 60 JBS, Pirate Hat)` }, { text: `Visit Wade at Toon HQ (242 XP, 8 JBS)` }], reward: `1727 XP - 60 JBS - Pirate Hat` }] },
    { name: `Keel Deals`, owner: `Ethan Keel`, ownerImg: `EthanKeel.webp`, mapImg: `KeelDealsMapLocation.webp`, shopImg: `KeelDeals.webp`, tasks: [] },
    { name: `Knots So Fast`, owner: `William Wake`, ownerImg: `WilliamWake.webp`, mapImg: `KnotsSoFastMapLocation.webp`, shopImg: `KnotsSoFast.webp`, tasks: [] },
    { name: `Rusty Buckets`, owner: `Rusty Ralph`, ownerImg: `RustyRalph.webp`, mapImg: `RustyBucketsMapLocation.webp`, shopImg: `RustyBuckets.webp`, tasks: [] },
    { name: `Anchor Management`, owner: `Doctor Drift`, ownerImg: `DoctorDrift.webp`, mapImg: `AnchorManagementMapLocation.webp`, shopImg: `AnchorManagement.webp`, tasks: [] },
    { name: `What's Canoe With You?`, owner: `Wilma Wobble`, ownerImg: `WilmaWobble.webp`, mapImg: `What'sCanoeWithYouMapLocation.webp`, shopImg: `What'sCanoeWithYou.webp`, tasks: [] },
    { name: `Pier Pressure Plumbing`, owner: `Paula Pylon`, ownerImg: `PaulaPylon.webp`, mapImg: `PierPressurePlumbingMapLocation.webp`, shopImg: `PierPressurePlumbing.webp`, tasks: [] },
    { name: `The Yo Ho Stop and Go`, owner: `Captain Jack Harrow`, ownerImg: `CaptainJackHarrow.webp`, mapImg: `TheYoHoStopAndGoMapLocation.webp`, shopImg: `TheYoHoStopAndGo.webp`, tasks: [] },
    { name: `What's Up, Dock?`, owner: `Davey Drydock`, ownerImg: `DaveyDrydock.webp`, mapImg: `What'sUpDockMapLocation.webp`, shopImg: `What'sUpDock.webp`, tasks: [TASK_BOARDWALK] },
    { name: `The Lighthouse`, owner: `Barnacle Bessie`, ownerImg: `BarnacleBessie.webp`, mapImg: `TheLighthouseMapLocation.webp`, shopImg: `TheLighthouse.webp`, tasks: [{ name: `Oh, Barnacles!`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Oh,_Barnacles!`, steps: [{ text: `Visit Flippy at Toon Hall in Toontown Central (178 XP, 7 JBS)` }, { text: `Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (178 XP, 7 JBS)` }, { text: `Visit River at Toon HQ (178 XP, 7 JBS)` }, { text: `Visit Wade at Toon HQ (178 XP, 7 JBS)` }], reward: `178 XP - 7 JBS per step` }, TASK_IMPORTANT, TASK_UNITE_1, TASK_CHARTING, TASK_I_CAN_SEE, TASK_CAPTAIN, { name: `The Office`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#The_Office`, steps: [{ text: `Visit Barnacle Bessie at The Lighthouse on Lighthouse Lane (107 XP, 4 JBS)`, sub: `Defeat the Land Acquisition Architect on Anchor Avenue` }, { text: `Return to Barnacle Bessie at The Lighthouse on Lighthouse Lane (1605 XP, 54 JBS, Ye Olde Toontowne Profile Background)` }], reward: `1605 XP - 54 JBS - Ye Olde Toontowne Profile Background` }] },
    { name: `This Transom Man Custom-Tailored Suits`, owner: `Porter Hole`, ownerImg: `PorterHole.webp`, mapImg: `ThisTransomManMapLocation.webp`, shopImg: `ThisTransomMan.webp`, tasks: [] },
    { name: `Docker's Diner`, owner: `Dinah Docker`, ownerImg: `DinahDocker.webp`, mapImg: `Docker'sDinerMapLocation.webp`, shopImg: `Docker'sDiner.webp`, tasks: [] },
    { name: `Seven Seas Cafe`, owner: `Ted Calm`, ownerImg: `TedCalm.webp`, mapImg: `SevenSeasCafeMapLocation.webp`, shopImg: `SevenSeasCafe.webp`, tasks: [] },
    { name: `Hook, Line, and Sinker Prank Shop`, owner: `Whoopie Cushion`, ownerImg: `WhoopieCushion.webp`, mapImg: `HookLineAndSinkerPrankShopMapLocation.webp`, shopImg: `HookLineAndSinkerPrankShop.webp`, tasks: [] },
    { name: `King Neptoon's Cannery`, owner: `Stinky Ned`, ownerImg: `StinkyNed.webp`, mapImg: `KingNeptoon'sCanneryMapLocation.webp`, shopImg: `KingNeptoon'sCannery.webp`, tasks: [] },
    { name: `Dog Paddles`, owner: `Ned Setter`, ownerImg: `NedSetter.webp`, mapImg: `DogPaddlesMapLocation.webp`, shopImg: `DogPaddles.webp`, tasks: [] },
    { name: `The Clam Bake Diner`, owner: `Pearl Diver`, ownerImg: `PearlDiver.webp`, mapImg: `TheClamBakeDinerMapLocation.webp`, shopImg: `TheClamBakeDiner.webp`, tasks: [] },
    { name: `Wholly Mackerel! Fish Market`, owner: `Felicia Chips`, ownerImg: `FeliciaChips.webp`, mapImg: `WhollyMackerelMapLocation.webp`, shopImg: `WhollyMackerel.webp`, tasks: [] },
    { name: `Claggart's Clever Clovis Closet`, owner: `Claggart`, ownerImg: `Claggart.webp`, mapImg: `Claggart'sCleverClovisClosetMapLocation.webp`, shopImg: `Claggart'sCleverClovisCloset.webp`, tasks: [] },
    { name: `Rudderly Ridiculous!`, owner: `Rudy Rudder`, ownerImg: `RudyRudder.webp`, mapImg: `RudderlyRidiculousMapLocation.webp`, shopImg: `RudderlyRidiculous.webp`, tasks: [] },
    { name: `Alice's Ballast Palace`, owner: `Alice`, ownerImg: `Alice.webp`, mapImg: `Alice'sBallastPalaceMapLocation.webp`, shopImg: `Alice'sBallastPalace.webp`, tasks: [] },
  ],
};
STREET_SHOPS[`BB|Lighthouse Lane`] = BB_LIGHTHOUSE;

const BB_SEAWEED: StreetShopData = {
  streetName: `Seaweed Street`, neighborhood: `Barnacle Boatyard`,
  mainMap: `/icons/streets/Barnacle-Boatyard/Seaweed-Street/seaweed-street-main-map.webp`,
  shopsBase: `/icons/streets/Barnacle-Boatyard/Seaweed-Street`,
  fisherman: { name: `Fisherman Reed`, img: `FishermanReed.webp` },
  shops: [
    { name: `That's a Moray!`, owner: `Emily Eel`, ownerImg: `EmilyEel.webp`, mapImg: `That'sAMorayMapLocation.webp`, shopImg: `That'sAMoray.webp`, tasks: [] },
    { name: `Squid's Seaweed`, owner: `Sid Squid`, ownerImg: `SidSquid.webp`, mapImg: `Squid'sSeaweedMapLocation.webp`, shopImg: `Squid'sSeaweed.webp`, tasks: [] },
    { name: `Good Luck Horseshoe Crabs`, owner: `Coral Reef`, ownerImg: `CoralReef.webp`, mapImg: `GoodLuckHorseshoeCrabsMapLocation.webp`, shopImg: `GoodLuckHorseshoeCrabs.webp`, tasks: [] },
    { name: `All for Nautical`, owner: `Shep Ahoy`, ownerImg: `ShepAhoy.webp`, mapImg: `AllForNauticalMapLocation.webp`, shopImg: `AllForNautical.webp`, tasks: [] },
    { name: `The Reel Deal`, owner: `Blisters McKee`, ownerImg: `BlistersMcKee.webp`, mapImg: `TheReelDealMapLocation.webp`, shopImg: `TheReelDeal.webp`, tasks: [TASK_SWIM_KIWI] },
    { name: `Duck's Back Water Company`, owner: `Carla Canal`, ownerImg: `CarlaCanal.webp`, mapImg: `DucksBackWaterCompanyMapLocation.webp`, shopImg: `DucksBackWaterCompany.webp`, tasks: [] },
    { name: `Run Aground Taxi Service`, owner: `Brian Beachead`, ownerImg: `BrianBeachead.webp`, mapImg: `RunAgroundTaxiServiceMapLocation.webp`, shopImg: `RunAgroundTaxiService.webp`, tasks: [] },
    { name: `Be More Pacific Ocean Notions`, owner: `Pacific Tim`, ownerImg: `PacificTim.webp`, mapImg: `BeMorePacificOceanNotionsMapLocation.webp`, shopImg: `BeMorePacificOceanNotions.webp`, tasks: [] },
    { name: `This Oar That`, owner: `Heave Ho`, ownerImg: `HeaveHo.webp`, mapImg: `ThisOarThatMapLocation.webp`, shopImg: `ThisOarThat.webp`, tasks: [] },
    { name: `Mermaid Swimwear`, owner: `Cyren`, ownerImg: `Cyren.webp`, mapImg: `MermaidSwimwearMapLocation.webp`, shopImg: `MermaidSwimwear.webp`, tasks: [] },
    { name: `Art's Smart Chart Mart`, owner: `Art`, ownerImg: `Art.webp`, mapImg: `Art'sSmartChartMartMapLocation.webp`, shopImg: `Art'sSmartChartMart.webp`, tasks: [TASK_CHARTING] },
    { name: `Reel 'Em Inn`, owner: `Rod Reel`, ownerImg: `RodReel.webp`, mapImg: `Reel'EmInMapLocation.webp`, shopImg: `Reel'EmIn.webp`, tasks: [] },
    { name: `Able-Bodied Gym`, owner: `Rocky Shores`, ownerImg: `RockyShores.webp`, mapImg: `Able-BodiedGymMapLocation.webp`, shopImg: `Able-BodiedGym.webp`, tasks: [] },
    { name: `Deep-Sea Diner`, owner: `Dinah Down`, ownerImg: `DinahDown.webp`, mapImg: `Deep-SeaDinerMapLocation.webp`, shopImg: `Deep-SeaDiner.webp`, tasks: [] },
    { name: `Barnacle Bargains`, owner: `Barnacle Barbara`, ownerImg: `BarnacleBarbara.webp`, mapImg: `BarnacleBargainsMapLocation.webp`, shopImg: `BarnacleBargains.webp`, tasks: [] },
    { name: `Windjammers and Jellies`, owner: `Gusty Kate`, ownerImg: `GustyKate.webp`, mapImg: `WindjammersAndJelliesMapLocation.webp`, shopImg: `WindjammersAndJellies.webp`, tasks: [] },
    { name: `Root Beer Afloats`, owner: `Bonzo Bilgepump`, ownerImg: `BonzoBilgepump.webp`, mapImg: `RootBeerAfloatsMapLocation.webp`, shopImg: `RootBeerAfloats.webp`, tasks: [] },
    { name: `Gifts With a Porpoise`, owner: `Dante Dolphin`, ownerImg: `DanteDolphin.webp`, mapImg: `GiftsWithAPorpoiseMapLocation.webp`, shopImg: `GiftsWithAPorpoise.webp`, tasks: [] },
    { name: `Peanut Butter and Jellyfish`, owner: `Toby Tonguestinger`, ownerImg: `TobyTonguestinger.webp`, mapImg: `PeanutButterandJellyfishMapLocation.webp`, shopImg: `PeanutButterandJellyfish.webp`, tasks: [] },
    { name: `Sails for Sale`, owner: `Wynn Bag`, ownerImg: `WynnBag.webp`, mapImg: `SailsForSaleMapLocation.webp`, shopImg: `SailsForSale.webp`, tasks: [] },
    { name: `Wok the Plank Chinese Food`, owner: `Gang Wei`, ownerImg: `GangWei.webp`, mapImg: `WokThePlankChineseFoodMapLocation.webp`, shopImg: `WokThePlankChineseFood.webp`, tasks: [] },
    { name: `Ahab's Prefab Sea Crab Center`, owner: `Ahab`, ownerImg: `Ahab.webp`, mapImg: `Ahab'sPrefabSeaCrabCenterMapLocation.webp`, shopImg: `Ahab'sPrefabSeaCrabCenter.webp`, tasks: [{ name: `Someone's Been Drinking Saltwater...`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Barnacle_Boatyard_Tasks#Someone%27s_Been_Drinking_Saltwater...`, steps: [{ text: `Visit Ahab at Ahab's Prefab Sea Crab Center on Seaweed Street (288 XP, 10 JBS)`, sub: `Defeat 6 Cogs in Barnacle Boatyard` }, { text: `Return to Ahab at Ahab's Prefab Sea Crab Center on Seaweed Street (288 XP, 10 JBS)` }, { text: `Visit Topsy Turvey at the Cap Size Hat Store on Lighthouse Lane (288 XP, 10 JBS)`, sub: `Recover Some Suit Thread from Double Talkers Anywhere` }, { text: `Return to Topsy Turvey at the Cap Size Hat Store on Lighthouse Lane (1727 XP, 60 JBS, Pirate Hat)` }, { text: `Visit Wade at Toon HQ (242 XP, 8 JBS)` }], reward: `1727 XP - 60 JBS - Pirate Hat` }] },
    { name: `Buoys and Gulls Nursery School`, owner: `Professor Plank`, ownerImg: `ProfessorPlank.webp`, mapImg: `BuoysAndGullsNurserySchoolMapLocation.webp`, shopImg: `BuoysAndGullsNurserySchool.webp`, tasks: [] },
  ],
};
STREET_SHOPS[`BB|Seaweed Street`] = BB_SEAWEED;

/* ─── Ye Olde Toontowne shared tasks ──────────────────────────── */
const TASK_EXECUTING_JJ = { name: `Executing The Executives`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Executing_The_Executives`, steps: [
  { text: `Visit Al Kemical at Toon HQ (594 XP, 17 JBS)` },
  { text: `Visit Sir Prysin at Demon Slayers on Wizard Way (594 XP, 17 JBS)` },
  { text: `Visit Jongleur Jocelyn at Jesters and Jousters on Knight Knoll (594 XP, 17 JBS)` },
  { text: `Return to Jongleur Jocelyn at Jesters and Jousters on Knight Knoll (594 XP, 17 JBS)`, sub: `Recover 3 Juggling Sticks from The Cogs in Ye Olde Toontowne` },
  { text: `Visit Mad Ernage at Brain Over Bronze on Wizard Way (594 XP, 17 JBS)` },
  { text: `Return to Jongleur Jocelyn (4157 XP, 117 JBS, Conquistador Helmet)`, sub: `Defeat 3 Level 5+ Cogs Anywhere` },
], reward: `4157 XP - 117 JBS - Conquistador Helmet` };
const TASK_COG_BASH = { name: `Ye Olde Cog Bash!`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Ye_Olde_Cog_Bash!`, steps: [
  { text: `Visit Patsy at The Holy Grail & Other Useless Dinnerware on Knight Knoll (392 XP, 11 JBS)` },
  { text: `Visit Moneyer Mason at the Half-Bean Bank on Knight Knoll (392 XP, 11 JBS)`, sub: `Defeat 5 Sellbots Anywhere` },
  { text: `Visit Merlin Ambrice at Rayvenward School of Magical Arts on Wizard Way (392 XP, 11 JBS)`, sub: `Defeat 6 Cashbots Anywhere` },
  { text: `Visit Marry Paston at the Platemail Post Office on Noble Nook (3918 XP, 111 JBS)`, sub: `Defeat 6 Lawbots Anywhere` },
  { text: `Visit Steamed Bams at The Dungeon Luncheon on Noble Nook (885 XP, 25 JBS)`, sub: `Defeat 7 Bossbots Anywhere` },
  { text: `Visit Enna Chantment at Toon HQ (4424 XP, 125 JBS)`, sub: `Defeat 7 Boardbots Anywhere` },
], reward: `4424 XP - 125 JBS (final step)` };
const TASK_PAGE_STUDYING = { name: `Page Studying 101`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Page_Studying_101`, steps: [
  { text: `Visit Archduke Arthur at Arthur's Barns & Nobles on Knight Knoll` },
  { text: `Return to Archduke Arthur at Arthur's Barns & Nobles on Knight Knoll`, sub: `Defeat 30 Level 6+ Cogs Anywhere` },
  { text: `Return to Archduke Arthur at Arthur's Barns & Nobles on Knight Knoll`, sub: `Defeat 20 Level 7+ Cogs Anywhere` },
], reward: `6148 XP - Knight Outfit - 300 JBS` };
const TASK_NOT_SO_TALL = { name: `Not-So-Tall Tales`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Not-So-Tall_Tales`, steps: [
  { text: `Visit Thea Troubadour at Troubadour's Tall Tales on Knight Knoll` },
  { text: `Return to Thea Troubadour at Troubadour's Tall Tales on Knight Knoll`, sub: `Defeat 15 Micromanagers Anywhere` },
], reward: `6032 XP - Small Head Cheesy Effect - 300 JBS` };
const TASK_MIDLIFE = { name: `Midlife Crisis`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Midlife_Crisis`, steps: [
  { text: `Visit Youthful Yannis at Middle Age Crisis Center on Wizard Way` },
  { text: `Return to Youthful Yannis at Middle Age Crisis Center on Wizard Way`, sub: `Defeat 10 Level 5+ Cogs Anywhere` },
  { text: `Return to Youthful Yannis at Middle Age Crisis Center on Wizard Way`, sub: `Defeat 5 Double Talkers Anywhere` },
  { text: `Return to Youthful Yannis (Poetic Nametag Awarded)`, sub: `Deliver a Level 5 Gag to Youthful Yannis` },
  { text: `Return to Youthful Yannis at Middle Age Crisis Center on Wizard Way`, sub: `Defeat 2 Three+ Story Cog Buildings Anywhere` },
  { text: `Return to Youthful Yannis at Middle Age Crisis Center on Wizard Way`, sub: `Defeat 10 Level 5+ Cogs Anywhere` },
  { text: `Return to Youthful Yannis at Middle Age Crisis Center on Wizard Way`, sub: `Defeat 5 Bloodsuckers Anywhere` },
], reward: `6224 XP - Transparent Cheesy Effect - Poetic Nametag Font - 300 JBS` };
const TASK_GOLDEN_PENNY = { name: `The Golden Penny`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/The_Golden_Penny`, steps: [
  { text: `Visit Tumbles in the Ye Olde Toontowne Playground` },
  { text: `Return to Tumbles in the YOTT Playground`, sub: `Recover A Golden Penny from a Cashbot Cog Building Anywhere` },
  { text: `Deliver A Golden Penny to Al Bumbledorf at Elder Headquarters in the YOTT Playground` },
  { text: `Deliver A Monocle to Al Bumbledorf at Elder Headquarters in the YOTT Playground`, sub: `Recover A Monocle from Shark Watchers Anywhere` },
  { text: `Deliver A Gold Penny to Merlin Ambrice at Rayvenward - School of Magical Arts on Wizard Way` },
  { text: `Return to Merlin Ambrice at Rayvenward - School of Magical Arts on Wizard Way`, sub: `Defeat 10 Cashbots in Ye Olde Toontowne` },
  { text: `Deliver A Chocolate Coin to Tumbles in the Ye Olde Toontowne Playground` },
], reward: `6354 XP - Casting Profile Pose - 300 JBS` };
const TASK_ADVENTURER = { name: `Used To Be An Adventurer`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Used_To_Be_An_Adventurer`, steps: [
  { text: `Visit Ariel Septim VII at Arrow to the Knee on Noble Nook` },
  { text: `Return to Ariel Septim VII at Arrow to the Knee on Noble Nook`, sub: `Recover 5 Strong Wires from The Cogs in Ye Olde Toontowne` },
  { text: `Return to Ariel Septim VII at Arrow to the Knee on Noble Nook`, sub: `Defeat 15 Level 6+ Cogs in Ye Olde Toontowne` },
  { text: `Return to Ariel Septim VII at Arrow to the Knee on Noble Nook`, sub: `Recover A Bandage from Spin Doctors Anywhere` },
], reward: `6176 XP - Teleport Access to Ye Olde Toontowne - 300 JBS` };
const TASK_DUNGEON_DUTY = { name: `Dungeon Duty`, type: `Sidetask`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Dungeon_Duty`, steps: [
  { text: `Visit Doyle N. Trouble in The Dungeon (YOTT Playground)` },
  { text: `Return to Doyle N. Trouble in The Dungeon`, sub: `Recover 5 Money Bags from Money Bags Anywhere` },
  { text: `Visit Steamed Bams at The Dungeon Luncheon on Noble Nook` },
  { text: `Return to Steamed Bams at The Dungeon Luncheon on Noble Nook`, sub: `Defeat 20 Level 5+ Cogs in Ye Olde Toontowne` },
  { text: `Deliver Some Food to Doyle N. Trouble in The Dungeon` },
  { text: `Return to Doyle N. Trouble in The Dungeon`, sub: `Recover Some Mechanical Pieces from a Cog Building in Ye Olde Toontowne` },
], reward: `12,128 XP - 600 JBS` };

const YOTT_KNIGHT: StreetShopData = {
  streetName: `Knight Knoll`, neighborhood: `Ye Olde Toontowne`,
  mainMap: `/icons/streets/Ye-Olde-Toontowne/Knight-Knoll/knight-knoll-main-map.webp`,
  shopsBase: `/icons/streets/Ye-Olde-Toontowne/Knight-Knoll`,
  shops: [
    { name: `Weapons in a Fortnight`, owner: `Epoch James`, ownerImg: `EpochJames.webp`, mapImg: `WeaponsInAFortnightMapLocation.webp`, shopImg: `WeaponsInAFortnight.webp`, tasks: [] },
    { name: `Cheese Steak Jimmy's`, owner: `Jimmy Wallace`, ownerImg: `JimmyWallace.webp`, mapImg: `CheeseSteakJimmy'sMapLocation.webp`, shopImg: `CheeseSteakJimmy's.webp`, tasks: [] },
    { name: `Killer Hares Barber Shop`, owner: `Barber Caerbannog`, ownerImg: `BarberCaerbannog.webp`, mapImg: `KillerHaresBarberShopMapLocation.webp`, shopImg: `KillerHaresBarberShop.webp`, tasks: [] },
    { name: `Burn Them at the Steak!`, owner: `Steward Selina`, ownerImg: `StewardSelina.webp`, mapImg: `BurnThemAtTheSteakMapLocation.webp`, shopImg: `BurnThemAtTheSteak.webp`, tasks: [] },
    { name: `Witches Get Stitches`, owner: `Constable Conrad`, ownerImg: `ConstableConrad.webp`, mapImg: `WitchesGetStitchesMapLocation.webp`, shopImg: `WitchesGetStitches.webp`, tasks: [] },
    { name: `Crossbow Puzzles`, owner: `Little Prince`, ownerImg: `LittlePrince.webp`, mapImg: `CrossbowPuzzlesMapLocation.webp`, shopImg: `CrossbowPuzzles.webp`, tasks: [] },
    { name: `Jesters and Jousters`, owner: `Jongleur Jocelyn`, ownerImg: `JongleurJocelyn.webp`, mapImg: `JestersAndJoustersMapLocation.webp`, shopImg: `JestersAndJousters.webp`, tasks: [TASK_EXECUTING_JJ] },
    { name: `Troubadour's Tall Tales`, owner: `Thea Troubadour`, ownerImg: `TheaTroubadour.webp`, mapImg: `Troubadour'sTallTalesMapLocation.webp`, shopImg: `Troubadour'sTallTales.webp`, tasks: [TASK_NOT_SO_TALL] },
    { name: `Serf's Up!`, owner: `Serf Simon`, ownerImg: `SerfSimon.webp`, mapImg: `Serf'sUpMapLocation.webp`, shopImg: `Serf'sUp.webp`, tasks: [] },
    { name: `Dungeons, Dragons, and Donjons`, owner: `Nichola Nomad`, ownerImg: `NicholaNomad.webp`, mapImg: `DungeonsDragonsAndDonjonsMapLocation.webp`, shopImg: `DungeonsDragonsAndDonjons.webp`, tasks: [] },
    { name: `Frederick's Fletchings and Bows`, owner: `Fletcher Frederick`, ownerImg: `FletcherFrederick.webp`, mapImg: `Frederick'sFletchingsAndBowsMapLocation.webp`, shopImg: `Frederick'sFletchingsAndBows.webp`, tasks: [] },
    { name: `Kings, Queens, and Aces`, owner: `Joker Juliana`, ownerImg: `JokerJuliana.webp`, mapImg: `KingsQueensAndAcesMapLocation.webp`, shopImg: `KingsQueensAndAces.webp`, tasks: [] },
    { name: `Hilt and Blade Weaponry`, owner: `Blacksmith Estoc`, ownerImg: `BlacksmithEstoc.webp`, mapImg: `HiltAndBladeWeaponryMapLocation.webp`, shopImg: `HiltAndBladeWeaponry.webp`, tasks: [{ name: `Executing The Executives (cont.)`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Executing_The_Executives`, steps: [{ text: `Visit Blacksmith Estoc at Hilt & Blade Weaponry on Knight Knoll (1790 XP, 50 JBS)` }, { text: `Return to Blacksmith Estoc at Hilt & Blade Weaponry on Knight Knoll (5371 XP, 150 JBS, Pirate Sword)`, sub: `Recover Some Sword Materials from A Cog Building in Ye Olde Toontowne` }], reward: `5371 XP - 150 JBS - Pirate Sword` }] },
    { name: `The Holy Grail & Other Useless Dinnerware`, owner: `Patsy`, ownerImg: `Patsy.webp`, mapImg: `TheHolyGrailMapLocation.webp`, shopImg: `TheHolyGrail.webp`, tasks: [TASK_COG_BASH] },
    { name: `Arthur's Barns and Nobles`, owner: `Archduke Arthur`, ownerImg: `ArchdukeArthur.webp`, mapImg: `Arthur'sBarnsAndNoblesMapLocation.webp`, shopImg: `Arthur'sBarnsAndNobles.webp`, tasks: [TASK_PAGE_STUDYING] },
    { name: `Half-Bean Bank`, owner: `Moneyer Mason`, ownerImg: `MoneyerMason.webp`, mapImg: `Half-BeanBankMapLocation.webp`, shopImg: `Half-BeanBank.webp`, tasks: [] },
    { name: `Installation Wizard`, owner: `Marty Python`, ownerImg: `MartyPython.webp`, mapImg: `InstallationWizardMapLocation.webp`, shopImg: `InstallationWizard.webp`, tasks: [] },
    { name: `Perpetual Stew - For You to Chew`, owner: `Peasant Peter`, ownerImg: `PeasantPeter.webp`, mapImg: `PerpetualStewMapLocation.webp`, shopImg: `PerpetualStew.webp`, tasks: [] },
    { name: `Enchantments and Spellbinding`, owner: `Tim the Enchanter`, ownerImg: `TimTheEnchanter.webp`, mapImg: `EnchantmentsAndSpellbindingMapLocation.webp`, shopImg: `EnchantmentsAndSpellbinding.webp`, tasks: [] },
    { name: `Camel-lot`, owner: `King Arture`, ownerImg: `KingArture.webp`, mapImg: `Camel-lotMapLocation.webp`, shopImg: `Camel-lot.webp`, tasks: [] },
  ],
};
STREET_SHOPS[`YOTT|Knight Knoll`] = YOTT_KNIGHT;

const YOTT_NOBLE: StreetShopData = {
  streetName: `Noble Nook`, neighborhood: `Ye Olde Toontowne`,
  mainMap: `/icons/streets/Ye-Olde-Toontowne/Noble-Nook/noble-nook-main-map.webp`,
  shopsBase: `/icons/streets/Ye-Olde-Toontowne/Noble-Nook`,
  shops: [
    { name: `Tailor's Tales`, owner: `Allan A. Dale`, ownerImg: `AllanA.Dale.webp`, mapImg: `Tailor'sTalesMapLocation.webp`, shopImg: `Tailor'sTales.webp`, tasks: [] },
    { name: `Taken for Granite`, owner: `Dagger`, ownerImg: `Dagger.webp`, mapImg: `TakenForGraniteMapLocation.webp`, shopImg: `TakenForGranite.webp`, tasks: [] },
    { name: `The Dungeon Luncheon`, owner: `Steamed Bams`, ownerImg: `SteamedBams.webp`, mapImg: `TheDungeonLuncheonMapLocation.webp`, shopImg: `TheDungeonLuncheon.webp`, tasks: [TASK_COG_BASH, TASK_DUNGEON_DUTY] },
    { name: `Bites for Knights`, owner: `Chef Lambert`, ownerImg: `ChefLambert.webp`, mapImg: `BitesForKnightsMapLocation.webp`, shopImg: `BitesForKnights.webp`, tasks: [] },
    { name: `A-Fort-Able Housing`, owner: `Gentry Gary`, ownerImg: `GentryGary.webp`, mapImg: `A-Fort-AbleHousingMapLocation.webp`, shopImg: `A-Fort-AbleHousing.webp`, tasks: [{ name: `Ye Olde Restoration Project`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Ye_Olde_Restoration_Project`, steps: [{ text: `Visit Magus Bizzy at Witchcraft? Hobby Helpers on Wizard Way (402 XP, 11 JBS)` }, { text: `Visit Gentry Gary at A-FORT-Able Housing on Noble Nook (402 XP, 11 JBS)` }, { text: `Return to Gentry Gary (402 XP, 11 JBS)`, sub: `Defeat 5 Level 5+ Cogs Anywhere` }, { text: `Visit Cleric Cecily at Dark Ages - Sleep Studies on Noble Nook (402 XP, 11 JBS)` }, { text: `Return 8 Wiring to Gentry Gary (402 XP, 11 JBS)`, sub: `Recover 8 Wiring from The Cogs Anywhere` }], reward: `Part of Ye Olde Restoration Project mainline chain` }] },
    { name: `Webster's Olde Dictionaries`, owner: `Webster`, ownerImg: `Webster.webp`, mapImg: `Webster'sOldeDictionariesMapLocation.webp`, shopImg: `Webster'sOldeDictionaries.webp`, tasks: [] },
    { name: `Round Table Eatery`, owner: `Hind Harry`, ownerImg: `HindHenry.webp`, mapImg: `RoundTableEateryMapLocation.webp`, shopImg: `RoundTableEatery.webp`, tasks: [] },
    { name: `Caltrops Gumdrops`, owner: `Pantler Peter`, ownerImg: `PantlerPeter.webp`, mapImg: `CaltropsGumdropsMapLocation.webp`, shopImg: `CaltropsGumdrops.webp`, tasks: [] },
    { name: `Trebuchet Buffet`, owner: `Friar Richard`, ownerImg: `FriarRichard.webp`, mapImg: `TrebuchetBuffetMapLocation.webp`, shopImg: `TrebuchetBuffet.webp`, tasks: [] },
    { name: `Draw-Bridge Art Academy`, owner: `Bailey`, ownerImg: `Bailey.webp`, mapImg: `Draw-BridgeArtAcademyMapLocation.webp`, shopImg: `Draw-BridgeArtAcademy.webp`, tasks: [{ name: `Ye Olde Restoration Project`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Ye_Olde_Restoration_Project`, steps: [{ text: `Visit Bailey at Draw-Bridge Art Academy on Noble Nook (402 XP, 11 JBS)` }, { text: `Return to Magus Bizzy at Witchcraft? Hobby Helpers on Wizard Way (402 XP, 11 JBS)`, sub: `Defeat 8 Level 4+ Cogs Anywhere` }], reward: `Part of Ye Olde Restoration Project mainline chain` }] },
    { name: `Knight and Day`, owner: `Tielo Time`, ownerImg: `TieloTime.webp`, mapImg: `KnightAndDayMapLocation.webp`, shopImg: `KnightAndDay.webp`, tasks: [] },
    { name: `Bonbon Ballistae`, owner: `Frank Ferdinand`, ownerImg: `FrankFerdinand.webp`, mapImg: `BonbonBallistaeMapLocation.webp`, shopImg: `BonbonBallistae.webp`, tasks: [] },
    { name: `Platemail Post Office`, owner: `Marry Paston`, ownerImg: `MarryPaston.webp`, mapImg: `PlatemailPostOfficeMapLocation.webp`, shopImg: `PlatemailPostOffice.webp`, tasks: [TASK_COG_BASH, { name: `Ye Olde Missing Postage`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Ye_Olde_Missing_Postage`, steps: [{ text: `Visit Marry Paston at the Platemail Post Office on Noble Nook (887 XP, 25 JBS)` }, { text: `Return to Marry Paston at the Platemail Post Office on Noble Nook (887 XP, 25 JBS)`, sub: `Recover A Package from Micromanagers Anywhere` }, { text: `Return to Will Lusion at Toon HQ (4434 XP, 125 JBS)`, sub: `Defeat A Cog Building Anywhere` }], reward: `4434 XP - 125 JBS (final step)` }] },
    { name: `Crusade Charades`, owner: `Rob N. Hood`, ownerImg: `RobNHood.webp`, mapImg: `CrusadeCharadesMapLocation.webp`, shopImg: `CrusadeCharades.webp`, tasks: [] },
    { name: `Dark Ages Sleep Studies`, owner: `Cleric Cecily`, ownerImg: `ClericCecily.webp`, mapImg: `DarkAgesSleepStudiesMapLocation.webp`, shopImg: `DarkAgesSleepStudies.webp`, tasks: [{ name: `Ye Olde Restoration Project`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Ye_Olde_Restoration_Project`, steps: [{ text: `Visit Cleric Cecily at Dark Ages - Sleep Studies on Noble Nook (402 XP, 11 JBS)` }, { text: `Return 8 Wiring to Gentry Gary (402 XP, 11 JBS)`, sub: `Recover 8 Wiring from The Cogs Anywhere` }], reward: `Part of Ye Olde Restoration Project mainline chain` }] },
    { name: `Pitch Blacksmith`, owner: `Blacksmith Botolf`, ownerImg: `BlacksmithBotolf.webp`, mapImg: `PitchBlacksmithMapLocation.webp`, shopImg: `PitchBlacksmith.webp`, tasks: [] },
    { name: `Joust Leave It to Ye!`, owner: `Younice`, ownerImg: `Younice.webp`, mapImg: `JoustLeaveItToYeMapLocation.webp`, shopImg: `JoustLeaveItToYe.webp`, tasks: [] },
    { name: `Re-Moat-Ly Funny Fables`, owner: `Will Rakespeare`, ownerImg: `WillRakespeare.webp`, mapImg: `Re-Moat_LyFunnyFablesMapLocation.webp`, shopImg: `Re-Moat_LyFunnyFables.webp`, tasks: [] },
    { name: `Followed to the Leather`, owner: `Merchant Margery`, ownerImg: `MerchantMargery.webp`, mapImg: `FollowedToTheLeatherMapLocation.webp`, shopImg: `FollowedToTheLeather.webp`, tasks: [] },
    { name: `Squire's Square`, owner: `Squire Simon`, ownerImg: `SquireSimon.webp`, mapImg: `Squire'sSquareMapLocation.webp`, shopImg: `Squire'sSquare.webp`, tasks: [] },
    { name: `Arrow to the Knee`, owner: `Ariel Septim VII`, ownerImg: `ArielSeptimVII.webp`, mapImg: `ArrowToTheKneeMapLocation.webp`, shopImg: `ArrowToTheKnee.webp`, tasks: [TASK_ADVENTURER] },
    { name: `Fried Earthapples`, owner: `Monsieur Fyre`, ownerImg: `MonsieurFrye.webp`, mapImg: `FriedEarthapplesMapLocation.webp`, shopImg: `FriedEarthapples.webp`, tasks: [] },
  ],
};
STREET_SHOPS[`YOTT|Noble Nook`] = YOTT_NOBLE;

const YOTT_WIZARD: StreetShopData = {
  streetName: `Wizard Way`, neighborhood: `Ye Olde Toontowne`,
  mainMap: `/icons/streets/Ye-Olde-Toontowne/Wizard-Way/wizard-way-main-map.webp`,
  shopsBase: `/icons/streets/Ye-Olde-Toontowne/Wizard-Way`,
  shops: [
    { name: `Critical Roles: Job Finding`, owner: `Nat Twenny`, ownerImg: `NatTwenny.webp`, mapImg: `CritcalRolesJobFindingMapLocation.webp`, shopImg: `CritcalRolesJobFinding.webp`, tasks: [] },
    { name: `Brain Over Bronze`, owner: `Mad Ernage`, ownerImg: `MadErnage.webp`, mapImg: `BrainOverBronzeMapLocation.webp`, shopImg: `BrainOverBronze.webp`, tasks: [{ name: `Executing The Executives (cont.)`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Executing_The_Executives`, steps: [{ text: `Visit Mad Ernage at Brain Over Bronze on Wizard Way (594 XP, 17 JBS)` }, { text: `Return to Jongleur Jocelyn (4157 XP, 117 JBS, Conquistador Helmet)`, sub: `Defeat 3 Level 5+ Cogs Anywhere` }], reward: `Part of Executing The Executives mainline chain` }] },
    { name: `Plague! Plague! Go Away!`, owner: `Craig Plague`, ownerImg: `CraigPlague.webp`, mapImg: `PlaguePlagueGoAwayMapLocation.webp`, shopImg: `PlaguePlagueGoAway.webp`, tasks: [{ name: `Cog Flu`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Cog_Flu`, steps: [{ text: `Visit Craig Plague at Plague! Plague! Go Away! on Wizard Way (1182 XP, 33 JBS)` }, { text: `Deliver Some Information to Will Lusion at Toon HQ (4727 XP, 133 JBS)`, sub: `Recover 3 Info from Cogs on Knight Knoll, 3 from Noble Nook, 3 from Wizard Way` }], reward: `4727 XP - 133 JBS (final step)` }] },
    { name: `Middle Age Crisis Center`, owner: `Youthful Yannis`, ownerImg: `YouthfulYannis.webp`, mapImg: `MiddleAgeCrisisCenterMapLocation.webp`, shopImg: `MiddleAgeCrisisCenter.webp`, tasks: [TASK_MIDLIFE] },
    { name: `MacBreath Mints`, owner: `Mac Breath`, ownerImg: `MacBreath.webp`, mapImg: `MacBreathMintsMapLocation.webp`, shopImg: `MacBreathMints.webp`, tasks: [] },
    { name: `Gerry Gemcutter's Jewelry`, owner: `Gerry Gemcutter`, ownerImg: `GerryGemcutter.webp`, mapImg: `GerryGemcutter'sJewelryMapLocation.webp`, shopImg: `GerryGemcutter'sJewelry.webp`, tasks: [] },
    { name: `Release Game`, owner: `Sir Owen`, ownerImg: `SirOwen.webp`, mapImg: `ReleaseGameMapLocation.webp`, shopImg: `ReleaseGame.webp`, tasks: [] },
    { name: `Rayvenward School of Magical Arts`, owner: `Merlin Ambrice`, ownerImg: `MerlinAmbrice.webp`, mapImg: `RayvenwardSchoolOfMagicalArtsMapLocation.webp`, shopImg: `RayvenwardSchoolOfMagicalArts.webp`, tasks: [TASK_COG_BASH, TASK_GOLDEN_PENNY] },
    { name: `Potion Motion Arcade`, owner: `Dude El Dug`, ownerImg: `Dude_El_Dug.webp`, mapImg: `PotionMotionArcadeMapLocation.webp`, shopImg: `PotionMotionArcade.webp`, tasks: [] },
    { name: `Country Fair Maiden Funnel Cakes`, owner: `Lady Lotsalard`, ownerImg: `LadyLotsalard.webp`, mapImg: `CountryFairMaidenFunnelCakesMapLocation.webp`, shopImg: `CountryFairMaidenFunnelCakes.webp`, tasks: [] },
    { name: `One Potion, Two Potions`, owner: `Dr. Brewce`, ownerImg: `Dr.Brewce.webp`, mapImg: `OnePotionTwoPotionsMapLocation.webp`, shopImg: `OnePotionTwoPotions.webp`, tasks: [] },
    { name: `Wish Upon A Starfish - Magical Aquarium`, owner: `Sparkle N. Sea`, ownerImg: `SparkleN.Sea.webp`, mapImg: `WishUponAStarfishMapLocation.webp`, shopImg: `WishUponAStarfishMagicalAquarium.webp`, tasks: [] },
    { name: `Demon Slayers`, owner: `Sir Prysin`, ownerImg: `SirPrysin.webp`, mapImg: `DemonSlayersMapLocation.webp`, shopImg: `DemonSlayers.webp`, tasks: [TASK_EXECUTING_JJ] },
    { name: `Fool's Wool`, owner: `Mitch E.`, ownerImg: `MitchE.webp`, mapImg: `Fool'sWoolMapLocation.webp`, shopImg: `Fool'sWool.webp`, tasks: [] },
    { name: `Horse Drawn Karts`, owner: `Joan of Park`, ownerImg: `JoanofPark.webp`, mapImg: `HorseDrawnKartsMapLocation.webp`, shopImg: `HorseDrawnKarts.webp`, tasks: [{ name: `Ye Olde Restoration Project`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Ye_Olde_Restoration_Project`, steps: [{ text: `Visit Joan of Park at Horse-drawn Karts on Wizard Way (402 XP, 11 JBS)` }, { text: `Return to Magus Bizzy at Witchcraft? Hobby Helpers (4017 XP, 111 JBS)`, sub: `Defeat 5 Executive Cogs Anywhere` }], reward: `Part of Ye Olde Restoration Project` }] },
    { name: `Watch for De Brie! Contractors`, owner: `Sir Reezy`, ownerImg: `SirReezy.webp`, mapImg: `WatchForDeBrieMapLocation.webp`, shopImg: `WatchForDeBrie.webp`, tasks: [] },
    { name: `Royal Thrones Toiletries`, owner: `Percy Lane`, ownerImg: `PercyLane.webp`, mapImg: `RoyalThronesToiletriesMapLocation.webp`, shopImg: `RoyalThronesToiletries.webp`, tasks: [{ name: `Ye Olde Restoration Project`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Ye_Olde_Restoration_Project`, steps: [{ text: `Visit Percy Lane at Royal Thrones Toiletries on Wizard Way (402 XP, 11 JBS)` }, { text: `Return to Magus Bizzy (402 XP, 11 JBS)`, sub: `Recover Some Furniture from Movers & Shakers Anywhere` }], reward: `Part of Ye Olde Restoration Project` }] },
    { name: `Witchcraft? Hobby Helpers`, owner: `Magus Bizzy`, ownerImg: `MagusBizzy.webp`, mapImg: `WitchcraftHobbyHelpersMapLocation.webp`, shopImg: `WitchcraftHobbyHelpers.webp`, tasks: [{ name: `Ye Olde Restoration Project (hub)`, type: `Mainline Task`, wikiUrl: `https://corporateclash.wiki.gg/wiki/Ye_Olde_Toontowne_Tasks#Ye_Olde_Restoration_Project`, steps: [{ text: `Visit Magus Bizzy at Witchcraft? Hobby Helpers on Wizard Way (402 XP, 11 JBS)` }, { text: `Investigate the Wizard Way Tunnel` }, { text: `Return to Magus Bizzy (402 XP, 11 JBS)` }, { text: `Visit Bailey at Draw-Bridge Art Academy on Noble Nook (402 XP, 11 JBS)` }, { text: `Return to Magus Bizzy (402 XP, 11 JBS)`, sub: `Defeat 8 Level 4+ Cogs Anywhere` }, { text: `Visit Joan of Park at Horse-drawn Karts on Wizard Way (402 XP, 11 JBS)` }, { text: `Return to Magus Bizzy (4017 XP, 111 JBS)`, sub: `Defeat 5 Executive Cogs Anywhere` }, { text: `Visit Percy Lane at Royal Thrones Toiletries on Wizard Way (402 XP, 11 JBS)` }, { text: `Return to Magus Bizzy (402 XP, 11 JBS)`, sub: `Recover Some Furniture from Movers & Shakers Anywhere` }], reward: `Hub for Ye Olde Restoration Project chain` }] },
  ],
};
STREET_SHOPS[`YOTT|Wizard Way`] = YOTT_WIZARD;
