import type { QuestPlayground } from './data-quests-types';
import { H, Q, S, KL, KH } from './data-quests-types';
export const MML: QuestPlayground = {
  name: 'Mezzo Melodyland', icon: '🎵', color: '#3a1545', accent: '#bf62cb',
  mainColor: '#e050ff', kudosHighColor: '#40ffb8',
  rows: [
    H('Main Storyline'),
    Q("Flippy's Been Expecting You",'',''), Q('Can Anybody Find Mae …','',''),
    Q('Tracing Tasty Treasure','',''), Q('LaughTrack.mp3','',''),
    Q('KAAAAZOOOOOOO!','',''), Q('Chop Shop Blues','',''),
    Q('Going Through The Maetions','',''), Q('Slow Cruising','',''),
    Q('Dull Scissors & Expectations','',''), Q('Take a Deeeeep Breath','',''),
    Q('To Catch a Cashbot','',''), Q('Mints, Anyone?','',''),
    Q("The Plan's a Go",'',''), Q('The Vault Heist','',''),
    Q('The Show Must Go On','⭐ The Brrrgh – Profile Background',''),
    H('Sidetasks'),
    S('Triple Scoop, Please!','⭐ Teleport Access','Alto Avenue (Tenor Times)'),
    S('Big Band Marching','Marching Band Outfit','Alto Avenue (For Good Measure)'),
    S('Flat Notes & Profiles','⭐ Whimsical – Nametag | ⭐ Flat Profile – Cheesy Effect','Soprano Street (Bee Flat Exterminators)'),
    S("What's That Sound?",'⭐ Big Head – Cheesy Effect','Soprano Street (Pipe Organs Medical Facilities)'),
    S('Got You Covered!','⭐ Fancy – Nametag','Alto Avenue (Pitch Perfect Roofing)'),
    S('Piano Player','⭐ Presenting – Profile Pose','Tumbies (Playground)'),
    H('Kudos Rank-Up Quests'),
    KL('1→2  Networking?','+1 MML Gag XP Multiplier'),
    KL('2→3  Banker Besties','15% Cheaper Gags in MML | +1 MML CUMBALL Booster'),
    KL('3→4  Rocked Out','⭐ Rock Concert – Background | ⭐ Fires n Flames – Nameplate'),
    KL('4→5  Cookie Conundrum','⭐ Pick Up The Phone – Profile Pose'),
    KL('5→6  Fools Brass','30% Cheaper Gags in MML | +1 MML CUMBALL Booster'),
    KH('6→7  Bach in Business','+2 MML Gag XP Multiplier'),
    KH('7→8  Phonic Phraudulence','⭐ Playful – Nametag Font'),
    KH('8→9  Musical Monstrosity','50% Cheaper Gags in MML | +1 MML CUMBALL Booster'),
    KH("9→10  Let's Dance!",'+1 Max Laff'),
    KH('10+  +40 Gumballs'),
  ],
};
