// Leveling Rewards: Level 2–85
export const LEVELING_REWARDS: { level: number; laff: number; xp: number; reward: string }[] = [
  { level: 2,  laff: 16, xp: 90,     reward: '+1 Laff' },
  { level: 3,  laff: 17, xp: 210,    reward: '+1 Laff' },
  { level: 4,  laff: 18, xp: 360,    reward: '+1 Laff · Training point' },
  { level: 5,  laff: 19, xp: 540,    reward: '+1 Laff · Carry 1,000 jellybeans' },
  { level: 6,  laff: 20, xp: 750,    reward: '+1 Laff' },
  { level: 7,  laff: 21, xp: 990,    reward: '+1 Laff' },
  { level: 8,  laff: 22, xp: 1260,   reward: '+1 Laff · Training point' },
  { level: 9,  laff: 23, xp: 1560,   reward: '+1 Laff' },
  { level: 10, laff: 24, xp: 1890,   reward: '+1 Laff · Carry 30 gags · Carry 1,500 jellybeans' },
  { level: 11, laff: 25, xp: 2250,   reward: '+1 Laff' },
  { level: 12, laff: 26, xp: 2640,   reward: '+1 Laff · Training point' },
  { level: 13, laff: 27, xp: 3060,   reward: '+1 Laff' },
  { level: 14, laff: 28, xp: 3510,   reward: '+1 Laff' },
  { level: 15, laff: 29, xp: 3990,   reward: '+1 Laff · Carry 2,000 jellybeans' },
  { level: 16, laff: 30, xp: 4500,   reward: '+1 Laff · Training point' },
  { level: 17, laff: 31, xp: 5040,   reward: '+1 Laff' },
  { level: 18, laff: 32, xp: 5610,   reward: '+1 Laff' },
  { level: 19, laff: 33, xp: 6210,   reward: '+1 Laff' },
  { level: 20, laff: 34, xp: 6840,   reward: '+1 Laff · Carry 40 gags · Carry 2,500 jellybeans · Training point' },
  { level: 21, laff: 35, xp: 7500,   reward: '+1 Laff' },
  { level: 22, laff: 36, xp: 8190,   reward: '+1 Laff' },
  { level: 23, laff: 37, xp: 8910,   reward: '+1 Laff' },
  { level: 24, laff: 38, xp: 9660,   reward: '+1 Laff' },
  { level: 25, laff: 39, xp: 10440,  reward: '+1 Laff · Carry 3,000 jellybeans' },
  { level: 26, laff: 40, xp: 11250,  reward: '+1 Laff' },
  { level: 27, laff: 41, xp: 12090,  reward: '+1 Laff' },
  { level: 28, laff: 42, xp: 12960,  reward: '+1 Laff · Training point' },
  { level: 29, laff: 43, xp: 13860,  reward: '+1 Laff' },
  { level: 30, laff: 44, xp: 14790,  reward: '+1 Laff · Carry 50 gags · Carry 3,500 jellybeans' },
  { level: 31, laff: 45, xp: 15750,  reward: '+1 Laff' },
  { level: 32, laff: 46, xp: 16740,  reward: '+1 Laff' },
  { level: 33, laff: 47, xp: 17760,  reward: '+1 Laff' },
  { level: 34, laff: 48, xp: 18810,  reward: '+1 Laff' },
  { level: 35, laff: 49, xp: 19890,  reward: '+1 Laff · Carry 4,000 jellybeans' },
  { level: 36, laff: 50, xp: 21000,  reward: '+1 Laff' },
  { level: 37, laff: 51, xp: 22140,  reward: '+1 Laff' },
  { level: 38, laff: 52, xp: 23310,  reward: '+1 Laff · Training point' },
  { level: 39, laff: 53, xp: 24510,  reward: '+1 Laff' },
  { level: 40, laff: 54, xp: 25740,  reward: '+1 Laff · Carry 60 gags · Carry 4,500 jellybeans' },
  { level: 41, laff: 55, xp: 27000,  reward: '+1 Laff' },
  { level: 42, laff: 56, xp: 28290,  reward: '+1 Laff' },
  { level: 43, laff: 57, xp: 29610,  reward: '+1 Laff' },
  { level: 44, laff: 58, xp: 30960,  reward: '+1 Laff' },
  { level: 45, laff: 59, xp: 32340,  reward: '+1 Laff · Carry 5,000 jellybeans' },
  { level: 46, laff: 60, xp: 33750,  reward: '+1 Laff' },
  { level: 47, laff: 61, xp: 35190,  reward: '+1 Laff' },
  { level: 48, laff: 62, xp: 36660,  reward: '+1 Laff' },
  { level: 49, laff: 63, xp: 38160,  reward: '+1 Laff' },
  { level: 50, laff: 64, xp: 39690,  reward: '+1 Laff · Carry 70 gags · Carry 5,500 jellybeans' },
  { level: 51, laff: 65, xp: 41250,  reward: '+1 Laff' },
  { level: 52, laff: 66, xp: 42840,  reward: '+1 Laff' },
  { level: 53, laff: 67, xp: 44460,  reward: '+1 Laff' },
  { level: 54, laff: 68, xp: 46110,  reward: '+1 Laff' },
  { level: 55, laff: 69, xp: 47790,  reward: '+1 Laff · Carry 6,000 jellybeans' },
  { level: 56, laff: 70, xp: 49500,  reward: '+1 Laff' },
  { level: 57, laff: 71, xp: 51240,  reward: '+1 Laff' },
  { level: 58, laff: 72, xp: 53010,  reward: '+1 Laff' },
  { level: 59, laff: 73, xp: 54810,  reward: '+1 Laff' },
  { level: 60, laff: 74, xp: 56640,  reward: '+1 Laff · Carry 80 gags · Carry 6,500 jellybeans' },
  { level: 61, laff: 75, xp: 58500,  reward: '+1 Laff' },
  { level: 62, laff: 76, xp: 60390,  reward: '+1 Laff' },
  { level: 63, laff: 77, xp: 62310,  reward: '+1 Laff' },
  { level: 64, laff: 78, xp: 64260,  reward: '+1 Laff' },
  { level: 65, laff: 79, xp: 66240,  reward: '+1 Laff · Carry 7,000 jellybeans' },
  { level: 66, laff: 80, xp: 68250,  reward: '+1 Laff' },
  { level: 67, laff: 81, xp: 70290,  reward: '+1 Laff' },
  { level: 68, laff: 82, xp: 72360,  reward: '+1 Laff · Training point' },
  { level: 69, laff: 83, xp: 74460,  reward: '+1 Laff' },
  { level: 70, laff: 84, xp: 76590,  reward: '+1 Laff · Carry 90 gags · Carry 7,500 jellybeans' },
  { level: 71, laff: 85, xp: 78750,  reward: '+1 Laff' },
  { level: 72, laff: 86, xp: 80940,  reward: '+1 Laff' },
  { level: 73, laff: 87, xp: 83160,  reward: '+1 Laff' },
  { level: 74, laff: 88, xp: 85410,  reward: '+1 Laff' },
  { level: 75, laff: 89, xp: 87690,  reward: '+1 Laff · Carry 8,000 jellybeans' },
  { level: 76, laff: 90, xp: 90000,  reward: '+1 Laff' },
  { level: 77, laff: 91, xp: 92340,  reward: '+1 Laff' },
  { level: 78, laff: 92, xp: 94710,  reward: '+1 Laff · Training point' },
  { level: 79, laff: 93, xp: 97110,  reward: '+1 Laff' },
  { level: 80, laff: 94, xp: 99540,  reward: '+1 Laff · Carry 100 gags · Carry 8,500 jellybeans' },
  { level: 81, laff: 95, xp: 102000, reward: '+1 Laff' },
  { level: 82, laff: 96, xp: 104490, reward: '+1 Laff' },
  { level: 83, laff: 97, xp: 107010, reward: '+1 Laff' },
  { level: 84, laff: 98, xp: 109560, reward: '+1 Laff' },
  { level: 85, laff: 99, xp: 112140, reward: '+1 Laff · Carry 9,000 jellybeans' },
];

// Total Laff Boost table
export type LaffBoostEntry =
  | { isHeader: true;  section: string; total: string }
  | { isHeader: false; section: string; note: string; source: string; laff: number; playground?: string };

export const LAFF_BOOSTS: LaffBoostEntry[] = [
  // Kudos Ranking — playground field maps to PG_ICON_MAP key in SectionLaff
  { isHeader: false, section: 'Kudos Ranking', note: 'Reach Kudos Rank 10', source: 'Kudos Rank 10', laff: 1, playground: 'Toontown Central' },
  { isHeader: false, section: 'Kudos Ranking', note: 'Reach Kudos Rank 10', source: 'Kudos Rank 10', laff: 1, playground: 'Barnacle Boatyard' },
  { isHeader: false, section: 'Kudos Ranking', note: 'Reach Kudos Rank 10', source: 'Kudos Rank 10', laff: 1, playground: 'Ye Olde Toontowne' },
  { isHeader: false, section: 'Kudos Ranking', note: 'Reach Kudos Rank 10', source: 'Kudos Rank 10', laff: 1, playground: 'Daffodil Gardens' },
  { isHeader: false, section: 'Kudos Ranking', note: 'Reach Kudos Rank 10', source: 'Kudos Rank 10', laff: 1, playground: 'Mezzo Melodyland' },
  { isHeader: false, section: 'Kudos Ranking', note: 'Reach Kudos Rank 10', source: 'Kudos Rank 10', laff: 1, playground: 'The Brrrgh' },
  { isHeader: false, section: 'Kudos Ranking', note: 'Reach Kudos Rank 10', source: 'Kudos Rank 10', laff: 1, playground: 'Acorn Acres' },
  { isHeader: false, section: 'Kudos Ranking', note: 'Reach Kudos Rank 10', source: 'Kudos Rank 10', laff: 1, playground: 'Drowsy Dreamland' },
  { isHeader: true,  section: 'Kudos Ranking', total: '+8 Laff' },
  // Fishing
  { isHeader: false, section: 'Fishing', note: 'Level 10', source: 'Fishing', laff: 1 },
  { isHeader: false, section: 'Fishing', note: 'Level 20', source: 'Fishing', laff: 1 },
  { isHeader: false, section: 'Fishing', note: 'Level 30', source: 'Fishing', laff: 1 },
  { isHeader: false, section: 'Fishing', note: 'Level 40', source: 'Fishing', laff: 1 },
  { isHeader: false, section: 'Fishing', note: 'Level 50', source: 'Fishing', laff: 1 },
  { isHeader: false, section: 'Fishing', note: 'Level 60', source: 'Fishing', laff: 1 },
  { isHeader: false, section: 'Fishing', note: 'Level 70', source: 'Fishing', laff: 1 },
  { isHeader: true,  section: 'Fishing', total: '+7 Laff' },
  // Trolly
  { isHeader: false, section: 'Trolly', note: 'Level 10', source: 'Trolley', laff: 1 },
  { isHeader: false, section: 'Trolly', note: 'Level 20', source: 'Trolley', laff: 1 },
  { isHeader: false, section: 'Trolly', note: 'Level 30', source: 'Trolley', laff: 1 },
  { isHeader: true,  section: 'Trolly', total: '+3 Laff' },
  // Racing
  { isHeader: false, section: 'Racing', note: 'Level 10', source: 'Racing', laff: 1 },
  { isHeader: false, section: 'Racing', note: 'Level 20', source: 'Racing', laff: 1 },
  { isHeader: false, section: 'Racing', note: 'Level 30', source: 'Racing', laff: 1 },
  { isHeader: true,  section: 'Racing', total: '+3 Laff' },
  // Golfing
  { isHeader: false, section: 'Golfing', note: 'Level 10', source: 'Golfing', laff: 1 },
  { isHeader: false, section: 'Golfing', note: 'Level 20', source: 'Golfing', laff: 1 },
  { isHeader: false, section: 'Golfing', note: 'Level 30', source: 'Golfing', laff: 1 },
  { isHeader: true,  section: 'Golfing', total: '+3 Laff' },
  // Sellbot Promotions
  { isHeader: false, section: 'Sellbot Promotions', note: 'Level 8',  source: 'Sellbot Suit', laff: 1 },
  { isHeader: false, section: 'Sellbot Promotions', note: 'Level 15', source: 'Sellbot Suit', laff: 1 },
  { isHeader: false, section: 'Sellbot Promotions', note: 'Level 20', source: 'Sellbot Suit', laff: 1 },
  { isHeader: false, section: 'Sellbot Promotions', note: 'Level 30', source: 'Sellbot Suit', laff: 1 },
  { isHeader: false, section: 'Sellbot Promotions', note: 'Level 40', source: 'Sellbot Suit', laff: 1 },
  { isHeader: false, section: 'Sellbot Promotions', note: 'Level 50', source: 'Sellbot Suit', laff: 1 },
  { isHeader: true,  section: 'Sellbot Promotions', total: '+6 Laff' },
  // Cashbot Promotions
  { isHeader: false, section: 'Cashbot Promotions', note: 'Level 8',  source: 'Cashbot Suit', laff: 1 },
  { isHeader: false, section: 'Cashbot Promotions', note: 'Level 15', source: 'Cashbot Suit', laff: 1 },
  { isHeader: false, section: 'Cashbot Promotions', note: 'Level 20', source: 'Cashbot Suit', laff: 1 },
  { isHeader: false, section: 'Cashbot Promotions', note: 'Level 30', source: 'Cashbot Suit', laff: 1 },
  { isHeader: false, section: 'Cashbot Promotions', note: 'Level 40', source: 'Cashbot Suit', laff: 1 },
  { isHeader: false, section: 'Cashbot Promotions', note: 'Level 50', source: 'Cashbot Suit', laff: 1 },
  { isHeader: true,  section: 'Cashbot Promotions', total: '+6 Laff' },
  // Lawbot Promotions
  { isHeader: false, section: 'Lawbot Promotions', note: 'Level 8',  source: 'Lawbot Suit', laff: 1 },
  { isHeader: false, section: 'Lawbot Promotions', note: 'Level 15', source: 'Lawbot Suit', laff: 1 },
  { isHeader: false, section: 'Lawbot Promotions', note: 'Level 20', source: 'Lawbot Suit', laff: 1 },
  { isHeader: false, section: 'Lawbot Promotions', note: 'Level 30', source: 'Lawbot Suit', laff: 1 },
  { isHeader: false, section: 'Lawbot Promotions', note: 'Level 40', source: 'Lawbot Suit', laff: 1 },
  { isHeader: false, section: 'Lawbot Promotions', note: 'Level 50', source: 'Lawbot Suit', laff: 1 },
  { isHeader: true,  section: 'Lawbot Promotions', total: '+6 Laff' },
  // Bossbot Promotions
  { isHeader: false, section: 'Bossbot Promotions', note: 'Level 8',  source: 'Bossbot Suit', laff: 1 },
  { isHeader: false, section: 'Bossbot Promotions', note: 'Level 15', source: 'Bossbot Suit', laff: 1 },
  { isHeader: false, section: 'Bossbot Promotions', note: 'Level 20', source: 'Bossbot Suit', laff: 1 },
  { isHeader: false, section: 'Bossbot Promotions', note: 'Level 30', source: 'Bossbot Suit', laff: 1 },
  { isHeader: false, section: 'Bossbot Promotions', note: 'Level 40', source: 'Bossbot Suit', laff: 1 },
  { isHeader: false, section: 'Bossbot Promotions', note: 'Level 50', source: 'Bossbot Suit', laff: 1 },
  { isHeader: true,  section: 'Bossbot Promotions', total: '+6 Laff' },
  // Directives
  { isHeader: false, section: 'Directives', note: '10 Needlenose', source: 'Completing Directives', laff: 1 },
  { isHeader: false, section: 'Directives', note: '15 Advocate',   source: 'Completing Directives', laff: 1 },
  { isHeader: false, section: 'Directives', note: '14 Borrister',  source: 'Completing Directives', laff: 1 },
  { isHeader: true,  section: 'Directives', total: '+3 Laff' },
];

