export interface CollectionItem { name: string; type: string; how: string; img?: string; }
export interface CollectionSection { name: string; icon: string; color: string; accent: string; items: CollectionItem[]; }
const I = (name: string, type: string, how: string, img?: string): CollectionItem => ({ name, type, how, img });
const BG = (f: string) => `/icons/collections/profile-backgrounds/${f}`;
const NP = (f: string) => `/icons/collections/profile-nameplates/${f}`;
const NT = (f: string) => `/icons/collections/profile-nametags/${f}`;
const PP = (f: string) => `/icons/collections/profile-poses/${f}`;
const CE = (f: string) => `/icons/collections/profile-cheesy-effects/${f}`;
const EM = (f: string) => `/icons/collections/emotions/${f}`;

export const COLLECTIONS: CollectionSection[] = [
  { name:"Start of Game", icon:"🎮", color:"#1a1a2a", accent:"#8888ff", items:[
    I("Default","Background","Available at start of game",BG('DefaultBackground.png')),
    I("Default Blue","Nameplate","Available at start of game",NP('DefaultBlue.png')),
    I("Default Dark Blue","Nameplate","Available at start of game",NP('DefaultDarkBlue.png')),
    I("Default Dark Green","Nameplate","Available at start of game",NP('DefaultDarkGreen.png')),
    I("Default Green","Nameplate","Available at start of game",NP('DefaultGreen.png')),
    I("Default Light Blue","Nameplate","Available at start of game",NP('DefaultLightBlue.png')),
    I("Default Orange","Nameplate","Available at start of game",NP('DefaultOrange.png')),
    I("Default Purple","Nameplate","Available at start of game",NP('DefaultPurple.png')),
    I("Default Red","Nameplate","Available at start of game",NP('DefaultRed.png')),
    I("Default Yellow","Nameplate","Available at start of game",NP('DefaultYellow.png')),
    I("Basic","Nametag","Available at start of game",NT('Basic_Nametag.png')),
    I("Plain","Nametag","Available at start of game",NT('Plain_Nametag.png')),
    I("Applause","Profile Pose","Available at start of game",PP('Pose-applause.png')),
    I("Neutral","Profile Pose","Available at start of game",PP('Pose-neutral.png')),
    I("Sit","Profile Pose","Available at start of game",PP('Pose-sit.png')),
    I("Wave","Profile Pose","Available at start of game",PP('Pose-wave.png')),
    I("Agree","Emotion","Available at start of game",EM('neutral/Agree.gif')),
    I("Angry","Emotion","Available at start of game",EM('negative/Angry.gif')),
    I("Disagree","Emotion","Available at start of game",EM('neutral/Disagree.gif')),
    I("Happy","Emotion","Available at start of game",EM('positive/Happy.gif')),
    I("Sleepy","Emotion","Available at start of game",EM('neutral/Sleepy.gif')),
    I("Wave","Emotion","Available at start of game",EM('neutral/Wave.gif')),
  ]},
  { name:"Activities", icon:"🎣", color:"#0a2a1a", accent:"#3dd68c", items:[
    I("Jellybeans","Background","Awarded for completing the Trolley for the first time",BG('JellybeansBackground.png')),
    I("Aquarium","Background","Awarded rarely when Fishing",BG('AquariumBackground.png')),
    I("Golfing","Background","Awarded for completing a round of Golf for the first time",BG('GolfingBackground.png')),
    I("Chequered Flag","Background","Awarded for completing a Race for the first time",BG('FlagBackground.png')),
    I("The Trolley","Nameplate","Awarded after completing Trolley games",NP('Trolley.png')),
    I("Under the Sea","Nameplate","Awarded after catching a rare fish",NP('UnderTheSea.png')),
    I("Golfing","Nameplate","Awarded for completing a round of Golf",NP('GolfingNameplate.png')),
    I("Racing","Nameplate","Awarded for completing a Race",NP('RacingNameplate.png')),
  ]},
  { name:"Misc.", icon:"🌟", color:"#2a1a00", accent:"#ffaa00", items:[
    I("Pacesetter & Firestarter","Background","Awarded after using the code FIRESETTER",BG('Pacesetter&FirestarterBackground.png')),
    I("Game Show","Background","Awarded after defeating the High Roller 13 times",BG('GameShowBackground.png')),
    I("Duck Shuffler","Background","Awarded after defeating the Duck Shuffler",BG('DuckShufflerBackground.png')),
    I("Cybertoon","Background","Awarded from a special event",BG('CybertoonBackground.png')),
    I("Pacesetter & Firestarter","Nameplate","Awarded after using the code FIRESETTER",NP('Pacesetter&FirestarterNameplate.png')),
    I("Game Show","Nameplate","Awarded after defeating the High Roller 13 times",NP('GameShowNameplate.png')),
    I("Cybertoon","Nameplate","Awarded from a special event",NP('CybertoonNameplate.png')),
    I("Green Duck Shuffler","Nameplate","Awarded after defeating the Duck Shuffler",NP('GreenDuckShufflerNameplate.png')),
    I("Red Duck Shuffler","Nameplate","Awarded after defeating the Duck Shuffler",NP('RedDuckShufflerNameplate.png')),
    I("Birthday Bash","Nametag","Special event reward",NT('Birthday_Bash_Nametag.png')),
    I("Sad","Emotion","Available at start of game",EM('negative/Sad.gif')),
    I("Shrug","Emotion","Purchasable from the Cattlelog (Series 1, #1 / Series 3, #1)",EM('neutral/Shrug.gif')),
    I("Think","Emotion","Purchasable from the Cattlelog (Series 4, #6)",EM('neutral/Think.gif')),
    I("Yawn","Emotion","Purchasable from the Cattlelog (Series 1, #1) — never goes to backorder",EM('neutral/Yawn.gif')),
    I("Laugh","Emotion","Purchasable from the Cattlelog (Series 1, #1) — never goes to backorder",EM('positive/Laugh.gif')),
    I("Dance","Emotion","Purchasable from the Cattlelog (Series 2, #5)",EM('positive/Dance.gif')),
    I("Applause","Emotion","Purchasable from the Cattlelog (Series 1, #5 / Series 3, #12)",EM('positive/Applause.gif')),
    I("Delighted","Emotion","Purchasable from the Cattlelog (Series 1, #1) — never goes to backorder",EM('positive/Delighted.gif')),
    I("Surprise","Emotion","Purchasable from the Cattlelog (Series 1, #1) — never goes to backorder",EM('positive/Surprise.gif')),
    I("Bow","Emotion","Purchasable from the Cattlelog (Series 1, #9 / Series 3, #8)",EM('positive/Bow.gif')),
    I("Furious","Emotion","Purchasable from the Cattlelog (Series 1, #1) — never goes to backorder",EM('negative/Furious.gif')),
    I("Cry","Emotion","Purchasable from the Cattlelog (Series 1, #1) — never goes to backorder",EM('negative/Cry.gif')),
    I("Cringe","Emotion","Purchasable from the Cattlelog (Series 4, #12)",EM('negative/Cringe.gif')),
    I("Confused","Emotion","Purchasable from the Cattlelog (Series 2, #1)",EM('negative/Confused.gif')),
    I("Belly Flop","Emotion","Purchasable from the Cattlelog (Series 7, #5)",EM('negative/BellyFlop.gif')),
    I("Banana Peel","Emotion","Purchasable from the Cattlelog (Series 7, #10)",EM('negative/BananaPeel.gif')),
    I("Bored","Emotion","Purchasable from the Cattlelog (Series 2, #9)",EM('negative/Bored.gif')),
    I("Taunt","Emotion","Purchasable from the Cattlelog (Series 1, #1) — never goes to backorder",EM('negative/Taunt.gif')),
  ]},
  { name:"G.U.M.B.A.L.L. Machine", icon:"🔮", color:"#2a102a", accent:"#cc44cc", items:[
    I("Outback","Background","Purchasable from the G.U.M.B.A.L.L. Machine",BG('OutbackBackground.png')),
    I("Outback","Nameplate","Purchasable from the G.U.M.B.A.L.L. Machine",NP('OutbackNameplate.png')),
    I("Stars","Nameplate","Purchasable from the G.U.M.B.A.L.L. Machine",NP('Stars.png')),
    I("Silent Treatment","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 450 Gumballs",PP('Pose-Silent_Treatment.png')),
    I("Banana","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 500 Gumballs",PP('Pose-Banana.png')),
    I("Seltzer Bottle","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 500 Gumballs",PP('Pose-Seltzer_Bottle.png')),
    I("Gag Button","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 500 Gumballs",PP('Pose-Gag_Button.png')),
    I("Pie Toss","Profile Pose","Purchasable from the G.U.M.B.A.L.L. Machine for 500 Gumballs",PP('Pose-Pie_Toss.png')),
    I("Megaphone","Profile Pose","Awarded after completing the Temperature Troubles Directive",PP('Pose-megaphone.png')),
  ]},
  { name:"Promotions / Directives / Overclocked", icon:"⚙️", color:"#1a1a1a", accent:"#aaaaaa", items:[
    I("R.I.D.D.L.E","Background","Awarded from a special event",BG('Riddle.png')),
    I("Paint Mixer","Background","Awarded from a special event",BG('PaintMixerBackground.png')),
    I("Sellbot HQ","Background","Awarded for reaching the Sellbot HQ Playground",BG('SellbotHQBackground.png')),
    I("Sellbot Paint","Nameplate","Awarded after completing Overclocked Find the Foreman (April Toons 2022)",NP('SellbotPaintNameplate.png')),
    I("Cashbot HQ","Background","Awarded for reaching the Cashbot HQ Playground",BG('CashbotHQBackground.png')),
    I("Lawbot HQ","Background","Awarded for reaching the Lawbot HQ Playground",BG('LawbotHQBackground.png')),
    I("Bossbot HQ","Background","Awarded for reaching the Bossbot HQ Playground",BG('BossbotHQBackground.png')),
    I("Turning It Up To 11","Nameplate","Awarded after completing a Mezzo Melodyland Kudos Rank-Up Task",NP('Turningitupto11.png')),
    I("Crochet","Nameplate","Awarded from a special event",NP('Crochet.png')),
    I("Resistance Salute","Profile Pose","Awarded after defeating The Directors",PP('Pose-Resistance_Salute.png')),
  ]},
  { name:"🎃 Halloween", icon:"🎃", color:"#2a0e00", accent:"#ff6600", items:[
    I("The Golden Corridor","Background","Previously awarded for defeating Sads the Skelecog",BG('TheGoldenCorridorBackground.png')),
    I("Halloween Town","Background","Awarded during Halloween events",BG('HalloweenTown.png')),
    I("Halloween Night","Background","Awarded during Halloween events",BG('HalloweenNightBackground.png')),
    I("Lazy Bones","Nameplate","Previously awarded for defeating Sads the Skelecog",NP('LazyBonesNameplate.png')),
    I("Spooky Bat","Nameplate","Awarded during the Halloween 2020 event",NP('Spookybat.png')),
    I("Halloween Night","Nameplate","Awarded during Halloween events",NP('HalloweenNightNameplate.png')),
    I("Halloween Candy (Blue)","Nameplate","Awarded during Halloween events",NP('HalloweenCandyBlue.png')),
    I("Halloween Candy (Green)","Nameplate","Awarded during Halloween events",NP('HalloweenCandyGreen.png')),
    I("Halloween Candy (Magenta)","Nameplate","Awarded during Halloween events",NP('HalloweenCandyMagenta.png')),
    I("Halloween Candy (Purple)","Nameplate","Awarded during Halloween events",NP('HalloweenCandyPurple.png')),
    I("Halloween Candy (Red)","Nameplate","Awarded during Halloween events",NP('HalloweenCandyRed.png')),
    I("Spooky","Nametag","Awarded during Halloween events",NT('Spooky_Nametag.png')),
    I("Sinking","Profile Pose","Available from Reid Stock during Halloween/April Toons for 35 of each Shkrafting Material",PP('Pose-sinking.png')),
    I("Spooky","Profile Pose","Awarded after completing Halloween Organizer (Unobtainable)",PP('Pose-spooky.png')),
    I("Zombie","Profile Pose","Awarded after completing Spooky Storyteller (Unobtainable)",PP('Pose-zombie.png')),
    I("No Arms","Cheesy Effect","Available during Halloween for 35 of each Shkrafting Material",CE('CE_noarms.png')),
    I("Scapegourd","Cheesy Effect","Shkrafting Shop (Lynn Decisive)",CE('ScapegourdDouble.png')),
    I("Spirit","Cheesy Effect","Shkrafting Shop (Lynn Decisive)",CE('CE_spirit.png')),
    I("Stomped","Cheesy Effect","Shkrafting Shop (Lynn Decisive)",CE('CE_Stomped.png')),
    I("Yarr & Harr","Cheesy Effect","Halloween event reward",CE('Yarr&HarrDouble.png')),
  ]},
  { name:"🎄 Christmas", icon:"🎄", color:"#0a2010", accent:"#40d070", items:[
    I("Winter Cabin","Background","Drop from Toonseltown Present Thief Game (Toonsmas Update)",BG('WinterCabinBackground.png')),
    I("Fireplace","Background","Awarded after completing Stocking Stuffers Toontask",BG('Fireplace.png')),
    I("Night Lights","Nameplate","Toonsmas event reward",NP('NightLights.png')),
    I("Wrapping","Nameplate","Awarded after completing Presidential Appreciation Toontask",NP('Wrappingpaper.png')),
    I("Tinsel","Nameplate","Drop from Toonseltown Present Thief Game (Toonsmas Event)",NP('TinselNameplate.png')),
    I("Snowman Head","Cheesy Effect","Caroling during Toonsmas",CE('SnowmanHeadDouble.png')),
  ]},
  { name:"Toontown Central", icon:"🍦", color:"#5a2004", accent:"#d86b10", items:[
    I("Toontown Central","Background","Awarded for progressing to Toontown Central in the Taskline",BG('ToontownCentralBackground.png')),
    I("Toontown Central Sky","Background","Awarded for visiting Toontown Central",BG('ToontownCentralSkyBackground.png')),
    I("Congratulations","Background","Awarded after completing Give and Cake Kudos Rank-Up Task",BG('CongratulationsBackground.png')),
    I("Toontown Central","Nameplate","Awarded for visiting Toontown Central",NP('Ttcnameplate.png')),
    I("Slippin'","Nameplate","Awarded for clicking the Banana Peel in Toon Hall",NP('SlippinNameplate.png')),
    I("You Did It","Nameplate","Awarded after completing Give and Cake Kudos Rank-Up Task",NP('YouDidItNameplate.png')),
    I("Ice Cream","Nametag","Awarded after reaching Toontown Central Kudos Rank 8",NT('Ice_Cream_Nametag.png')),
    I("Zany","Nametag","Awarded after completing a Toontown Central task",NT('Nametag-Zany.png')),
    I("Become Duck","Profile Pose","Awarded after reaching Toontown Central Kudos Rank 5",PP('Pose-Become_Duck.png')),
    I("Selfie","Profile Pose","Awarded after completing the task New Toony Tourist",PP('Pose-selfie.png')),
    I("Upset","Profile Pose","Awarded after defeating the Derrick Man",PP('Pose-upset.png')),
    I("Invisible","Cheesy Effect","Awarded from the Cream-Be-Gone sidetask in Toontown Central",CE('CE_invisible.png')),
  ]},
  { name:"Barnacle Boatyard", icon:"⚓", color:"#5a1a05", accent:"#dc4a14", items:[
    I("Barnacle Boatyard","Background","Awarded for progressing to Barnacle Boatyard in the Taskline",BG('BarnacleBoatyard.png')),
    I("Barnacle Boatyard Sky","Background","Awarded for visiting Barnacle Boatyard",BG('BarnacleBoatyardSkyBackground.png')),
    I("On The Dock","Background","Awarded after completing Silverware Sting Kudos Rank-Up Task",BG('OnTheDockBackground.png')),
    I("Barnacle Boatyard","Nameplate","Awarded for visiting Barnacle Boatyard",NP('BarnacleBoatyardNameplate.png')),
    I("Sandcastles","Nameplate","Awarded for riding the Boat for 20 Laps",NP('SandcastlesNameplate.png')),
    I("Boardwalk","Nametag","Awarded after completing a Barnacle Boatyard task",NT('Boardwalk.png')),
    I("Nautical","Nametag","Awarded after completing a Barnacle Boatyard task",NT('Nautical_Nametag.png')),
    I("Pirate","Nametag","Awarded after completing a Barnacle Boatyard task",NT('Pirate_Nametag.png')),
    I("Wonky","Nametag","Awarded after completing a Barnacle Boatyard task",NT('Wonky.png')),
    I("Diving","Profile Pose","Awarded after completing the task Swimming Kiwi",PP('Pose-diving.png')),
    I("I'm Outta Here!","Profile Pose","Awarded after defeating the Land Acquisition Architect",PP("Pose-I'm_outta_here.png")),
    I("Treasure","Profile Pose","Awarded after reaching Barnacle Boatyard Kudos Rank 5",PP('Pose-Treasure.png')),
    I("Big Legs","Cheesy Effect","Awarded after completing The Salty Spit-toon sidetask",CE('CE_biglegs.png')),
  ]},
  { name:"Ye Olde Toontowne", icon:"👑", color:"#33205e", accent:"#9b70cc", items:[
    I("Ye Olde Toontowne","Background","Awarded for progressing to Ye Olde Toontowne in the Taskline",BG('YeOleToontowneBackground.png')),
    I("Ye Olde Toontowne Sky","Background","Awarded for visiting Ye Olde Toontowne",BG('YOTTskyBackground.png')),
    I("Hearty Feast","Background","Awarded from a special event",BG('HeartyFeastBackground.png')),
    I("Ye Olde Toontowne","Nameplate","Awarded for visiting Ye Olde Toontowne",NP('YOTT.png')),
    I("The Doodragon","Nameplate","Awarded from a special event",NP('TheDoodragonNameplate.png')),
    I("Medieval","Nametag","Awarded after completing a Ye Olde Toontowne task",NT('Medieval_Nametag.png')),
    I("Poetic","Nametag","Awarded after completing a Ye Olde Toontowne task",NT('Poetic.png')),
    I("At The Gate","Profile Pose","Awarded after reaching Ye Olde Toontowne Kudos Rank 5",PP('Pose-At_The_Gate.png')),
    I("Casting","Profile Pose","Awarded after completing the task The Golden Penny",PP('Pose-casting.png')),
    I("To Be or Not To Be?","Profile Pose","Awarded after defeating the Public Relations Representative",PP('Pose-To_be_or_not_to_be.png')),
    I("Small Head","Cheesy Effect","Purchasable or event reward",CE('CE_smallhead.png')),
    I("Transparent","Cheesy Effect","Purchasable or event reward",CE('CE_transparent.png')),
  ]},
  { name:"Daffodil Gardens", icon:"🌸", color:"#314600", accent:"#9bd31a", items:[
    I("Daffodil Gardens","Background","Awarded for progressing to Daffodil Gardens in the Taskline",BG('DaffodilGardensBackground.png')),
    I("Daffodil Gardens Sky","Background","Awarded for visiting Daffodil Gardens",BG('DaffodilSkysBackground.png')),
    I("Tranquil Fountain","Background","Awarded from a special event",BG('TranquilFountainBackground.png')),
    I("Daffodil Gardens","Nameplate","Awarded for visiting Daffodil Gardens",NP('DaffodilNameplate.png')),
    I("Gardening","Nameplate","Awarded after completing a Daffodil Gardens Kudos Rank-Up Task",NP('GardeningNameplate.png')),
    I("Calligraphy","Nametag","Awarded after completing a Daffodil Gardens task",NT('Calligraphy_Nametag.png')),
    I("Silly","Nametag","Awarded after completing a Daffodil Gardens task",NT('Silly_Nametag.png')),
    I("Elegance","Profile Pose","Awarded after reaching Daffodil Gardens Kudos Rank 5",PP('Pose-Elegance.png')),
    I("Running","Profile Pose","Awarded after completing the task Wedding Planner",PP('Pose-running.png')),
    I("Flat Portrait","Cheesy Effect","Purchasable or event reward",CE('CE_flatportrait.png')),
    I("Green Toon","Cheesy Effect","Awarded from the Monkey See Monkey Do sidetask",CE('CE_greentoon.png')),
  ]},
  { name:"Mezzo Melodyland", icon:"🎵", color:"#482052", accent:"#bf62cb", items:[
    I("Mezzo Melodyland","Background","Awarded for progressing to Mezzo Melodyland in the Taskline",BG('MezzoMelodylandBackground.png')),
    I("Mezzo Melodyland Sky","Background","Awarded for visiting Mezzo Melodyland",BG('MezzoMelodylandSky.png')),
    I("Rock Concert","Background","Awarded from a special event",BG('RockConcertBackground.png')),
    I("Mezzo Melodyland","Nameplate","Awarded for visiting Mezzo Melodyland",NP('MezzoMelodylandNameplate.png')),
    I("Fire n' Flames","Nameplate","Awarded from a special event",NP("FiresN'FlamesNameplate.png")),
    I("Fancy","Nametag","Awarded after completing a Mezzo Melodyland task",NT('Fancy_Nametag.png')),
    I("Playful","Nametag","Awarded after completing a Mezzo Melodyland task",NT('Playful_Nametag.png')),
    I("Whimsical","Nametag","Awarded after completing a Mezzo Melodyland task",NT('Whimsical_Nametag.png')),
    I("Pick Up The Phone","Profile Pose","Awarded after reaching Mezzo Melodyland Kudos Rank 5",PP('Pose-Pick_Up_The_Phone.png')),
    I("Presenting...","Profile Pose","Awarded after completing the task Piano Player",PP('Pose-presenting.png')),
    I("Big Head","Cheesy Effect","Purchasable or event reward",CE('CE_bighead.png')),
    I("Flat Profile","Cheesy Effect","Purchasable or event reward",CE('CE_flatprofile.png')),
  ]},
  { name:"The Brrrgh", icon:"❄️", color:"#003a46", accent:"#29b2dc", items:[
    I("The Brrrgh","Background","Awarded for progressing to The Brrrgh in the Taskline",BG('TheBrrrghBackground.png')),
    I("The Brrrgh Sky","Background","Awarded for visiting The Brrrgh",BG('BrrrghSkyBackground.png')),
    I("Doodlesledding","Background","Awarded from the Doodlesledding event",BG('DoodlesleddingBackground.png')),
    I("The Brrrgh","Nameplate","Awarded for visiting The Brrrgh",NP('BrrrghNameplate.png')),
    I("Snowball Fight","Nameplate","Awarded from a special event",NP('SnowballFightNameplate.png')),
    I("Scarf","Nameplate","Awarded after completing a The Brrrgh Kudos Rank-Up Task",NP('ScarfNameplate.png')),
    I("Comical","Nametag","Awarded after completing a The Brrrgh task",NT('Comical_Nametag.png')),
    I("Shivering","Nametag","Awarded after completing a The Brrrgh task",NT('Shivering_Nametag.png')),
    I("Fire Hands","Profile Pose","Awarded after reaching The Brrrgh Kudos Rank 5",PP('Pose-fire-hands.gif')),
    I("Surprised","Profile Pose","Awarded after completing the task Gathering Warmth",PP('Pose-surprised.png')),
    I("Big White Toon","Cheesy Effect","Purchasable or event reward",CE('CE_bigwhitetoon.png')),
    I("No Color","Cheesy Effect","Purchasable or event reward",CE('CE_nocolor.png')),
    I("Wireframe","Cheesy Effect","Purchasable or event reward",CE('CE_wireframe.png')),
  ]},
  { name:"Acorn Acres", icon:"🌰", color:"#00451e", accent:"#20cf69", items:[
    I("Acorn Acres","Background","Awarded for progressing to Acorn Acres in the Taskline",BG('AABackground.png')),
    I("Acorn Acres Sky","Background","Awarded for visiting Acorn Acres",BG('AASkyBackground.png')),
    I("Light Show","Background","Awarded from a special event",BG('LightShowBackground.png')),
    I("Acorn Acres","Nameplate","Awarded for visiting Acorn Acres",NP('AANameplate.png')),
    I("Light Show","Nameplate","Awarded from a special event",NP('LightsShowNameplate.png')),
    I("Arrogant","Nametag","Awarded after completing an Acorn Acres task",NT('Arrogant_Nametag.png')),
    I("Practical","Nametag","Awarded after completing an Acorn Acres task",NT('PracticalNametag.png')),
    I("Greened","Profile Pose","Awarded after completing the task Survival Kit Builder",PP('Pose-greened.png')),
    I("Rolled","Profile Pose","Awarded after reaching Acorn Acres Kudos Rank 5",PP('Pose-Rolled.png')),
    I("Big Toon","Cheesy Effect","Purchasable or event reward",CE('CE_bigtoon.png')),
    I("Small Legs","Cheesy Effect","Purchasable or event reward",CE('CE_smalllegs.png')),
  ]},
  { name:"Drowsy Dreamland", icon:"💤", color:"#1a1060", accent:"#7b68ee", items:[
    I("Drowsy Dreamland","Background","Awarded for progressing to Drowsy Dreamland in the Taskline",BG('DrowsyDreamlandBackground.png')),
    I("Drowsy Dreamland Sky","Background","Awarded for visiting Drowsy Dreamland",BG('DrowsyDreamlandPGBackground.png')),
    I("Sweet","Background","Awarded from a special event",BG('SweetBackground.png')),
    I("Drowsy Dreamland","Nameplate","Awarded for visiting Drowsy Dreamland",NP('DrowsyDreamlandNameplate.png')),
    I("Sweet","Nameplate","Awarded from a special event",NP('SweetNameplate.png')),
    I("Action","Nametag","Awarded after completing a Drowsy Dreamland task",NT('ActionNametag.png')),
    I("Cinema","Nametag","Awarded after completing a Drowsy Dreamland task",NT('CinemaNametag.png')),
    I("Western","Nametag","Awarded after completing a Drowsy Dreamland task",NT('WesternNametag.png')),
    I("Resistance Salute","Emotion","Say SpeedChat \"Would you like some help?\" under Friendly to Whispering Willow in Talking In Your Sleep Voice Training on Pajama Place, Drowsy Dreamland",EM('neutral/Resistance_Salute.gif')),
    I("Naptime","Profile Pose","Awarded after reaching Drowsy Dreamland Kudos Rank 5",PP('Pose-Naptime.png')),
    I("Yawn","Profile Pose","Awarded after completing the task Camera Repair",PP('Pose-yawning.png')),
    I("Small Toon","Cheesy Effect","Purchasable or event reward",CE('CE_smalltoon.png')),
  ]},
  { name:"Unobtainable", icon:"🔒", color:"#1a1a1a", accent:"#888888", items:[
    I("Sky Clan","Background","Awarded for completing a Sky Clan task during the Mayday event",BG('SkyclanBackground.png')),
    I("Break The Law!","Background","Awarded for getting 4 Pink Slip Pieces during Break The Law",BG('BTLbackground.png')),
    I("New Years 2019 Fireworks","Background","Awarded during the 2019 New Years Event",BG('NewYear2019Background.png')),
    I("New Years 2020 Fireworks","Background","Awarded during the 2020 New Years Event",BG('NewYears2020Background.png')),
    I("Easter 2020","Background","Awarded after using the Easter 2020 code",BG('Easter2020Background.png')),
    I("Valentine's 2020","Background","Awarded after using the Valentoon's 2020 code",BG('Valentines2020Background.png')),
    I("Artificial Progeny","Background","Awarded for defeating the Witness Stand-In during Break The Law",BG('ArtificalProgenyBackground.png')),
    I("Fireworks Show","Background","Awarded after using the 2020 Summer code",BG('FireworksShowBackground.png')),
    I("Dreams Come True","Nameplate","Awarded from a special event",NP('DreamsComeTrue.png')),
    I("Atticus' Desk","Nameplate","Awarded from a special event",NP('AtticusDeskNameplate.png')),
    I("Pink Slip","Nameplate","Awarded for completing a Sky Clan task during the Mayday event",NP('PinkSlipNameplate.png')),
    I("Thanksgiving 2019","Nameplate","Awarded for attending the 2019 Thanksgiving Event",NP('Thanksgiving2019Namepalte.png')),
    I("New Years Fireworks 2019","Nameplate","Awarded for attending the 2019 New Years Event",NP('2019Nameplate.png')),
    I("New Years Fireworks 2020","Nameplate","Awarded for attending the 2020 New Years Event",NP('2020Nameplate.png')),
    I("Easter 2020","Nameplate","Awarded for using the 2020 Easter Event code",NP('Easter2020Nameplate.png')),
    I("Candy","Nameplate","Unobtainable event reward",NP('Candy.png')),
    I("Prepare for Launch","Nameplate","Awarded after using the 2020 Summer code",NP('PrepareForLaunchNameplate.png')),
    I("Pink Slip","Cheesy Effect","Awarded for getting 6 Pink Slip Pieces during Break The Law",CE('CE_Pinkslip.png')),
  ]},
];
export const COLLECTION_TYPES = ['Background','Nameplate','Nametag','Profile Pose','Cheesy Effect','Emotion'] as const;
export type CollectionType = typeof COLLECTION_TYPES[number];
